/**
 * Performance Tear-Sheet Page
 * Comprehensive portfolio vs NIFTY 50 QuantStats analytics suite with educational explainer engine
 */

'use client';

import React, { useState, useEffect } from 'react';
import { MetricCard } from '@/components/ui/MetricCard';
import { analyticsApi } from '@/lib/api';
import {
  Newspaper,
  AlertTriangle,
  RefreshCw,
  TrendingUp,
  Activity,
  CalendarDays,
  Scale,
  Download,
  HelpCircle,
  X,
  Info,
  ShieldAlert,
  Percent,
  BarChart2,
  PieChart,
  Layers,
  ArrowUpRight,
  ArrowDownRight
} from 'lucide-react';

interface ExplainerContent {
  title: string;
  what: string;
  howInferred: string;
  whyImportant: string;
  howToInfer: string;
  benchmark?: string;
}

const EXPLAINERS: Record<string, ExplainerContent> = {
  total_return: {
    title: 'Compounded Total Return',
    what: 'The cumulative percentage growth of your portfolio over the entire 1-year analysis window, assuming full dividend and cash compounding.',
    howInferred: 'Calculated as R_total = ∏(1 + R_t) - 1 across all 252 trading days.',
    whyImportant: 'The headline bottom-line figure showing overall nominal capital growth.',
    howToInfer: '25.75% means ₹1,00,000 invested 1 year ago has grown into ₹1,25,750 today.',
    benchmark: 'Nifty 50 1-Year Total Return: -2.6% (Portfolio Alpha: +28.4%).'
  },
  cagr: {
    title: 'Compound Annual Growth Rate (CAGR)',
    what: 'The smoothed annualized geometric rate of return that would take the portfolio from its starting value to its ending value.',
    howInferred: 'CAGR = (1 + R_total)^(252 / N) - 1, where N is the number of trading sessions.',
    whyImportant: 'Standardizes returns to an annual basis for fair comparison against multi-year benchmarks, Fixed Deposits (6.5%), and debt yields.',
    howToInfer: 'Above 18% is top-decile multi-cap performance in Indian markets.',
    benchmark: 'Long-term Indian equity historical CAGR benchmark: 12.0% – 14.0%.'
  },
  sharpe_ratio: {
    title: 'Sharpe Ratio (Rf = 2.0%)',
    what: 'The classic measure of risk-adjusted excess return per unit of total volatility.',
    howInferred: 'Sharpe = (Annualized Return - Risk-Free Rate) / Annualized Volatility. Uses 2.0% risk-free hurdle.',
    whyImportant: 'Determines whether superior returns are generated through genuine investment skill or reckless leverage/volatility.',
    howToInfer: 'Below 1.0 = Sub-optimal; 1.0 – 1.5 = Good; Above 1.5 = Outstanding risk efficiency.',
    benchmark: 'Current Portfolio: 1.26 vs NIFTY 50: -0.20.'
  },
  max_drawdown: {
    title: 'Maximum Drawdown (Peak-to-Trough)',
    what: 'The largest cumulative percentage decline experienced from a historical peak before establishing a new peak.',
    howInferred: 'MDD = min_t ( (V_t - max_{τ ≤ t} V_τ) / max_{τ ≤ t} V_τ ).',
    whyImportant: 'Measures downside capital destruction risk and psychological pain tolerance during market panics.',
    howToInfer: '-14.24% means at its deepest drawdown (March 2026 correction), the portfolio temporarily declined 14.24% from its highest peak.',
    benchmark: 'Standard equity mandate drawdown ceiling: ≤ -20.0%.'
  },
  beta_vs_nifty: {
    title: 'Market Beta (β vs NIFTY 50)',
    what: 'The statistical sensitivity of portfolio returns relative to benchmark market swings.',
    howInferred: 'Beta = Cov(R_portfolio, R_nifty) / Var(R_nifty).',
    whyImportant: 'Identifies systemic market exposure: β = 1.0 indicates identical market movement; β > 1.0 indicates higher cyclical volatility.',
    howToInfer: '1.06 indicates the portfolio tends to move 6% more than the NIFTY 50 during broad market rallies and corrections.',
    benchmark: 'Balanced multi-cap target: 0.90 – 1.10.'
  },
  alpha_annualized: {
    title: 'Annualized Jensen Alpha (α)',
    what: 'The excess return generated by the portfolio above what is predicted by the Capital Asset Pricing Model (CAPM) beta.',
    howInferred: 'Alpha = R_portfolio - (R_f + β × (R_nifty - R_f)) annualized.',
    whyImportant: 'The purest measure of active quantitative value-add over passive indexing.',
    howToInfer: '28.51% indicates massive active outperformance generated by high-conviction scrip selection (MCX, Motherson, Redington).',
    benchmark: 'Institutional hurdle: Alpha > +3.0%.'
  },
  sortino_ratio: {
    title: 'Sortino Ratio (Downside Risk-Adjusted)',
    what: 'A refined Sharpe ratio variant that penalizes only downside volatility, ignoring beneficial upside volatility.',
    howInferred: 'Sortino = (R_portfolio - R_f) / Downside_Deviation.',
    whyImportant: 'Investors welcome upward volatility; penalizing upside moves in the Sharpe denominator can be misleading. Sortino isolates true downside risk.',
    howToInfer: 'Above 1.5 indicates strong downside protection during corrections.',
    benchmark: 'Typical top-quartile PMS target: Sortino > 1.40.'
  },
  calmar_ratio: {
    title: 'Calmar Ratio (CAGR to Drawdown)',
    what: 'The ratio of annualized compounded return to the absolute maximum drawdown.',
    howInferred: 'Calmar = CAGR / |Max Drawdown| = 25.98% / 14.24% = 1.82.',
    whyImportant: 'Heavily used by hedge funds and CTA trend-followers to evaluate recovery capability after severe drawdowns.',
    howToInfer: 'Above 1.5 is considered exceptional risk-return asymmetry.',
    benchmark: 'Institutional target: Calmar > 1.0.'
  },
  omega_ratio: {
    title: 'Omega Ratio',
    what: 'The probability-weighted ratio of cumulative gains versus cumulative losses relative to the target hurdle.',
    howInferred: 'Calculated as the integral of the return distribution above threshold divided by the integral below threshold.',
    whyImportant: 'Captures all statistical return moments (mean, variance, skewness, and kurtosis) simultaneously.',
    howToInfer: 'Omega > 1.20 indicates that upside probability mass significantly outweighs downside tail risk.',
    benchmark: 'Standard baseline: > 1.15.'
  },
  tail_ratio: {
    title: 'Tail Ratio (95th vs 5th Percentile)',
    what: 'The magnitude of extreme positive returns (95th percentile) relative to extreme negative returns (5th percentile).',
    howInferred: 'Tail Ratio = |95th percentile daily return| / |5th percentile daily return|.',
    whyImportant: 'Shows whether favorable tail events are bigger than adverse tail shocks.',
    howToInfer: 'Above 1.0 indicates right-skewed positive tail payoff asymmetry.',
    benchmark: 'Target: > 1.05.'
  },
  skewness: {
    title: 'Return Distribution Skewness',
    what: 'A measure of asymmetry in daily returns around the portfolio mean.',
    howInferred: 'Computed as the normalized third statistical moment E[(R - μ)^3] / σ^3.',
    whyImportant: 'Positive skew means frequent moderate returns with rare massive upward surprises; negative skew warns of sudden steep drops.',
    howToInfer: 'Values between -0.5 and +0.5 indicate a well-balanced distribution without fatal left-tail collapse.',
    benchmark: 'Normal distribution benchmark = 0.0.'
  },
  kurtosis: {
    title: 'Excess Kurtosis (Fat-Tail Indicator)',
    what: 'A measure of whether returns exhibit fatter tails and sharper peaks than a Gaussian normal curve.',
    howInferred: 'Computed as E[(R - μ)^4] / σ^4 - 3.',
    whyImportant: 'High positive kurtosis (> 3) warns of "black swan" jump risks.',
    howToInfer: 'Helps evaluate tail risk buffers and stop-loss placement.',
    benchmark: 'Standard Gaussian = 0.0 (Mesokurtic).'
  },
  monthly_returns: {
    title: 'Monthly Return Heatmap',
    what: 'Chronological calendar matrix showing discrete monthly compounded percentage performance.',
    howInferred: 'Calculated as ∏_{day ∈ month}(1 + R_t) - 1 for each calendar month.',
    whyImportant: 'Visualizes return consistency, winning streaks, and seasonal drawdown clusters.',
    howToInfer: 'Green cells represent positive months; red cells represent negative months. Darker saturation indicates larger percentage magnitude.'
  },
  underwater_curve: {
    title: 'Underwater Drawdown Curve',
    what: 'Continuous time-series trace of the portfolio\'s percentage decline from its all-time high watermark.',
    howInferred: 'Drawdown_t = (V_t - max_{τ ≤ t} V_τ) / max_{τ ≤ t} V_τ at daily resolution.',
    whyImportant: 'Shows the exact duration and recovery path of every drawdown cycle throughout the year.',
    howToInfer: 'A flat line at 0.0% means the portfolio is at an all-time high. Valleys illustrate how deep drops went and how many days it took to recover.'
  },
  weights_used: {
    title: 'Constituent Asset Weights',
    what: 'The active allocation percentage assigned to each security in the portfolio across the 1-year evaluation period.',
    howInferred: 'Derived from current portfolio database holdings and normalized to sum to 100.0%.',
    whyImportant: 'Reveals which specific scrips drove the tear-sheet performance results.',
    howToInfer: 'Check largest weights (Motherson 13.6%, JuniorBees 12.8%, Midcap ETF 10.5%) to understand return drivers.'
  }
};

function HelpExplainerModal({ itemKey, onClose }: { itemKey: string; onClose: () => void }) {
  const info = EXPLAINERS[itemKey];
  if (!info) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-fadeIn">
      <div className="bg-slate-900 border border-slate-700 rounded-xl max-w-xl w-full p-6 shadow-2xl relative text-slate-100 max-h-[90vh] overflow-y-auto">
        <button
          onClick={onClose}
          className="absolute top-4 right-4 text-slate-400 hover:text-white p-1 rounded-lg hover:bg-slate-800 transition-colors"
          aria-label="Close explainer"
        >
          <X className="w-5 h-5" />
        </button>

        <div className="flex items-center space-x-3 mb-4">
          <div className="p-2 bg-emerald-500/20 text-emerald-400 rounded-lg">
            <Info className="w-6 h-6" />
          </div>
          <h3 className="text-xl font-bold text-white">{info.title}</h3>
        </div>

        <div className="space-y-4 text-sm leading-relaxed">
          <div className="bg-slate-800/80 p-3.5 rounded-lg border border-slate-700/60">
            <h4 className="text-xs font-semibold text-emerald-400 uppercase tracking-wider mb-1">What This Means</h4>
            <p className="text-slate-200">{info.what}</p>
          </div>

          <div className="bg-slate-800/80 p-3.5 rounded-lg border border-slate-700/60">
            <h4 className="text-xs font-semibold text-emerald-400 uppercase tracking-wider mb-1">How It Is Inferred</h4>
            <p className="text-slate-300">{info.howInferred}</p>
          </div>

          <div className="bg-slate-800/80 p-3.5 rounded-lg border border-slate-700/60">
            <h4 className="text-xs font-semibold text-emerald-400 uppercase tracking-wider mb-1">Why It Is Important</h4>
            <p className="text-slate-300">{info.whyImportant}</p>
          </div>

          <div className="bg-slate-800/80 p-3.5 rounded-lg border border-slate-700/60">
            <h4 className="text-xs font-semibold text-emerald-400 uppercase tracking-wider mb-1">How To Interpret</h4>
            <p className="text-slate-300">{info.howToInfer}</p>
          </div>

          {info.benchmark && (
            <div className="bg-emerald-950/40 p-3 rounded-lg border border-emerald-800/50 text-emerald-200 text-xs font-medium">
              💡 <span className="font-semibold text-emerald-300">Quantitative Benchmark:</span> {info.benchmark}
            </div>
          )}
        </div>

        <div className="mt-6 flex justify-end">
          <button
            onClick={onClose}
            className="px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white rounded-lg font-medium text-sm transition-colors"
          >
            Got It
          </button>
        </div>
      </div>
    </div>
  );
}

function HelpBtn({ onClick, label }: { onClick: () => void; label?: string }) {
  return (
    <button
      onClick={(e) => {
        e.stopPropagation();
        onClick();
      }}
      className="inline-flex items-center justify-center w-4 h-4 ml-1.5 text-slate-400 hover:text-emerald-400 rounded-full hover:bg-slate-800/60 transition-colors"
      title={label || 'Click to understand this metric'}
      aria-label={label || 'Explainer info'}
    >
      <HelpCircle className="w-3.5 h-3.5" />
    </button>
  );
}

interface TearSheetData {
  window: { start: string; end: string };
  holdings: Record<string, number>;
  metrics: Record<string, number | null>;
  relative_vs_nifty: Record<string, number | null>;
  monthly_returns: Record<string, Record<string, number>>;
  underwater: { date: string; drawdown: number }[];
  methodology: string;
}

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

export default function TearSheetPage() {
  const [data, setData] = useState<TearSheetData | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [activeExplainer, setActiveExplainer] = useState<string | null>(null);

  const fetchTearSheet = async () => {
    setLoading(true);
    setError(null);
    try {
      const result = await analyticsApi.getTearSheet();
      setData(result);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load tear-sheet data');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchTearSheet();
  }, []);

  const fmt = (value: number | null | undefined, decimals = 2, suffix = '') => {
    if (value === null || value === undefined || Number.isNaN(value)) return 'N/A';
    return `${(value * 100).toFixed(decimals)}${suffix}`;
  };

  const fmtRatio = (value: number | null | undefined, decimals = 2) => {
    if (value === null || value === undefined || Number.isNaN(value)) return 'N/A';
    return value.toFixed(decimals);
  };

  const heatColor = (value: number): string => {
    const capped = Math.max(-0.08, Math.min(0.08, value));
    if (capped >= 0) return `rgba(16, 185, 129, ${0.20 + (capped / 0.08) * 0.75})`;
    return `rgba(239, 68, 68, ${0.20 + (-capped / 0.08) * 0.75})`;
  };

  const years = data ? Object.keys(data.monthly_returns).sort() : [];

  const drawdownPoints = data?.underwater ?? [];
  const worstDrawdown = drawdownPoints.length
    ? Math.min(...drawdownPoints.map((p) => p.drawdown))
    : null;

  // Calculate annual return per year
  const getYearlyTotalReturn = (year: string) => {
    if (!data?.monthly_returns[year]) return null;
    let compounded = 1.0;
    const months = Object.values(data.monthly_returns[year]);
    if (!months.length) return null;
    for (const r of months) {
      compounded *= (1.0 + r);
    }
    return compounded - 1.0;
  };

  // Export CSV
  const handleExportCSV = () => {
    if (!data) return;
    const rows: string[] = [];
    rows.push('Daisy Risk Engine - Performance Tear-Sheet Report');
    rows.push(`Analysis Window,${data.window.start} to ${data.window.end}`);
    rows.push('');
    rows.push('Headline QuantStats Metrics');
    rows.push(`Total Return,${fmt(data.metrics.total_return, 2, '%')}`);
    rows.push(`CAGR,${fmt(data.metrics.cagr, 2, '%')}`);
    rows.push(`Sharpe Ratio,${fmtRatio(data.metrics.sharpe)}`);
    rows.push(`Sortino Ratio,${fmtRatio(data.metrics.sortino)}`);
    rows.push(`Calmar Ratio,${fmtRatio(data.metrics.calmar)}`);
    rows.push(`Omega Ratio,${fmtRatio(data.metrics.omega)}`);
    rows.push(`Tail Ratio,${fmtRatio(data.metrics.tail_ratio)}`);
    rows.push(`Annualized Volatility,${fmt(data.metrics.volatility, 2, '%')}`);
    rows.push(`Max Drawdown,${fmt(data.metrics.max_drawdown, 2, '%')}`);
    rows.push(`Skewness,${fmtRatio(data.metrics.skew)}`);
    rows.push(`Kurtosis,${fmtRatio(data.metrics.kurtosis)}`);
    rows.push('');
    rows.push('Against NIFTY 50 Benchmark');
    rows.push(`Beta vs Nifty,${fmtRatio(data.relative_vs_nifty.beta_vs_nifty)}`);
    rows.push(`Alpha (Annualized),${fmt(data.relative_vs_nifty.alpha_annualized, 2, '%')}`);
    rows.push(`Portfolio Sharpe,${fmtRatio(data.metrics.sharpe)}`);
    rows.push(`Benchmark Sharpe,${fmtRatio(data.relative_vs_nifty.benchmark_sharpe)}`);
    rows.push(`Portfolio Volatility,${fmt(data.metrics.volatility, 2, '%')}`);
    rows.push(`Benchmark Volatility,${fmt(data.relative_vs_nifty.benchmark_volatility, 2, '%')}`);
    rows.push('');
    rows.push('Monthly Returns (Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec, Full Year)');
    for (const y of years) {
      const rowVals = [y];
      for (let m = 1; m <= 12; m++) {
        const val = data.monthly_returns[y]?.[String(m)];
        rowVals.push(val !== undefined ? (val * 100).toFixed(2) + '%' : '-');
      }
      const yTot = getYearlyTotalReturn(y);
      rowVals.push(yTot !== null ? (yTot * 100).toFixed(2) + '%' : '-');
      rows.push(rowVals.join(','));
    }

    const csvContent = 'data:text/csv;charset=utf-8,' + rows.join('\n');
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', `tear_sheet_performance_${new Date().toISOString().split('T')[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="space-y-6">
      {/* Active Explainer Modal */}
      {activeExplainer && (
        <HelpExplainerModal
          itemKey={activeExplainer}
          onClose={() => setActiveExplainer(null)}
        />
      )}

      {/* Hero Section */}
      <div className="bg-gradient-to-r from-emerald-600 via-teal-600 to-cyan-700 rounded-xl p-6 text-white shadow-lg relative overflow-hidden">
        <div className="absolute right-0 top-0 translate-x-8 -translate-y-8 w-64 h-64 bg-white/10 rounded-full blur-3xl pointer-events-none" />
        <div className="flex items-center justify-between relative z-10">
          <div>
            <div className="flex items-center space-x-3 mb-2">
              <h1 className="text-3xl font-bold tracking-tight">Performance Tear-Sheet</h1>
              <span className="px-3 py-0.5 rounded-full text-xs font-semibold bg-white/20 text-white backdrop-blur-sm">
                QUANTSTATS SUITE
              </span>
            </div>
            <p className="text-emerald-100 max-w-2xl text-sm leading-relaxed">
              Institutional-grade performance tear-sheet benchmarking your active portfolio against the NIFTY 50 index across full return and risk dimensions.
            </p>
            {data && (
              <div className="flex flex-wrap items-center mt-4 gap-3">
                <div className="bg-black/20 backdrop-blur-md px-3 py-1.5 rounded-lg text-emerald-100 text-xs font-medium border border-white/10">
                  Window: <span className="font-bold text-white ml-1">{data.window.start} → {data.window.end}</span>
                </div>
                <div className="bg-black/20 backdrop-blur-md px-3 py-1.5 rounded-lg text-emerald-100 text-xs font-medium border border-white/10">
                  Holdings: <span className="font-bold text-white ml-1">{Object.keys(data.holdings).length} active</span>
                </div>
                <div className="bg-black/20 backdrop-blur-md px-3 py-1.5 rounded-lg text-emerald-100 text-xs font-medium border border-white/10">
                  Benchmark: <span className="font-bold text-white ml-1">NIFTY 50 (^NSEI)</span>
                </div>
              </div>
            )}
          </div>
          <div className="hidden md:flex items-center space-x-3">
            <button
              onClick={handleExportCSV}
              disabled={!data || loading}
              className="flex items-center bg-white/20 hover:bg-white/30 rounded-xl px-3.5 py-2.5 text-xs font-semibold transition-colors border border-white/10 shadow-sm"
              title="Export Performance Report to CSV"
            >
              <Download className="w-4 h-4 mr-1.5 text-emerald-200" />
              Export CSV
            </button>
            <button
              onClick={fetchTearSheet}
              disabled={loading}
              className="bg-white/20 hover:bg-white/30 rounded-xl p-2.5 transition-colors border border-white/10 shadow-sm"
              title="Refresh Tear-Sheet Metrics"
            >
              <RefreshCw className={`w-5 h-5 ${loading ? 'animate-spin' : ''}`} />
            </button>
            <div className="p-3 bg-white/10 backdrop-blur-md rounded-xl border border-white/20 shadow-inner">
              <Newspaper className="w-10 h-10 text-emerald-200" />
            </div>
          </div>
        </div>
      </div>

      {/* Error State */}
      {error && (
        <div className="bg-rose-950/30 border border-rose-800/50 rounded-xl p-4 text-rose-200 text-sm flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <AlertTriangle className="w-5 h-5 text-rose-400 shrink-0" />
            <div>
              <h4 className="font-semibold text-rose-300">Could not build performance tear-sheet</h4>
              <p className="text-xs text-rose-400 mt-0.5">{error}</p>
            </div>
          </div>
          <button
            onClick={fetchTearSheet}
            className="px-3 py-1.5 bg-rose-900/60 hover:bg-rose-800 rounded-lg text-xs font-semibold text-rose-100 transition-colors"
          >
            Try Again
          </button>
        </div>
      )}

      {/* Loading State */}
      {loading && !data && (
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-8 text-center space-y-3">
          <RefreshCw className="w-8 h-8 text-emerald-400 animate-spin mx-auto" />
          <h3 className="text-base font-semibold text-white">Computing QuantStats Performance Suite...</h3>
          <p className="text-xs text-slate-400">
            Evaluating historical returns, benchmark covariance, and underwater drawdown series.
          </p>
        </div>
      )}

      {/* Main Content */}
      {!loading && !error && data && (
        <>
          {/* Headline 4 Core Metrics */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            <div className="relative group">
              <MetricCard
                title="Total Return"
                value={fmt(data.metrics.total_return, 2, '%')}
                icon={TrendingUp}
                loading={loading}
              />
              <div className="absolute top-4 right-4 z-10">
                <HelpBtn onClick={() => setActiveExplainer('total_return')} />
              </div>
            </div>

            <div className="relative group">
              <MetricCard
                title="CAGR"
                value={fmt(data.metrics.cagr, 2, '%')}
                icon={Activity}
                loading={loading}
              />
              <div className="absolute top-4 right-4 z-10">
                <HelpBtn onClick={() => setActiveExplainer('cagr')} />
              </div>
            </div>

            <div className="relative group">
              <MetricCard
                title="Sharpe Ratio"
                value={fmtRatio(data.metrics.sharpe)}
                icon={Scale}
                loading={loading}
              />
              <div className="absolute top-4 right-4 z-10">
                <HelpBtn onClick={() => setActiveExplainer('sharpe_ratio')} />
              </div>
            </div>

            <div className="relative group">
              <MetricCard
                title="Max Drawdown"
                value={fmt(data.metrics.max_drawdown, 2, '%')}
                icon={AlertTriangle}
                loading={loading}
              />
              <div className="absolute top-4 right-4 z-10">
                <HelpBtn onClick={() => setActiveExplainer('max_drawdown')} />
              </div>
            </div>
          </div>

          {/* Relative vs NIFTY 50 */}
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-sm">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center space-x-2">
                <h3 className="text-lg font-bold text-white">Against NIFTY 50 Benchmark</h3>
                <HelpBtn onClick={() => setActiveExplainer('alpha_annualized')} />
              </div>
              <span className="text-xs px-2.5 py-1 rounded-full bg-slate-800 text-slate-300 border border-slate-700 font-mono">
                Benchmark: ^NSEI
              </span>
            </div>

            {Object.keys(data.relative_vs_nifty).length === 0 ? (
              <p className="text-sm text-slate-400">Benchmark history unavailable for this window.</p>
            ) : (
              <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4 pt-1">
                <div className="p-3.5 rounded-lg bg-slate-800/40 border border-slate-700/50 relative group">
                  <div className="flex items-center justify-between mb-1">
                    <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Beta</span>
                    <HelpBtn onClick={() => setActiveExplainer('beta_vs_nifty')} />
                  </div>
                  <p className="text-xl font-bold font-mono text-white">
                    {fmtRatio(data.relative_vs_nifty.beta_vs_nifty)}
                  </p>
                  <span className="text-[10px] text-slate-400 mt-0.5 block">Market Sensitivity</span>
                </div>

                <div className="p-3.5 rounded-lg bg-emerald-950/20 border border-emerald-800/40 relative group">
                  <div className="flex items-center justify-between mb-1">
                    <span className="text-xs font-semibold text-emerald-400 uppercase tracking-wider">Alpha (Ann.)</span>
                    <HelpBtn onClick={() => setActiveExplainer('alpha_annualized')} />
                  </div>
                  <p className="text-xl font-bold font-mono text-emerald-300">
                    +{fmt(data.relative_vs_nifty.alpha_annualized, 2, '%')}
                  </p>
                  <span className="text-[10px] text-emerald-400/80 mt-0.5 block">Active Outperformance</span>
                </div>

                <div className="p-3.5 rounded-lg bg-slate-800/40 border border-slate-700/50 relative group">
                  <div className="flex items-center justify-between mb-1">
                    <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Portfolio Sharpe</span>
                    <HelpBtn onClick={() => setActiveExplainer('sharpe_ratio')} />
                  </div>
                  <p className="text-xl font-bold font-mono text-teal-300">
                    {fmtRatio(data.metrics.sharpe)}
                  </p>
                  <span className="text-[10px] text-slate-400 mt-0.5 block">Risk Efficiency</span>
                </div>

                <div className="p-3.5 rounded-lg bg-slate-800/40 border border-slate-700/50 relative group">
                  <div className="flex items-center justify-between mb-1">
                    <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Nifty Sharpe</span>
                    <HelpBtn onClick={() => setActiveExplainer('sharpe_ratio')} />
                  </div>
                  <p className="text-xl font-bold font-mono text-slate-300">
                    {fmtRatio(data.relative_vs_nifty.benchmark_sharpe)}
                  </p>
                  <span className="text-[10px] text-slate-400 mt-0.5 block">Index Risk Efficiency</span>
                </div>

                <div className="p-3.5 rounded-lg bg-slate-800/40 border border-slate-700/50 relative group">
                  <div className="flex items-center justify-between mb-1">
                    <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Portfolio Vol</span>
                    <HelpBtn onClick={() => setActiveExplainer('portfolio_volatility')} />
                  </div>
                  <p className="text-xl font-bold font-mono text-amber-300">
                    {fmt(data.metrics.volatility, 2, '%')}
                  </p>
                  <span className="text-[10px] text-slate-400 mt-0.5 block">1-Yr Realized Risk</span>
                </div>

                <div className="p-3.5 rounded-lg bg-slate-800/40 border border-slate-700/50 relative group">
                  <div className="flex items-center justify-between mb-1">
                    <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Nifty Vol</span>
                    <HelpBtn onClick={() => setActiveExplainer('benchmark_volatility')} />
                  </div>
                  <p className="text-xl font-bold font-mono text-slate-300">
                    {fmt(data.relative_vs_nifty.benchmark_volatility, 2, '%')}
                  </p>
                  <span className="text-[10px] text-slate-400 mt-0.5 block">Index Realized Risk</span>
                </div>
              </div>
            )}
          </div>

          {/* Extended QuantStats Advanced Risk-Adjusted Suite */}
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-sm">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center space-x-2">
                <h3 className="text-lg font-bold text-white">Risk-Adjusted Return & Distribution Suite</h3>
                <span className="px-2 py-0.5 rounded text-[11px] font-semibold bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
                  ADVANCED ANALYTICS
                </span>
              </div>
              <Activity className="w-5 h-5 text-slate-400" />
            </div>

            <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-4">
              <div className="p-3.5 rounded-lg bg-slate-800/40 border border-slate-700/50">
                <div className="flex items-center justify-between mb-1">
                  <span className="text-xs font-semibold text-slate-400">Sortino Ratio</span>
                  <HelpBtn onClick={() => setActiveExplainer('sortino_ratio')} />
                </div>
                <p className="text-lg font-bold font-mono text-emerald-400">{fmtRatio(data.metrics.sortino)}</p>
                <span className="text-[10px] text-slate-500">Downside Adjusted</span>
              </div>

              <div className="p-3.5 rounded-lg bg-slate-800/40 border border-slate-700/50">
                <div className="flex items-center justify-between mb-1">
                  <span className="text-xs font-semibold text-slate-400">Calmar Ratio</span>
                  <HelpBtn onClick={() => setActiveExplainer('calmar_ratio')} />
                </div>
                <p className="text-lg font-bold font-mono text-teal-300">{fmtRatio(data.metrics.calmar)}</p>
                <span className="text-[10px] text-slate-500">CAGR / Max DD</span>
              </div>

              <div className="p-3.5 rounded-lg bg-slate-800/40 border border-slate-700/50">
                <div className="flex items-center justify-between mb-1">
                  <span className="text-xs font-semibold text-slate-400">Omega Ratio</span>
                  <HelpBtn onClick={() => setActiveExplainer('omega_ratio')} />
                </div>
                <p className="text-lg font-bold font-mono text-cyan-300">{fmtRatio(data.metrics.omega)}</p>
                <span className="text-[10px] text-slate-500">Gain / Loss Mass</span>
              </div>

              <div className="p-3.5 rounded-lg bg-slate-800/40 border border-slate-700/50">
                <div className="flex items-center justify-between mb-1">
                  <span className="text-xs font-semibold text-slate-400">Tail Ratio</span>
                  <HelpBtn onClick={() => setActiveExplainer('tail_ratio')} />
                </div>
                <p className="text-lg font-bold font-mono text-blue-300">{fmtRatio(data.metrics.tail_ratio)}</p>
                <span className="text-[10px] text-slate-500">95th vs 5th Pct</span>
              </div>

              <div className="p-3.5 rounded-lg bg-slate-800/40 border border-slate-700/50">
                <div className="flex items-center justify-between mb-1">
                  <span className="text-xs font-semibold text-slate-400">Skewness</span>
                  <HelpBtn onClick={() => setActiveExplainer('skewness')} />
                </div>
                <p className="text-lg font-bold font-mono text-slate-200">{fmtRatio(data.metrics.skew)}</p>
                <span className="text-[10px] text-slate-500">Return Asymmetry</span>
              </div>

              <div className="p-3.5 rounded-lg bg-slate-800/40 border border-slate-700/50">
                <div className="flex items-center justify-between mb-1">
                  <span className="text-xs font-semibold text-slate-400">Kurtosis</span>
                  <HelpBtn onClick={() => setActiveExplainer('kurtosis')} />
                </div>
                <p className="text-lg font-bold font-mono text-slate-200">{fmtRatio(data.metrics.kurtosis)}</p>
                <span className="text-[10px] text-slate-500">Fat-Tail Peak</span>
              </div>
            </div>
          </div>

          {/* Monthly Returns Heatmap */}
          {years.length > 0 && (
            <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-sm overflow-x-auto">
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center space-x-2">
                  <h3 className="text-lg font-bold text-white">Monthly Returns Heatmap (%)</h3>
                  <HelpBtn onClick={() => setActiveExplainer('monthly_returns')} />
                </div>
                <CalendarDays className="w-5 h-5 text-slate-400" />
              </div>

              <table className="min-w-full tabular-nums border-collapse">
                <thead>
                  <tr className="border-b border-slate-800">
                    <th className="text-left text-xs font-bold text-slate-400 pb-3 pr-4">Year</th>
                    {MONTHS.map((m) => (
                      <th key={m} className="text-center text-xs font-semibold text-slate-400 pb-3 px-1.5 min-w-[54px]">
                        {m}
                      </th>
                    ))}
                    <th className="text-right text-xs font-bold text-emerald-400 pb-3 pl-4">Year Total</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-800/50">
                  {years.map((year) => {
                    const yearTotal = getYearlyTotalReturn(year);
                    return (
                      <tr key={year} className="hover:bg-slate-800/30 transition-colors">
                        <td className="text-sm font-bold text-slate-200 py-2.5 pr-4 font-mono">{year}</td>
                        {MONTHS.map((_, mi) => {
                          const mKey = String(mi + 1);
                          const val = data.monthly_returns[year]?.[mKey];
                          return (
                            <td key={mi} className="px-1 py-1">
                              {val === undefined ? (
                                <div className="h-9 rounded-lg bg-slate-800/30 border border-slate-800/50 flex items-center justify-center text-xs text-slate-600">
                                  -
                                </div>
                              ) : (
                                <div
                                  className="h-9 rounded-lg flex items-center justify-center text-xs font-bold font-mono text-white shadow-sm border border-white/10 transition-transform hover:scale-105"
                                  style={{ backgroundColor: heatColor(val) }}
                                  title={`${MONTHS[mi]} ${year}: ${(val * 100).toFixed(2)}%`}
                                >
                                  {val > 0 ? '+' : ''}{(val * 100).toFixed(1)}%
                                </div>
                              )}
                            </td>
                          );
                        })}
                        <td className="py-2.5 pl-4 text-right">
                          <span className={`font-mono text-xs font-bold px-2 py-1 rounded-md ${
                            (yearTotal ?? 0) >= 0
                              ? 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/30'
                              : 'bg-rose-500/20 text-rose-300 border border-rose-500/30'
                          }`}>
                            {yearTotal !== null ? `${yearTotal >= 0 ? '+' : ''}${(yearTotal * 100).toFixed(1)}%` : '-'}
                          </span>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}

          {/* Underwater Curve & Constituents */}
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {/* Underwater Drawdown Chart */}
            {drawdownPoints.length > 0 && (
              <div className="lg:col-span-2 bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-sm">
                <div className="flex items-center justify-between mb-4">
                  <div className="flex items-center space-x-2">
                    <h3 className="text-lg font-bold text-white">Underwater Drawdown Curve</h3>
                    <HelpBtn onClick={() => setActiveExplainer('underwater_curve')} />
                  </div>
                  <span className="text-xs px-2.5 py-1 rounded-full bg-rose-950/40 text-rose-300 border border-rose-800/50 font-mono font-bold">
                    Peak Drop: {fmt(worstDrawdown, 2, '%')}
                  </span>
                </div>
                
                <div className="p-3 bg-slate-800/30 rounded-lg border border-slate-700/40 mb-3 flex items-center justify-between text-xs text-slate-400">
                  <span>Start: <span className="font-mono text-slate-200 ml-1">{drawdownPoints[0]?.date}</span></span>
                  <span>End: <span className="font-mono text-slate-200 ml-1">{drawdownPoints[drawdownPoints.length - 1]?.date}</span></span>
                </div>

                <div className="relative pt-2">
                  <svg viewBox="0 0 600 130" className="w-full h-32" preserveAspectRatio="none">
                    <defs>
                      <linearGradient id="drawdownGrad" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="0%" stopColor="rgba(239, 68, 68, 0.4)" />
                        <stop offset="100%" stopColor="rgba(239, 68, 68, 0.05)" />
                      </linearGradient>
                    </defs>
                    <path
                      d={`M 0 10 ${drawdownPoints
                        .map((p, i) => {
                          const x = (i / (drawdownPoints.length - 1)) * 600;
                          const depth = Math.min(1, Math.abs(p.drawdown) / Math.abs(worstDrawdown || 1));
                          const y = 10 + depth * 110;
                          return `L ${x.toFixed(1)} ${y.toFixed(1)}`;
                        })
                        .join(' ')} L 600 10 Z`}
                      fill="url(#drawdownGrad)"
                      stroke="rgba(239, 68, 68, 0.9)"
                      strokeWidth="1.8"
                    />
                  </svg>
                  <div className="flex justify-between text-[11px] text-slate-500 font-mono mt-2">
                    <span>0.0% Watermark</span>
                    <span className="text-rose-400 font-bold">{fmt(worstDrawdown, 2, '%')} Trough</span>
                  </div>
                </div>
              </div>
            )}

            {/* Portfolio Holdings Breakdown */}
            <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-sm">
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center space-x-2">
                  <h3 className="text-lg font-bold text-white">Weights Used ({Object.keys(data.holdings).length})</h3>
                  <HelpBtn onClick={() => setActiveExplainer('weights_used')} />
                </div>
                <PieChart className="w-5 h-5 text-slate-400" />
              </div>

              <div className="space-y-2.5 max-h-72 overflow-y-auto pr-1">
                {Object.entries(data.holdings)
                  .sort(([, a], [, b]) => b - a)
                  .map(([ticker, weight]) => (
                    <div key={ticker} className="flex items-center justify-between p-2 rounded-lg bg-slate-800/40 border border-slate-700/40 text-xs">
                      <span className="font-semibold text-slate-200 w-28 truncate">{ticker}</span>
                      <div className="flex items-center space-x-2">
                        <div className="w-20 bg-slate-800 rounded-full h-1.5 overflow-hidden">
                          <div
                            className="h-full bg-emerald-500 rounded-full"
                            style={{ width: `${Math.min(100, weight * 500)}%` }}
                          />
                        </div>
                        <span className="font-mono font-bold text-teal-300 w-12 text-right">
                          {(weight * 100).toFixed(1)}%
                        </span>
                      </div>
                    </div>
                  ))}
              </div>
            </div>
          </div>

          {/* Methodology Card */}
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-sm">
            <h3 className="text-base font-bold text-white mb-2">QuantStats Analytics Methodology</h3>
            <p className="text-xs text-slate-400 leading-relaxed">
              Performance metrics computed using the QuantStats institutional portfolio analytics engine over cached OHLCV adjusted closing prices. Benchmark series retrieved from National Stock Exchange NIFTY 50 (^NSEI) index. Returns compounded geometrically on daily frequency with a 2.0% risk-free rate hurdle.
            </p>
          </div>
        </>
      )}
    </div>
  );
}
