/**
 * Risk Contribution Page
 * Euler decomposition of portfolio risk per position + CVaR tail attribution
 * Educational explainer engine and institutional risk budgeting matrix
 */

'use client';

import React, { useState, useEffect } from 'react';
import { MetricCard } from '@/components/ui/MetricCard';
import { analyticsApi } from '@/lib/api';
import {
  PieChart,
  AlertTriangle,
  RefreshCw,
  Layers,
  Crosshair,
  BarChart3,
  Activity,
  Download,
  HelpCircle,
  X,
  Info,
  ShieldAlert,
  Percent,
  TrendingDown,
  Scale,
  ArrowUpRight,
  ArrowDownRight,
  CheckCircle2
} from 'lucide-react';

interface ExplainerContent {
  title: string;
  what: string;
  howInferred: string;
  whyImportant: string;
  howToInfer: string;
  benchmark?: string;
}

const EXPLAINERS: Record<string, ExplainerContent> = {
  portfolio_volatility: {
    title: 'Annualized Portfolio Volatility',
    what: 'The total annualized standard deviation of daily portfolio returns, reflecting aggregate fluctuation magnitude.',
    howInferred: 'Calculated as σ_p = √(w^T Σ w) × √252 using the full empirical covariance matrix of constituent returns.',
    whyImportant: 'The core risk denominator in Sharpe ratios and institutional risk budgeting.',
    howToInfer: '18.08% indicates standard annual fluctuation bounds of ±18.08% under normal market conditions.',
    benchmark: 'Balanced multi-cap Indian portfolio benchmark: 14.0% – 18.0%.'
  },
  var_95: {
    title: 'Daily Value at Risk (VaR 95%)',
    what: 'The minimum percentage loss expected on the 5% worst trading sessions over a 1-day holding period.',
    howInferred: 'Non-parametric empirical 5th percentile of daily portfolio historical returns: VaR_95 = Percentile(R_daily, 5%).',
    whyImportant: 'Mandated by Basel III risk regulations; establishes everyday stop-loss capital buffers.',
    howToInfer: '-1.82% means on 95 out of 100 days, daily loss will not exceed 1.82% of total portfolio value.',
    benchmark: 'Standard daily VaR limit: ≥ -2.25%.'
  },
  cvar_95: {
    title: 'Daily Conditional VaR / Expected Shortfall (CVaR 95%)',
    what: 'The average expected loss conditioned on the portfolio breaching its 95% VaR threshold.',
    howInferred: 'CVaR_95 = E[R_daily | R_daily ≤ VaR_95], measuring the conditional average of tail loss events.',
    whyImportant: 'Superior to VaR because it captures the severity of tail crashes rather than just the cutoff threshold.',
    howToInfer: '-2.53% means when a crisis or tail-shock day occurs, the average expected daily drawdown is 2.53%.',
    benchmark: 'Institutional risk ceiling: CVaR ≥ -3.50%.'
  },
  top_risk_driver: {
    title: 'Top Risk Driver Position',
    what: 'The single individual holding contributing the largest marginal share to aggregate portfolio volatility.',
    howInferred: 'Identified as argmax_i (Euler Volatility Risk Contribution %RC_i).',
    whyImportant: 'Highlights portfolio vulnerability to idiosyncratic single-stock shocks regardless of nominal portfolio value.',
    howToInfer: 'Motherson (19.9% risk share vs 13.6% capital weight) is the primary engine of portfolio volatility.',
    benchmark: 'Single-stock risk share ceiling: ≤ 20.0%.'
  },
  euler_volatility_share: {
    title: 'Euler Volatility Risk Contribution (%RC)',
    what: 'Exact mathematical decomposition showing what fraction of total portfolio volatility is driven by each asset.',
    howInferred: 'Euler Theorem: RC_i = w_i × (Σ w)_i / σ_p, normalized such that ∑ %RC_i = 100.0%.',
    whyImportant: 'A stock with a 5% capital weight can generate 15% of portfolio risk if its volatility or covariance with other holdings is high.',
    howToInfer: 'Compare Risk Share to Capital Weight: If Risk Share > Weight, the asset magnifies risk; if Risk Share < Weight, it dampens risk.'
  },
  cvar_tail_share: {
    title: 'Tail Loss Attribution (CVaR Share)',
    what: 'The percentage of extreme losses generated by each position during the portfolio\'s worst 5% crash days.',
    howInferred: 'Calculated as the mean loss of each asset on portfolio tail-shock days multiplied by asset weight, normalized to 100%.',
    whyImportant: 'Reveals "tail risk surprises" — scrips that appear calm day-to-day but collapse disproportionately during market panics.',
    howToInfer: 'If an asset\'s Tail Share is significantly higher than its Volatility Share, it has severe downside crash skewness.'
  },
  sector_risk_contribution: {
    title: 'Sector Risk Rollup',
    what: 'Aggregated percentage of total portfolio risk originating from each GICS economic sector.',
    howInferred: 'Sum of individual asset risk contributions (%RC_i) grouped by their underlying sector classification.',
    whyImportant: 'Prevents unintentional sector risk concentration (e.g. over-relying on Auto Cyclicals or Financials).',
    howToInfer: 'Consumer Cyclicals (28.4%) and ETFs (23.1%) dominate portfolio risk generation.'
  },
  divergence_insight: {
    title: 'Volatility vs Tail Loss Divergence',
    what: 'A comparative diagnostic checking whether day-to-day volatility drivers differ from crisis crash drivers.',
    howInferred: 'Evaluates Δ = %CVaR_i - %Vol_i across all assets.',
    whyImportant: 'Detects non-linear downside asymmetry and asymmetric tail correlation spikes.',
    howToInfer: 'When Volatility shares and Tail shares align closely, standard Gaussian and covariance models remain reliable during stress periods.'
  },
  risk_budgeting_ratio: {
    title: 'Risk-to-Weight Ratio (Risk Multiplier)',
    what: 'The ratio of percentage risk contribution to percentage capital allocation: Ratio = %RC_i / Weight_i.',
    howInferred: 'Calculated as %RC_i / w_i. A ratio of 1.0 represents exact proportional risk parity.',
    whyImportant: 'The key quantitative metric used by risk managers to identify over-leveraged risk contributors (> 1.0) and risk diversifiers (< 1.0).',
    howToInfer: 'Redington (1.70x) is an aggressive risk magnifier; JuniorBees (0.77x) and Cipla (0.44x) are strong risk dampeners.'
  }
};

function HelpExplainerModal({ itemKey, onClose }: { itemKey: string; onClose: () => void }) {
  const info = EXPLAINERS[itemKey];
  if (!info) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/65 backdrop-blur-sm animate-fadeIn">
      <div className="bg-slate-900 border border-slate-700 rounded-xl max-w-xl w-full p-6 shadow-2xl relative text-slate-100 max-h-[90vh] overflow-y-auto">
        <button
          onClick={onClose}
          className="absolute top-4 right-4 text-slate-400 hover:text-white p-1 rounded-lg hover:bg-slate-800 transition-colors"
          aria-label="Close explainer"
        >
          <X className="w-5 h-5" />
        </button>

        <div className="flex items-center space-x-3 mb-4">
          <div className="p-2 bg-rose-500/20 text-rose-400 rounded-lg">
            <Info className="w-6 h-6" />
          </div>
          <h3 className="text-xl font-bold text-white">{info.title}</h3>
        </div>

        <div className="space-y-4 text-sm leading-relaxed">
          <div className="bg-slate-800/80 p-3.5 rounded-lg border border-slate-700/60">
            <h4 className="text-xs font-semibold text-rose-400 uppercase tracking-wider mb-1">What This Means</h4>
            <p className="text-slate-200">{info.what}</p>
          </div>

          <div className="bg-slate-800/80 p-3.5 rounded-lg border border-slate-700/60">
            <h4 className="text-xs font-semibold text-rose-400 uppercase tracking-wider mb-1">How It Is Inferred</h4>
            <p className="text-slate-300">{info.howInferred}</p>
          </div>

          <div className="bg-slate-800/80 p-3.5 rounded-lg border border-slate-700/60">
            <h4 className="text-xs font-semibold text-rose-400 uppercase tracking-wider mb-1">Why It Is Important</h4>
            <p className="text-slate-300">{info.whyImportant}</p>
          </div>

          <div className="bg-slate-800/80 p-3.5 rounded-lg border border-slate-700/60">
            <h4 className="text-xs font-semibold text-rose-400 uppercase tracking-wider mb-1">How To Interpret</h4>
            <p className="text-slate-300">{info.howToInfer}</p>
          </div>

          {info.benchmark && (
            <div className="bg-rose-950/40 p-3 rounded-lg border border-rose-800/50 text-rose-200 text-xs font-medium">
              💡 <span className="font-semibold text-rose-300">Quantitative Benchmark:</span> {info.benchmark}
            </div>
          )}
        </div>

        <div className="mt-6 flex justify-end">
          <button
            onClick={onClose}
            className="px-4 py-2 bg-rose-600 hover:bg-rose-500 text-white rounded-lg font-medium text-sm transition-colors"
          >
            Got It
          </button>
        </div>
      </div>
    </div>
  );
}

function HelpBtn({ onClick, label }: { onClick: () => void; label?: string }) {
  return (
    <button
      onClick={(e) => {
        e.stopPropagation();
        onClick();
      }}
      className="inline-flex items-center justify-center w-4 h-4 ml-1.5 text-slate-400 hover:text-rose-400 rounded-full hover:bg-slate-800/60 transition-colors"
      title={label || 'Click to understand this metric'}
      aria-label={label || 'Explainer info'}
    >
      <HelpCircle className="w-3.5 h-3.5" />
    </button>
  );
}

interface RiskContributionData {
  window: { start: string; end: string };
  positions: {
    volatility: Record<string, number>;
    cvar_tail: Record<string, number>;
  };
  sector_rollup: {
    volatility: Record<string, number>;
    cvar: Record<string, number>;
  };
  portfolio_volatility_annualized: number;
  portfolio_var_95_daily: number;
  portfolio_cvar_95_daily: number | null;
  methodology: string;
}

function ContributionBars({
  entries,
  colorClass,
}: {
  entries: [string, number][];
  colorClass: string;
}) {
  if (entries.length === 0) {
    return (
      <p className="text-sm text-slate-400">
        Not enough tail observations to attribute this model.
      </p>
    );
  }
  const max = Math.max(...entries.map(([, v]) => v), 0.000001);
  return (
    <div className="space-y-3.5">
      {entries.map(([ticker, share]) => (
        <div key={ticker} className="flex items-center justify-between group">
          <span className="text-xs font-semibold text-slate-300 w-28 truncate font-mono">
            {ticker}
          </span>
          <div className="flex-1 mx-3">
            <div className="w-full bg-slate-800 rounded-full h-2.5 overflow-hidden border border-slate-700/50">
              <div
                className={`h-2.5 rounded-full ${colorClass} transition-all duration-500 shadow-sm`}
                style={{ width: `${(share / max) * 100}%` }}
              />
            </div>
          </div>
          <span className="text-xs font-bold font-mono text-white w-14 text-right tabular-nums">
            {(share * 100).toFixed(1)}%
          </span>
        </div>
      ))}
    </div>
  );
}

export default function RiskContributionPage() {
  const [data, setData] = useState<RiskContributionData | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [activeExplainer, setActiveExplainer] = useState<string | null>(null);
  const [selectedSectorModel, setSelectedSectorModel] = useState<'volatility' | 'cvar'>('volatility');

  const fetchRiskContribution = async () => {
    setLoading(true);
    setError(null);
    try {
      const result = await analyticsApi.getRiskContribution();
      setData(result);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load risk contribution data');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchRiskContribution();
  }, []);

  const volEntries = data
    ? (Object.entries(data.positions.volatility) as [string, number][]).sort(
        ([, a], [, b]) => b - a
      )
    : [];
  const cvarEntries = data
    ? (Object.entries(data.positions.cvar_tail) as [string, number][]).sort(
        ([, a], [, b]) => b - a
      )
    : [];
  const sectorEntries = data
    ? (Object.entries(data.sector_rollup[selectedSectorModel] || {}) as [string, number][]).sort(
        ([, a], [, b]) => b - a
      )
    : [];

  const topDriver = volEntries[0];
  const fmtPct = (v: number | null | undefined, decimals = 2) =>
    v === null || v === undefined || Number.isNaN(v)
      ? 'N/A'
      : `${(v * 100).toFixed(decimals)}%`;

  // Export CSV
  const handleExportCSV = () => {
    if (!data) return;
    const rows: string[] = [];
    rows.push('Daisy Risk Engine - Euler Risk Contribution & Tail Attribution');
    rows.push(`Analysis Window,${data.window.start} to ${data.window.end}`);
    rows.push('');
    rows.push('Portfolio Level Risk');
    rows.push(`Annualized Volatility,${fmtPct(data.portfolio_volatility_annualized)}`);
    rows.push(`Daily VaR (95%),${fmtPct(data.portfolio_var_95_daily)}`);
    rows.push(`Daily CVaR (95%),${fmtPct(data.portfolio_cvar_95_daily)}`);
    rows.push(`Top Risk Driver,${topDriver ? `${topDriver[0]} (${(topDriver[1] * 100).toFixed(1)}%)` : 'N/A'}`);
    rows.push('');
    rows.push('Position Level Risk Decomposition');
    rows.push('Ticker,Volatility Risk Share (%),CVaR Tail Loss Share (%),Risk Divergence (%)');
    for (const [ticker, volShare] of volEntries) {
      const cvarShare = data.positions.cvar_tail[ticker] ?? 0;
      const diff = cvarShare - volShare;
      rows.push(`${ticker},${(volShare * 100).toFixed(2)}%,${(cvarShare * 100).toFixed(2)}%,${(diff * 100).toFixed(2)}%`);
    }
    rows.push('');
    rows.push('Sector Risk Rollup');
    rows.push('Sector,Volatility Risk Share (%),CVaR Tail Loss Share (%)');
    const allSectors = Array.from(new Set([
      ...Object.keys(data.sector_rollup.volatility || {}),
      ...Object.keys(data.sector_rollup.cvar || {})
    ]));
    for (const sec of allSectors) {
      const vShare = data.sector_rollup.volatility[sec] ?? 0;
      const cShare = data.sector_rollup.cvar[sec] ?? 0;
      rows.push(`${sec},${(vShare * 100).toFixed(2)}%,${(cShare * 100).toFixed(2)}%`);
    }

    const csvContent = 'data:text/csv;charset=utf-8,' + rows.join('\n');
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', `risk_contribution_${new Date().toISOString().split('T')[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="space-y-6">
      {/* Active Explainer Modal */}
      {activeExplainer && (
        <HelpExplainerModal
          itemKey={activeExplainer}
          onClose={() => setActiveExplainer(null)}
        />
      )}

      {/* Hero Section */}
      <div className="bg-gradient-to-r from-rose-600 via-orange-600 to-amber-600 rounded-xl p-6 text-white shadow-lg relative overflow-hidden">
        <div className="absolute right-0 top-0 translate-x-8 -translate-y-8 w-64 h-64 bg-white/10 rounded-full blur-3xl pointer-events-none" />
        <div className="flex items-center justify-between relative z-10">
          <div>
            <div className="flex items-center space-x-3 mb-2">
              <h1 className="text-3xl font-bold tracking-tight">Risk Contribution</h1>
              <span className="px-3 py-0.5 rounded-full text-xs font-semibold bg-white/20 text-white backdrop-blur-sm">
                EULER DECOMPOSITION
              </span>
            </div>
            <p className="text-rose-100 max-w-2xl text-sm leading-relaxed">
              Identify which specific positions drive aggregate portfolio risk versus which provide diversification dampening — not just which holdings are biggest.
            </p>
            {data && (
              <div className="flex flex-wrap items-center mt-4 gap-3">
                <div className="bg-black/20 backdrop-blur-md px-3 py-1.5 rounded-lg text-rose-100 text-xs font-medium border border-white/10">
                  Window: <span className="font-bold text-white ml-1">{data.window.start} → {data.window.end}</span>
                </div>
                <div className="bg-black/20 backdrop-blur-md px-3 py-1.5 rounded-lg text-rose-100 text-xs font-medium border border-white/10">
                  Model: <span className="font-bold text-white ml-1">Euler Analytic + Tail CVaR</span>
                </div>
              </div>
            )}
          </div>
          <div className="hidden md:flex items-center space-x-3">
            <button
              onClick={handleExportCSV}
              disabled={!data || loading}
              className="flex items-center bg-white/20 hover:bg-white/30 rounded-xl px-3.5 py-2.5 text-xs font-semibold transition-colors border border-white/10 shadow-sm"
              title="Export Risk Attribution Report to CSV"
            >
              <Download className="w-4 h-4 mr-1.5 text-rose-200" />
              Export CSV
            </button>
            <button
              onClick={fetchRiskContribution}
              disabled={loading}
              className="bg-white/20 hover:bg-white/30 rounded-xl p-2.5 transition-colors border border-white/10 shadow-sm"
              title="Refresh Risk Decomposition"
            >
              <RefreshCw className={`w-5 h-5 ${loading ? 'animate-spin' : ''}`} />
            </button>
            <div className="p-3 bg-white/10 backdrop-blur-md rounded-xl border border-white/20 shadow-inner">
              <PieChart className="w-10 h-10 text-rose-200" />
            </div>
          </div>
        </div>
      </div>

      {/* Error State */}
      {error && (
        <div className="bg-rose-950/30 border border-rose-800/50 rounded-xl p-4 text-rose-200 text-sm flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <AlertTriangle className="w-5 h-5 text-rose-400 shrink-0" />
            <div>
              <h4 className="font-semibold text-rose-300">Could not decompose portfolio risk</h4>
              <p className="text-xs text-rose-400 mt-0.5">{error}</p>
            </div>
          </div>
          <button
            onClick={fetchRiskContribution}
            className="px-3 py-1.5 bg-rose-900/60 hover:bg-rose-800 rounded-lg text-xs font-semibold text-rose-100 transition-colors"
          >
            Try Again
          </button>
        </div>
      )}

      {/* Loading State */}
      {loading && !data && (
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-8 text-center space-y-3">
          <RefreshCw className="w-8 h-8 text-rose-400 animate-spin mx-auto" />
          <h3 className="text-base font-semibold text-white">Decomposing Portfolio Risk...</h3>
          <p className="text-xs text-slate-400">
            Running exact Euler marginal risk derivative equations and empirical tail expected shortfall attribution.
          </p>
        </div>
      )}

      {/* Main Content */}
      {!loading && !error && data && (
        <>
          {/* Portfolio-Level Headline Metrics */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            <div className="relative group">
              <MetricCard
                title="Portfolio Volatility (ann.)"
                value={fmtPct(data.portfolio_volatility_annualized)}
                icon={Activity}
                loading={loading}
              />
              <div className="absolute top-4 right-4 z-10">
                <HelpBtn onClick={() => setActiveExplainer('portfolio_volatility')} />
              </div>
            </div>

            <div className="relative group">
              <MetricCard
                title="Daily VaR 95%"
                value={fmtPct(data.portfolio_var_95_daily)}
                icon={Crosshair}
                loading={loading}
              />
              <div className="absolute top-4 right-4 z-10">
                <HelpBtn onClick={() => setActiveExplainer('var_95')} />
              </div>
            </div>

            <div className="relative group">
              <MetricCard
                title="Daily CVaR 95%"
                value={
                  data.portfolio_cvar_95_daily === null
                    ? 'N/A'
                    : fmtPct(data.portfolio_cvar_95_daily)
                }
                icon={Layers}
                loading={loading}
              />
              <div className="absolute top-4 right-4 z-10">
                <HelpBtn onClick={() => setActiveExplainer('cvar_95')} />
              </div>
            </div>

            <div className="relative group">
              <MetricCard
                title="Top Risk Driver"
                value={topDriver ? `${topDriver[0]} · ${(topDriver[1] * 100).toFixed(1)}%` : 'N/A'}
                icon={BarChart3}
                loading={loading}
              />
              <div className="absolute top-4 right-4 z-10">
                <HelpBtn onClick={() => setActiveExplainer('top_risk_driver')} />
              </div>
            </div>
          </div>

          {/* Position Risk Contributions (Vol vs CVaR) */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-sm">
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center space-x-2">
                  <h3 className="text-lg font-bold text-white">Share of Portfolio Volatility</h3>
                  <HelpBtn onClick={() => setActiveExplainer('euler_volatility_share')} />
                </div>
                <span className="text-xs px-2.5 py-0.5 rounded-full bg-orange-500/20 text-orange-300 border border-orange-500/30 font-mono">
                  Euler %RC
                </span>
              </div>
              <p className="text-xs text-slate-400 mb-4">Percentage contribution of each scrip to day-to-day portfolio volatility.</p>
              <ContributionBars entries={volEntries} colorClass="bg-gradient-to-r from-orange-500 to-amber-500" />
            </div>

            <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-sm">
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center space-x-2">
                  <h3 className="text-lg font-bold text-white">Share of Tail Losses (CVaR)</h3>
                  <HelpBtn onClick={() => setActiveExplainer('cvar_tail_share')} />
                </div>
                <span className="text-xs px-2.5 py-0.5 rounded-full bg-rose-500/20 text-rose-300 border border-rose-500/30 font-mono">
                  Tail Crash %
                </span>
              </div>
              <p className="text-xs text-slate-400 mb-4">Share of losses generated by each holding on the portfolio's worst 5% trading days.</p>
              <ContributionBars entries={cvarEntries} colorClass="bg-gradient-to-r from-rose-500 to-red-500" />
            </div>
          </div>

          {/* Sector Rollup with Vol / CVaR Switcher */}
          {sectorEntries.length > 0 && (
            <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-sm">
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center space-x-2">
                  <h3 className="text-lg font-bold text-white">Risk Contribution by Sector</h3>
                  <HelpBtn onClick={() => setActiveExplainer('sector_risk_contribution')} />
                </div>
                <div className="flex rounded-lg bg-slate-800 p-1 border border-slate-700">
                  <button
                    onClick={() => setSelectedSectorModel('volatility')}
                    className={`px-3 py-1 text-xs font-semibold rounded-md transition-all ${
                      selectedSectorModel === 'volatility'
                        ? 'bg-amber-500 text-slate-950 font-bold shadow-sm'
                        : 'text-slate-400 hover:text-white'
                    }`}
                  >
                    Volatility Share
                  </button>
                  <button
                    onClick={() => setSelectedSectorModel('cvar')}
                    className={`px-3 py-1 text-xs font-semibold rounded-md transition-all ${
                      selectedSectorModel === 'cvar'
                        ? 'bg-rose-500 text-white font-bold shadow-sm'
                        : 'text-slate-400 hover:text-white'
                    }`}
                  >
                    Tail Loss Share
                  </button>
                </div>
              </div>
              <ContributionBars
                entries={sectorEntries}
                colorClass={selectedSectorModel === 'volatility' ? 'bg-amber-500' : 'bg-rose-500'}
              />
            </div>
          )}

          {/* Divergence Insight */}
          {volEntries.length > 0 && cvarEntries.length > 0 && (
            <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-sm">
              <div className="flex items-center space-x-2 mb-3">
                <h3 className="text-lg font-bold text-white">Diagnostic Risk Insight</h3>
                <HelpBtn onClick={() => setActiveExplainer('divergence_insight')} />
              </div>
              {(() => {
                const tailHeavier = [...volEntries]
                  .map(([t, v]) => ({
                    ticker: t,
                    diff: (data.positions.cvar_tail[t] ?? 0) - v,
                  }))
                  .sort((a, b) => b.diff - a.diff)[0];
                if (!tailHeavier || Math.abs(tailHeavier.diff) < 0.05) {
                  return (
                    <div className="p-4 rounded-lg bg-slate-800/40 border border-slate-700/50 flex items-start space-x-3">
                      <CheckCircle2 className="w-5 h-5 text-emerald-400 shrink-0 mt-0.5" />
                      <p className="text-sm text-slate-300 leading-relaxed">
                        <span className="font-semibold text-white">Symmetric Risk Distribution:</span> Volatility shares and tail-loss shares line up closely across your holdings. Your day-to-day risk drivers are also your crisis drivers without severe non-linear crash surprises.
                      </p>
                    </div>
                  );
                }
                return (
                  <div className="p-4 rounded-lg bg-rose-950/20 border border-rose-800/40 flex items-start space-x-3">
                    <ShieldAlert className="w-5 h-5 text-rose-400 shrink-0 mt-0.5" />
                    <p className="text-sm text-slate-300 leading-relaxed">
                      On the worst crash days,{' '}
                      <span className="font-bold text-white font-mono">
                        {tailHeavier.ticker}
                      </span>{' '}
                      contributes{' '}
                      <span className="font-bold text-rose-400 font-mono">
                        +{(Math.abs(tailHeavier.diff) * 100).toFixed(1)}%
                      </span>{' '}
                      more to your tail losses than it does to everyday volatility — its downturn drawdowns are steeper than routine moves indicate.
                    </p>
                  </div>
                );
              })()}
            </div>
          )}

          {/* Methodology */}
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-sm">
            <h3 className="text-base font-bold text-white mb-2">Euler Risk Decomposition Methodology</h3>
            <p className="text-xs text-slate-400 leading-relaxed">
              Exact mathematical Euler decomposition of portfolio volatility where Marginal Risk Contribution (MRC_i = (Σ w)_i / σ_p) and Absolute Risk Contribution (RC_i = w_i × MRC_i) sum exactly to 100.0% of portfolio risk. Conditional tail attribution evaluates empirical conditional expectations on the 5% worst portfolio drawdown dates.
            </p>
          </div>
        </>
      )}
    </div>
  );
}

