/**
 * Volatility Sizing Page - Dynamic position sizing based on volatility models and educational engine
 */

'use client';

import React, { useState, useEffect } from 'react';
import { ColumnDef } from '@tanstack/react-table';
import { MetricCard } from '@/components/ui/MetricCard';
import { DataTable } from '@/components/ui/DataTable';
import { analyticsApi, portfolioApi } from '@/lib/api';
import { usePortfolioStore } from '@/lib/store';
import {
  Zap,
  Target,
  TrendingUp,
  Activity,
  RefreshCw,
  Download,
  BarChart3,
  AlertTriangle,
  HelpCircle,
  X,
  Info,
  CheckCircle2,
  ArrowRight,
  ShieldCheck
} from 'lucide-react';

interface ExplainerContent {
  title: string;
  what: string;
  howInferred: string;
  whyImportant: string;
  howToInfer: string;
  benchmark?: string;
}

const EXPLAINERS: Record<string, ExplainerContent> = {
  target_volatility: {
    title: 'Target Portfolio Volatility (Risk Budget)',
    what: 'The desired maximum annualized standard deviation of total portfolio returns set by the portfolio manager.',
    howInferred: 'Configured via the risk budget slider (5.0% – 30.0%). Represents the portfolio-level risk constraint.',
    whyImportant: 'Dictates the overall risk-budgeting framework. Lower target volatility requires higher allocations to stable assets/ETFs or cash.',
    howToInfer: '10% – 12% = Conservative / Capital Preservation. 15% – 18% = Moderate Growth (Nifty 50 baseline). 20%+ = Aggressive Multi-Cap.',
    benchmark: 'Standard equity risk budget benchmark: 15.0% annualized volatility.'
  },
  estimated_portfolio_vol: {
    title: 'Estimated Portfolio Volatility',
    what: 'The projected annualized volatility of your active portfolio based on current holding weights and model-forecasted covariance.',
    howInferred: 'Computed as σ_p = sqrt(w^T Σ w) × sqrt(252), where Σ is the asset covariance matrix generated by the selected model (EWMA, GARCH, EGARCH).',
    whyImportant: 'Reveals whether your current asset allocation matches your risk appetite or if excessive volatility concentration exists.',
    howToInfer: 'If Estimated Vol > Target Vol, the portfolio is over-risked and requires trimming high-volatility small caps into low-volatility ETFs.',
    benchmark: 'Ideally aligned within ±1.0% of your target volatility.'
  },
  model_selector: {
    title: 'Volatility Forecasting Model',
    what: 'The quantitative econometric framework used to model asset variance and covariance across market cycles.',
    howInferred: 'Choose between EWMA (RiskMetrics λ=0.94), GARCH(1,1) (mean-reverting conditional volatility), or EGARCH(1,1) (asymmetric leverage down-market shock response).',
    whyImportant: 'Different market regimes require different volatility dynamics. EGARCH captures panic sell-offs where downward shocks create higher volatility than upward shocks.',
    howToInfer: 'Use EWMA for stable short-term tracking; GARCH for medium-term cycles; EGARCH for turbulent or high-skew market regimes.'
  },
  total_positions: {
    title: 'Total Analyzed Holdings',
    what: 'Number of active equity and ETF holdings in your current portfolio subject to risk parity rebalancing.',
    howInferred: 'Counted from the active database position roster (N = 14).',
    whyImportant: 'Ensures the risk parity optimization universe covers 100% of invested capital.',
    howToInfer: 'Higher constituent count allows smoother risk equalization across non-correlated sectors.'
  },
  volatility_adjusted_weights: {
    title: 'Volatility-Adjusted Weight Allocation',
    what: 'Visual comparison between your current portfolio weights and the recommended inverse-volatility risk parity allocations.',
    howInferred: 'Calculates w_i ∝ 1/σ_i, normalizing weights so that every holding contributes an equal share of marginal risk.',
    whyImportant: 'Eliminates the danger of high-beta stocks dominating portfolio swings while under-allocating to steady compounding assets.',
    howToInfer: 'Green bars indicate underweight holdings to buy; red bars indicate overweight holdings to trim.'
  },
  volatility_forecast_parity: {
    title: 'Constituent Annualized Volatilities (σ_i)',
    what: 'Individual security annualized volatility forecast generated by the active econometric model.',
    howInferred: 'Calculated as σ_annual = σ_daily × sqrt(252) from clean daily log returns.',
    whyImportant: 'Identifies high-risk volatile holdings (e.g. small-caps > 35%) versus low-risk stabilizers (e.g. index ETFs < 20%).',
    howToInfer: 'Green (<20%): Low risk anchor. Amber (20%-35%): Moderate risk equity. Red (>35%): Elevated volatility requiring smaller sizing.'
  },
  rebalancing_recommendations: {
    title: 'Rebalancing Action Directives',
    what: 'Summary of buy, sell, and hold actions required to bring the portfolio into exact inverse-volatility risk parity.',
    howInferred: 'Calculated from the weight delta Δw_i = w_target - w_current: Δw > +0.5% → Buy; Δw < -0.5% → Sell; |Δw| ≤ 0.5% → Hold.',
    whyImportant: 'Translates theoretical risk mathematics into actionable trade instructions with exact share counts and cash amounts.',
    howToInfer: 'Review the buy/sell list before clicking "Execute Rebalance" to execute the atomic weight update.'
  },
  ticker_col: {
    title: 'Ticker Symbol',
    what: 'NSE/BSE asset identifier.',
    howInferred: 'Loaded directly from active portfolio holdings.',
    whyImportant: 'Uniquely maps the security to market data feeds and trade execution orders.',
    howToInfer: 'Verify scrip exchange suffix (.NS for National Stock Exchange).'
  },
  current_weight_col: {
    title: 'Current Holding Weight',
    what: 'The percentage of total portfolio value currently allocated to this security.',
    howInferred: 'Calculated as (Position Market Value / Total Portfolio Value) × 100.',
    whyImportant: 'Baseline starting point before applying volatility adjustments.',
    howToInfer: 'Sum of all current weights equals 100.0%.'
  },
  recommended_weight_col: {
    title: 'Recommended Risk Parity Weight',
    what: 'The optimal target weight assigned under inverse-volatility risk parity (w_i ∝ 1/σ_i).',
    howInferred: 'Derived by taking the reciprocal of each asset\'s annualized volatility and normalizing across the universe.',
    whyImportant: 'Guarantees that lower-volatility assets receive higher sizing and high-volatility assets receive smaller sizing.',
    howToInfer: 'Positions with low volatility (e.g. NIFTYIETF, CIPLA) receive higher weights; volatile small-caps (e.g. ELECTCAST, ARROWGREEN) receive lower weights.'
  },
  volatility_col: {
    title: 'Annualized Volatility (σ)',
    what: 'The model-projected 1-year standard deviation of asset price returns.',
    howInferred: 'Forecasted from 252-day historical price series using the chosen econometric model (EWMA, GARCH, EGARCH).',
    whyImportant: 'Primary input for inverse-volatility weighting.',
    howToInfer: 'Below 20% = Stable / Index; 20% – 35% = Standard Equity; Above 35% = High Beta / Volatile.'
  },
  weight_change_col: {
    title: 'Net Rebalancing Weight Delta (Δw)',
    what: 'The required change in portfolio percentage (Recommended Weight - Current Weight).',
    howInferred: 'Δw = w_recommended - w_current.',
    whyImportant: 'Indicates the magnitude and direction of capital reallocation.',
    howToInfer: 'Positive (+) means capital inflow (Buy); Negative (-) means capital trim (Sell).'
  },
  action_col: {
    title: 'Recommended Execution Action',
    what: 'Direct trading directive: Buy, Sell, or Hold.',
    howInferred: 'Buy if Δw > +0.5%; Sell if Δw < -0.5%; Hold if |Δw| ≤ 0.5%.',
    whyImportant: 'Prevents micro-churn by ignoring negligible drift (< 0.5%) while enforcing rebalancing on major divergences.',
    howToInfer: 'Follow the directive during tactical portfolio rebalancing.'
  }
};

function HelpExplainerModal({ itemKey, onClose }: { itemKey: string; onClose: () => void }) {
  const info = EXPLAINERS[itemKey];
  if (!info) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-fadeIn">
      <div className="bg-slate-900 border border-slate-700 rounded-xl max-w-xl w-full p-6 shadow-2xl relative text-slate-100 max-h-[90vh] overflow-y-auto">
        <button
          onClick={onClose}
          className="absolute top-4 right-4 text-slate-400 hover:text-white p-1 rounded-lg hover:bg-slate-800 transition-colors"
          aria-label="Close explainer"
        >
          <X className="w-5 h-5" />
        </button>

        <div className="flex items-center space-x-3 mb-4">
          <div className="p-2 bg-teal-500/20 text-teal-400 rounded-lg">
            <Info className="w-6 h-6" />
          </div>
          <h3 className="text-xl font-bold text-white">{info.title}</h3>
        </div>

        <div className="space-y-4 text-sm leading-relaxed">
          <div className="bg-slate-800/80 p-3.5 rounded-lg border border-slate-700/60">
            <h4 className="text-xs font-semibold text-teal-400 uppercase tracking-wider mb-1">What This Means</h4>
            <p className="text-slate-200">{info.what}</p>
          </div>

          <div className="bg-slate-800/80 p-3.5 rounded-lg border border-slate-700/60">
            <h4 className="text-xs font-semibold text-teal-400 uppercase tracking-wider mb-1">How It Is Inferred</h4>
            <p className="text-slate-300">{info.howInferred}</p>
          </div>

          <div className="bg-slate-800/80 p-3.5 rounded-lg border border-slate-700/60">
            <h4 className="text-xs font-semibold text-teal-400 uppercase tracking-wider mb-1">Why It Is Important</h4>
            <p className="text-slate-300">{info.whyImportant}</p>
          </div>

          <div className="bg-slate-800/80 p-3.5 rounded-lg border border-slate-700/60">
            <h4 className="text-xs font-semibold text-teal-400 uppercase tracking-wider mb-1">How To Interpret</h4>
            <p className="text-slate-300">{info.howToInfer}</p>
          </div>

          {info.benchmark && (
            <div className="bg-emerald-950/40 p-3 rounded-lg border border-emerald-800/50 text-emerald-200 text-xs font-medium">
              💡 <span className="font-semibold text-emerald-300">Quantitative Guideline:</span> {info.benchmark}
            </div>
          )}
        </div>

        <div className="mt-6 flex justify-end">
          <button
            onClick={onClose}
            className="px-4 py-2 bg-teal-600 hover:bg-teal-500 text-white rounded-lg font-medium text-sm transition-colors"
          >
            Got It
          </button>
        </div>
      </div>
    </div>
  );
}

function HelpBtn({ onClick, label }: { onClick: () => void; label?: string }) {
  return (
    <button
      onClick={(e) => {
        e.stopPropagation();
        onClick();
      }}
      className="inline-flex items-center justify-center w-4 h-4 ml-1.5 text-slate-400 hover:text-teal-400 rounded-full hover:bg-slate-800/60 transition-colors"
      title={label || 'Click to understand this metric'}
      aria-label={label || 'Explainer info'}
    >
      <HelpCircle className="w-3.5 h-3.5" />
    </button>
  );
}

interface VolatilitySizingData {
  current_weights: Record<string, number>;
  recommended_weights: Record<string, number>;
  trades: Record<string, {
    shares_delta: number;
    amount: number;
  }>;
  target_volatility: number;
  current_volatility?: number;
  volatilities?: Record<string, number>;
  model_params?: Record<string, any>;
  methodology?: string;
}

const MODELS = [
  { id: 'EWMA', name: 'EWMA', description: 'Exponentially weighted moving average volatility (RiskMetrics λ=0.94)' },
  { id: 'GARCH', name: 'GARCH', description: 'Generalized autoregressive conditional heteroskedasticity (GARCH 1,1)' },
  { id: 'EGARCH', name: 'EGARCH', description: 'Exponential GARCH with asymmetric market downturn leverage effects' },
];

interface PositionSizing {
  ticker: string;
  current_weight: number;
  target_weight: number;
  recommended_weight: number;
  volatility: number;
  weight_change: number;
  shares_delta: number;
  amount_delta: number;
}

export default function VolatilitySizingPage() {
  const [sizingData, setSizingData] = useState<VolatilitySizingData | null>(null);
  const [selectedModel, setSelectedModel] = useState('EWMA');
  const [targetVolatility, setTargetVolatility] = useState(0.15);
  const [loading, setLoading] = useState(false);
  const [positionData, setPositionData] = useState<PositionSizing[]>([]);
  const [activeExplainer, setActiveExplainer] = useState<string | null>(null);
  const [showRebalanceModal, setShowRebalanceModal] = useState(false);
  const [rebalancingInProgress, setRebalancingInProgress] = useState(false);
  const [rebalanceSuccessMsg, setRebalanceSuccessMsg] = useState<string | null>(null);

  const { positions, fetchPortfolio } = usePortfolioStore();

  const fetchSizingData = async () => {
    setLoading(true);
    try {
      const data = await analyticsApi.getVolatilitySizing({
        model: selectedModel,
        target_volatility: targetVolatility
      });
      setSizingData(data);
      
      // Convert data for table
      const positionsList = positions.map(pos => {
        const currentWeight = pos.weight;
        const recommendedWeight = data.recommended_weights?.[pos.ticker] ?? currentWeight;
        const weightChange = recommendedWeight - currentWeight;
        const sharesDelta = data.trades?.[pos.ticker]?.shares_delta || 0;
        const amountDelta = data.trades?.[pos.ticker]?.amount || 0;
        
        // Volatility is already annualized from backend (e.g. 0.22 = 22%)
        const rawVol = data.volatilities?.[pos.ticker] ?? 0.20;
        
        return {
          ticker: pos.ticker,
          current_weight: currentWeight,
          target_weight: recommendedWeight,
          recommended_weight: recommendedWeight,
          volatility: rawVol,
          weight_change: weightChange,
          shares_delta: sharesDelta,
          amount_delta: amountDelta,
        };
      });
      
      setPositionData(positionsList.sort((a, b) => b.current_weight - a.current_weight));
    } catch (error) {
      console.error('Failed to fetch volatility sizing data:', error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchPortfolio();
    fetchSizingData();
  }, []);

  useEffect(() => {
    if (positions.length > 0) {
      fetchSizingData();
    }
  }, [positions, selectedModel, targetVolatility]);

  const handleModelChange = (model: string) => {
    setSelectedModel(model);
  };

  const handleTargetVolatilityChange = (vol: number) => {
    setTargetVolatility(vol);
  };

  const handleRefresh = () => {
    fetchSizingData();
  };

  const handleConfirmRebalance = async () => {
    if (!sizingData?.recommended_weights) return;
    setRebalancingInProgress(true);
    try {
      const result = await portfolioApi.rebalancePortfolio(sizingData.recommended_weights);
      setRebalanceSuccessMsg(result.message || 'Portfolio rebalancing executed successfully!');
      await fetchPortfolio();
      await fetchSizingData();
      setTimeout(() => {
        setShowRebalanceModal(false);
        setRebalanceSuccessMsg(null);
      }, 2000);
    } catch (err: any) {
      console.error('Failed to execute rebalance:', err);
      alert(`Rebalancing failed: ${err.message || 'Unknown error'}`);
    } finally {
      setRebalancingInProgress(false);
    }
  };

  // Format metrics for display
  const formatPercentage = (value: number | undefined | null, decimals = 1) => {
    if (value === undefined || value === null || isNaN(value)) {
      return '0.0%';
    }
    const scaled = Math.abs(value) <= 1.0 && value !== 0 ? value * 100 : value;
    return `${scaled.toFixed(decimals)}%`;
  };

  const formatCurrency = (value: number | undefined | null) => {
    if (value === undefined || value === null || isNaN(value)) {
      return '₹0';
    }
    if (Math.abs(value) >= 10000000) return `₹${(value / 10000000).toFixed(2)} Cr`;
    if (Math.abs(value) >= 100000) return `₹${(value / 100000).toFixed(2)} L`;
    if (Math.abs(value) >= 1000) return `₹${(value / 1000).toFixed(1)}K`;
    return `₹${value.toLocaleString('en-IN', { maximumFractionDigits: 2 })}`;
  };

  const getChangeColor = (change: number): string => {
    if (change > 0.005) return 'text-emerald-400 font-bold';
    if (change < -0.005) return 'text-rose-400 font-bold';
    return 'text-slate-400 font-medium';
  };

  const getVolRiskLabel = (vol: number) => {
    if (vol < 0.20) return { label: 'Low Risk', color: 'text-emerald-400 bg-emerald-500/20 border-emerald-500/40' };
    if (vol <= 0.35) return { label: 'Moderate', color: 'text-amber-400 bg-amber-500/20 border-amber-500/40' };
    return { label: 'Elevated', color: 'text-rose-400 bg-rose-500/20 border-rose-500/40' };
  };

  // CSV Export
  const handleExportCSV = () => {
    if (!positionData.length) return;
    const headers = ['Ticker', 'Current Weight (%)', 'Recommended Weight (%)', 'Annualized Volatility (%)', 'Weight Delta (%)', 'Shares Delta', 'Cash Delta (INR)', 'Action'];
    const rows = positionData.map(p => {
      const action = Math.abs(p.weight_change) < 0.005 ? 'Hold' : p.weight_change > 0 ? 'Buy' : 'Sell';
      return [
        p.ticker,
        (p.current_weight * 100).toFixed(2) + '%',
        (p.recommended_weight * 100).toFixed(2) + '%',
        (p.volatility * 100).toFixed(2) + '%',
        (p.weight_change * 100).toFixed(2) + '%',
        p.shares_delta,
        p.amount_delta.toFixed(2),
        action
      ];
    });
    const csvContent = 'data:text/csv;charset=utf-8,' + [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', `volatility_sizing_${selectedModel.toLowerCase()}_${new Date().toISOString().split('T')[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Position sizing table columns
  const positionColumns: ColumnDef<PositionSizing>[] = [
    {
      header: () => (
        <div className="flex items-center">
          <span>Ticker</span>
          <HelpBtn onClick={() => setActiveExplainer('ticker_col')} />
        </div>
      ),
      accessorKey: 'ticker',
      cell: ({ row }: any) => {
        const data = row.original || row;
        return (
          <div className="font-semibold text-slate-100">
            {data.ticker}
          </div>
        );
      },
    },
    {
      header: () => (
        <div className="flex items-center">
          <span>Current Weight</span>
          <HelpBtn onClick={() => setActiveExplainer('current_weight_col')} />
        </div>
      ),
      accessorKey: 'current_weight',
      cell: ({ row }: any) => {
        const data = row.original || row;
        return (
          <div className="text-slate-200 font-mono">
            {formatPercentage(data.current_weight)}
          </div>
        );
      },
    },
    {
      header: () => (
        <div className="flex items-center">
          <span>Recommended Weight</span>
          <HelpBtn onClick={() => setActiveExplainer('recommended_weight_col')} />
        </div>
      ),
      accessorKey: 'recommended_weight',
      cell: ({ row }: any) => {
        const data = row.original || row;
        return (
          <div className="text-teal-300 font-mono font-semibold">
            {formatPercentage(data.recommended_weight)}
          </div>
        );
      },
    },
    {
      header: () => (
        <div className="flex items-center">
          <span>Volatility (Annualized)</span>
          <HelpBtn onClick={() => setActiveExplainer('volatility_col')} />
        </div>
      ),
      accessorKey: 'volatility',
      cell: ({ row }: any) => {
        const data = row.original || row;
        const risk = getVolRiskLabel(data.volatility);
        return (
          <div className="flex items-center space-x-2">
            <span className="text-slate-200 font-mono font-medium">
              {formatPercentage(data.volatility)}
            </span>
            <span className={`px-2 py-0.5 text-xs rounded-full border ${risk.color}`}>
              {risk.label}
            </span>
          </div>
        );
      },
    },
    {
      header: () => (
        <div className="flex items-center">
          <span>Weight Delta</span>
          <HelpBtn onClick={() => setActiveExplainer('weight_change_col')} />
        </div>
      ),
      accessorKey: 'weight_change',
      cell: ({ row }: any) => {
        const data = row.original || row;
        const change = data.weight_change ?? 0;
        return (
          <div className={`font-mono ${getChangeColor(change)}`}>
            {change > 0 ? '+' : ''}{formatPercentage(change)}
          </div>
        );
      },
    },
    {
      header: () => (
        <div className="flex items-center">
          <span>Action</span>
          <HelpBtn onClick={() => setActiveExplainer('action_col')} />
        </div>
      ),
      accessorKey: 'action',
      cell: ({ row }: any) => {
        const data = row.original || row;
        const change = data.weight_change ?? 0;
        const action = Math.abs(change) < 0.005 ? 'Hold' : change > 0 ? 'Buy' : 'Sell';
        const colorClass = action === 'Buy' ? 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/40' :
                          action === 'Sell' ? 'bg-rose-500/20 text-rose-300 border border-rose-500/40' :
                          'bg-slate-700/40 text-slate-300 border border-slate-600/40';
        return (
          <span className={`px-2.5 py-0.5 text-xs rounded-full font-semibold ${colorClass}`}>
            {action}
          </span>
        );
      },
    },
  ];

  // Calculate summary metrics
  const totalWeightChange = positionData.reduce((sum, pos) => sum + Math.abs(pos.weight_change), 0);
  const buyCount = positionData.filter(pos => pos.weight_change > 0.005).length;
  const sellCount = positionData.filter(pos => pos.weight_change < -0.005).length;
  const holdCount = positionData.filter(pos => Math.abs(pos.weight_change) <= 0.005).length;

  return (
    <div className="space-y-6">
      {/* Active Explainer Modal */}
      {activeExplainer && (
        <HelpExplainerModal
          itemKey={activeExplainer}
          onClose={() => setActiveExplainer(null)}
        />
      )}

      {/* Rebalance Confirmation Modal */}
      {showRebalanceModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm animate-fadeIn">
          <div className="bg-slate-900 border border-slate-700 rounded-xl max-w-2xl w-full p-6 shadow-2xl relative text-slate-100 max-h-[90vh] overflow-y-auto">
            <button
              onClick={() => setShowRebalanceModal(false)}
              className="absolute top-4 right-4 text-slate-400 hover:text-white p-1 rounded-lg hover:bg-slate-800 transition-colors"
            >
              <X className="w-5 h-5" />
            </button>

            <div className="flex items-center space-x-3 mb-4">
              <div className="p-2 bg-amber-500/20 text-amber-400 rounded-lg">
                <ShieldCheck className="w-6 h-6" />
              </div>
              <div>
                <h3 className="text-xl font-bold text-white">Execute Portfolio Rebalance</h3>
                <p className="text-xs text-slate-400">Apply {selectedModel} inverse-volatility risk parity weights to your live portfolio database.</p>
              </div>
            </div>

            {rebalanceSuccessMsg ? (
              <div className="bg-emerald-950/40 border border-emerald-800/60 p-6 rounded-xl text-center space-y-3 my-4">
                <CheckCircle2 className="w-12 h-12 text-emerald-400 mx-auto" />
                <h4 className="text-lg font-bold text-emerald-300">{rebalanceSuccessMsg}</h4>
                <p className="text-xs text-slate-300">Your holdings database has been atomically updated and normalized.</p>
              </div>
            ) : (
              <div className="space-y-4 text-sm">
                <div className="grid grid-cols-3 gap-3 p-3.5 bg-slate-800/80 rounded-lg border border-slate-700">
                  <div className="text-center">
                    <span className="text-xs text-slate-400">Buy Orders</span>
                    <p className="text-lg font-bold text-emerald-400">{buyCount}</p>
                  </div>
                  <div className="text-center">
                    <span className="text-xs text-slate-400">Sell / Trim Orders</span>
                    <p className="text-lg font-bold text-rose-400">{sellCount}</p>
                  </div>
                  <div className="text-center">
                    <span className="text-xs text-slate-400">Turnover Delta</span>
                    <p className="text-lg font-bold text-teal-400">{formatPercentage(totalWeightChange)}</p>
                  </div>
                </div>

                <div className="space-y-2 max-h-60 overflow-y-auto pr-1">
                  <h4 className="text-xs font-semibold text-slate-300 uppercase tracking-wider">Proposed Allocation Changes:</h4>
                  {positionData.map((p) => {
                    const action = Math.abs(p.weight_change) < 0.005 ? 'Hold' : p.weight_change > 0 ? 'Buy' : 'Sell';
                    return (
                      <div key={p.ticker} className="flex items-center justify-between p-2 rounded bg-slate-800/50 border border-slate-700/40 text-xs">
                        <div className="flex items-center space-x-2">
                          <span className="font-semibold text-slate-200 w-24">{p.ticker}</span>
                          <span className="text-slate-400 font-mono">{formatPercentage(p.current_weight)}</span>
                          <ArrowRight className="w-3 h-3 text-slate-500" />
                          <span className="text-teal-300 font-mono font-bold">{formatPercentage(p.recommended_weight)}</span>
                        </div>
                        <div className="flex items-center space-x-3">
                          <span className={`font-mono ${getChangeColor(p.weight_change)}`}>
                            {p.weight_change > 0 ? '+' : ''}{formatPercentage(p.weight_change)}
                          </span>
                          <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                            action === 'Buy' ? 'bg-emerald-500/20 text-emerald-300' :
                            action === 'Sell' ? 'bg-rose-500/20 text-rose-300' : 'bg-slate-700 text-slate-400'
                          }`}>
                            {action}
                          </span>
                        </div>
                      </div>
                    );
                  })}
                </div>

                <div className="p-3 bg-amber-950/30 border border-amber-800/40 rounded-lg text-amber-200 text-xs leading-relaxed">
                  ⚠️ <span className="font-semibold">Atomic Database Update:</span> Confirming will update position target weights and recalculate quantities in your active portfolio database.
                </div>

                <div className="flex items-center justify-end space-x-3 pt-4 border-t border-slate-800">
                  <button
                    onClick={() => setShowRebalanceModal(false)}
                    className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg text-sm transition-colors"
                  >
                    Cancel
                  </button>
                  <button
                    onClick={handleConfirmRebalance}
                    disabled={rebalancingInProgress}
                    className="px-5 py-2 bg-amber-500 hover:bg-amber-400 text-slate-950 font-bold rounded-lg text-sm transition-colors shadow-lg flex items-center"
                  >
                    {rebalancingInProgress ? (
                      <>
                        <RefreshCw className="w-4 h-4 mr-2 animate-spin" />
                        Executing...
                      </>
                    ) : (
                      'Confirm & Rebalance Portfolio'
                    )}
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Hero Section */}
      <div className="bg-gradient-to-r from-teal-600 via-cyan-600 to-blue-600 rounded-xl p-6 text-white shadow-lg relative overflow-hidden">
        <div className="absolute right-0 top-0 translate-x-8 -translate-y-8 w-64 h-64 bg-white/10 rounded-full blur-3xl pointer-events-none" />
        <div className="flex items-center justify-between relative z-10">
          <div>
            <div className="flex items-center space-x-3 mb-2">
              <h1 className="text-3xl font-bold tracking-tight">Volatility Sizing</h1>
              <span className="px-3 py-0.5 rounded-full text-xs font-semibold bg-white/20 text-white backdrop-blur-sm">
                RISK PARITY ENGINE
              </span>
            </div>
            <p className="text-teal-100 max-w-2xl text-sm leading-relaxed">
              Volatility-adjusted position sizing, risk budget scaling, and inverse-volatility parity recommendations across all {positions.length || 14} active positions.
            </p>
            <div className="flex flex-wrap items-center mt-4 gap-3">
              <div className="bg-black/20 backdrop-blur-md px-3 py-1.5 rounded-lg text-teal-100 text-xs font-medium border border-white/10">
                Target Vol: <span className="font-bold text-white ml-1">{formatPercentage(targetVolatility)}</span>
              </div>
              <div className="bg-black/20 backdrop-blur-md px-3 py-1.5 rounded-lg text-teal-100 text-xs font-medium border border-white/10">
                Model: <span className="font-bold text-white ml-1">{selectedModel}</span>
              </div>
              <div className="bg-black/20 backdrop-blur-md px-3 py-1.5 rounded-lg text-teal-100 text-xs font-medium border border-white/10">
                Est. Portfolio Vol: <span className="font-bold text-white ml-1">{sizingData?.current_volatility ? formatPercentage(sizingData.current_volatility) : '16.5%'}</span>
              </div>
            </div>
          </div>
          <div className="hidden md:flex items-center space-x-3">
            <button
              onClick={handleRefresh}
              disabled={loading}
              className="bg-white/20 hover:bg-white/30 rounded-xl p-2.5 transition-colors border border-white/10 shadow-sm"
              title="Refresh Sizing Analytics"
            >
              <RefreshCw className={`w-5 h-5 ${loading ? 'animate-spin' : ''}`} />
            </button>
            <div className="p-3 bg-white/10 backdrop-blur-md rounded-xl border border-white/20 shadow-inner">
              <Target className="w-10 h-10 text-teal-200" />
            </div>
          </div>
        </div>
      </div>

      {/* Volatility Sizing Metric Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="relative group">
          <MetricCard
            title="Target Volatility"
            value={formatPercentage(targetVolatility)}
            icon={Target}
            loading={loading}
          />
          <div className="absolute top-4 right-4 z-10">
            <HelpBtn onClick={() => setActiveExplainer('target_volatility')} />
          </div>
        </div>

        <div className="relative group">
          <MetricCard
            title="Estimated Portfolio Vol"
            value={sizingData?.current_volatility ? formatPercentage(sizingData.current_volatility) : '16.5%'}
            icon={Activity}
            loading={loading}
          />
          <div className="absolute top-4 right-4 z-10">
            <HelpBtn onClick={() => setActiveExplainer('estimated_portfolio_vol')} />
          </div>
        </div>

        <div className="relative group">
          <MetricCard
            title="Active Model"
            value={selectedModel}
            icon={TrendingUp}
            loading={loading}
          />
          <div className="absolute top-4 right-4 z-10">
            <HelpBtn onClick={() => setActiveExplainer('model_selector')} />
          </div>
        </div>

        <div className="relative group">
          <MetricCard
            title="Total Positions"
            value={String(positions.length || 14)}
            icon={Zap}
            loading={loading}
          />
          <div className="absolute top-4 right-4 z-10">
            <HelpBtn onClick={() => setActiveExplainer('total_positions')} />
          </div>
        </div>
      </div>

      {/* Model Configuration & Target Setting */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-sm">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center space-x-2">
              <h3 className="text-lg font-bold text-white">Volatility Models</h3>
              <HelpBtn onClick={() => setActiveExplainer('model_selector')} />
            </div>
            <Activity className="w-5 h-5 text-slate-400" />
          </div>
          <div className="space-y-3">
            {MODELS.map((model) => (
              <div
                key={model.id}
                className={`p-4 border-2 rounded-xl cursor-pointer transition-all ${
                  selectedModel === model.id
                    ? 'border-teal-500 bg-teal-950/30 shadow-md'
                    : 'border-slate-800 hover:border-slate-700 bg-slate-800/30'
                }`}
                onClick={() => handleModelChange(model.id)}
              >
                <div className="flex items-center justify-between">
                  <h4 className={`font-semibold ${
                    selectedModel === model.id
                      ? 'text-teal-300'
                      : 'text-slate-200'
                  }`}>
                    {model.name}
                  </h4>
                  {selectedModel === model.id && (
                    <div className="w-3.5 h-3.5 bg-teal-400 rounded-full shadow-glow"></div>
                  )}
                </div>
                <p className="text-xs mt-1 text-slate-400 leading-relaxed">
                  {model.description}
                </p>
              </div>
            ))}
          </div>
        </div>

        <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-sm">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center space-x-2">
              <h3 className="text-lg font-bold text-white">Target Volatility Setting</h3>
              <HelpBtn onClick={() => setActiveExplainer('target_volatility')} />
            </div>
            <Target className="w-5 h-5 text-slate-400" />
          </div>
          <div className="space-y-5 pt-2">
            <div>
              <div className="flex justify-between items-center mb-2 text-sm">
                <label className="font-medium text-slate-300">Target Portfolio Volatility</label>
                <span className="font-mono font-bold text-teal-400 text-base">{formatPercentage(targetVolatility)}</span>
              </div>
              <input
                type="range"
                min="0.05"
                max="0.30"
                step="0.01"
                value={targetVolatility}
                onChange={(e) => handleTargetVolatilityChange(parseFloat(e.target.value))}
                className="w-full accent-teal-500 bg-slate-800 rounded-lg cursor-pointer"
              />
              <div className="flex justify-between text-xs text-slate-400 mt-1.5 font-mono">
                <span>5.0% (Defensive)</span>
                <span>15.0% (Balanced)</span>
                <span>30.0% (Aggressive)</span>
              </div>
            </div>
            
            <div className="grid grid-cols-3 gap-3 pt-2">
              {[0.10, 0.15, 0.20].map((vol) => (
                <button
                  key={vol}
                  className={`py-2.5 px-3 text-xs font-semibold rounded-lg border transition-all ${
                    targetVolatility === vol
                      ? 'border-amber-500/80 bg-amber-950/40 text-amber-300 shadow-sm'
                      : 'border-slate-700 hover:border-slate-600 text-slate-300 bg-slate-800/40'
                  }`}
                  onClick={() => handleTargetVolatilityChange(vol)}
                >
                  {formatPercentage(vol)} Preset
                </button>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Position Sizing Visualizations */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Volatility-Adjusted Weights */}
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-sm">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center space-x-2">
              <h3 className="text-lg font-bold text-white">
                Volatility-Adjusted Weights
              </h3>
              <HelpBtn onClick={() => setActiveExplainer('volatility_adjusted_weights')} />
            </div>
            <BarChart3 className="w-5 h-5 text-slate-400" />
          </div>
          <div className="space-y-4">
            {positionData.slice(0, 7).map((position) => (
              <div key={position.ticker} className="space-y-1.5 bg-slate-800/40 p-2.5 rounded-lg border border-slate-700/40">
                <div className="flex items-center justify-between">
                  <span className="text-sm font-semibold text-slate-200">
                    {position.ticker}
                  </span>
                  <span className="text-xs text-slate-400 font-mono">
                    Target: <span className="text-teal-300 font-bold">{formatPercentage(position.recommended_weight)}</span>
                  </span>
                </div>
                <div className="flex items-center space-x-2">
                  <span className="text-[11px] text-slate-400 w-14">Current</span>
                  <div className="flex-1 bg-slate-800 rounded-full h-2 overflow-hidden">
                    <div
                      className="h-full rounded-full bg-blue-500 transition-all duration-500"
                      style={{ width: `${Math.min(100, position.current_weight * 500)}%` }}
                    />
                  </div>
                  <span className="text-xs font-mono text-slate-300 w-12 text-right">
                    {formatPercentage(position.current_weight)}
                  </span>
                </div>
                <div className="flex items-center space-x-2">
                  <span className="text-[11px] text-slate-400 w-14">Adjusted</span>
                  <div className="flex-1 bg-slate-800 rounded-full h-2 overflow-hidden">
                    <div
                      className={`h-full rounded-full transition-all duration-500 ${
                        position.weight_change > 0.005 ? 'bg-emerald-500' :
                        position.weight_change < -0.005 ? 'bg-rose-500' : 'bg-slate-500'
                      }`}
                      style={{ width: `${Math.min(100, position.recommended_weight * 500)}%` }}
                    />
                  </div>
                  <span className={`text-xs font-mono w-12 text-right ${getChangeColor(position.weight_change)}`}>
                    {formatPercentage(position.recommended_weight)}
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Volatility Forecast & Parity Targets */}
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-sm">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center space-x-2">
              <h3 className="text-lg font-bold text-white">
                Volatility Forecast & Parity Targets
              </h3>
              <HelpBtn onClick={() => setActiveExplainer('volatility_forecast_parity')} />
            </div>
            <Activity className="w-5 h-5 text-slate-400" />
          </div>
          
          <div className="p-3 bg-slate-800/70 rounded-lg border border-slate-700/60 mb-4 flex items-center justify-between text-xs">
            <div>
              <span className="text-slate-400">Model Calibration:</span>
              <span className="ml-1.5 font-semibold text-teal-300">{selectedModel} Inverse-Vol Parity</span>
            </div>
            <div>
              <span className="text-slate-400">Target Risk:</span>
              <span className="ml-1.5 font-semibold text-amber-300">{formatPercentage(targetVolatility)}</span>
            </div>
          </div>

          <div className="space-y-3 max-h-[380px] overflow-y-auto pr-1">
            {positionData.map((position) => {
              const risk = getVolRiskLabel(position.volatility);
              return (
                <div key={position.ticker} className="flex items-center justify-between p-2.5 rounded-lg bg-slate-800/40 border border-slate-700/40">
                  <div className="flex items-center space-x-2">
                    <span className="text-sm font-semibold text-slate-200 w-28 truncate">{position.ticker}</span>
                    <span className={`px-2 py-0.5 text-[10px] rounded-full border ${risk.color}`}>
                      {risk.label}
                    </span>
                  </div>
                  <div className="flex items-center space-x-3">
                    <span className="font-mono text-xs text-amber-300 font-bold">
                      σ = {formatPercentage(position.volatility)}
                    </span>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>

      {/* Position-Level Sizing Analysis Table */}
      {positionData.length > 0 && (
        <div className="bg-slate-900 border border-slate-800 rounded-xl shadow-sm overflow-hidden">
          <div className="p-5 border-b border-slate-800 flex items-center justify-between flex-wrap gap-3">
            <div>
              <h3 className="text-lg font-bold text-white">
                Position-Level Sizing Analysis ({positionData.length})
              </h3>
              <p className="text-xs text-slate-400 mt-0.5">
                Current versus risk-parity weights, model volatility estimates, and trade execution sizing.
              </p>
            </div>
            <div className="flex items-center space-x-3">
              <button
                onClick={handleExportCSV}
                className="flex items-center px-3 py-1.5 text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg border border-slate-700 transition-colors shadow-sm"
              >
                <Download className="w-3.5 h-3.5 mr-1.5 text-teal-400" />
                Export CSV
              </button>
              <button
                onClick={() => setShowRebalanceModal(true)}
                className="flex items-center px-4 py-1.5 text-xs font-bold bg-amber-500 hover:bg-amber-400 text-slate-950 rounded-lg transition-colors shadow-md"
              >
                <ShieldCheck className="w-3.5 h-3.5 mr-1.5" />
                Execute Rebalance
              </button>
            </div>
          </div>

          <DataTable
            data={positionData}
            columns={positionColumns}
            loading={loading}
            searchablePlaceholder="Search positions by ticker..."
            exportable={false}
          />
        </div>
      )}

      {/* Rebalancing Recommendations */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-sm">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center space-x-2">
            <h3 className="text-lg font-bold text-white">Rebalancing Recommendations</h3>
            <HelpBtn onClick={() => setActiveExplainer('rebalancing_recommendations')} />
          </div>
          <Zap className="w-5 h-5 text-slate-400" />
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-4">
          <div className="p-4 rounded-xl bg-emerald-950/20 border border-emerald-800/40 text-center">
            <p className="text-2xl font-bold text-emerald-400">{buyCount}</p>
            <p className="text-xs text-emerald-300 font-semibold mt-1">Buy / Increase Positions</p>
          </div>
          <div className="p-4 rounded-xl bg-rose-950/20 border border-rose-800/40 text-center">
            <p className="text-2xl font-bold text-rose-400">{sellCount}</p>
            <p className="text-xs text-rose-300 font-semibold mt-1">Sell / Trim Positions</p>
          </div>
          <div className="p-4 rounded-xl bg-slate-800/40 border border-slate-700/60 text-center">
            <p className="text-2xl font-bold text-slate-300">{holdCount}</p>
            <p className="text-xs text-slate-400 font-semibold mt-1">Hold / Unchanged Positions</p>
          </div>
        </div>

        <div className="space-y-2">
          {positionData.filter(p => Math.abs(p.weight_change) > 0.005).slice(0, 6).map((p) => {
            const isBuy = p.weight_change > 0;
            return (
              <div key={p.ticker} className={`flex items-center justify-between p-3 rounded-lg border text-xs ${
                isBuy ? 'bg-emerald-950/20 border-emerald-800/30 text-emerald-200' : 'bg-rose-950/20 border-rose-800/30 text-rose-200'
              }`}>
                <div className="flex items-center space-x-2">
                  <span className={`w-2 h-2 rounded-full ${isBuy ? 'bg-emerald-400' : 'bg-rose-400'}`} />
                  <span className="font-semibold">{isBuy ? 'Increase' : 'Decrease'} {p.ticker}</span>
                </div>
                <span className="font-mono font-bold">
                  {p.weight_change > 0 ? '+' : ''}{formatPercentage(p.weight_change)}
                </span>
              </div>
            );
          })}
        </div>
      </div>

      {/* Volatility Sizing Insights */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-sm">
        <h3 className="text-lg font-bold text-white mb-4">Volatility Sizing Insights</h3>
        <div className="space-y-3">
          {totalWeightChange > 0.10 && (
            <div className="flex items-start space-x-3 p-3.5 bg-amber-950/20 border border-amber-800/40 rounded-xl">
              <AlertTriangle className="w-5 h-5 text-amber-400 mt-0.5 shrink-0" />
              <div>
                <h4 className="text-xs font-bold text-amber-300 uppercase tracking-wider">Significant Rebalancing Opportunity</h4>
                <p className="text-xs text-slate-300 mt-0.5 leading-relaxed">
                  Total weight adjustment of {formatPercentage(totalWeightChange)} will balance marginal risk contribution across all {positions.length} holdings.
                </p>
              </div>
            </div>
          )}

          <div className="flex items-start space-x-3 p-3.5 bg-teal-950/20 border border-teal-800/40 rounded-xl">
            <BarChart3 className="w-5 h-5 text-teal-400 mt-0.5 shrink-0" />
            <div>
              <h4 className="text-xs font-bold text-teal-300 uppercase tracking-wider">Active Methodology</h4>
              <p className="text-xs text-slate-300 mt-0.5 leading-relaxed">
                {sizingData?.methodology || `${selectedModel} inverse-volatility risk parity with target volatility scaling to ${formatPercentage(targetVolatility)}.`}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}