/**
 * Volatility Sizing Page - Dynamic position sizing based on volatility models and educational engine
 */

'use client';

import React, { useState, useEffect, useRef, useMemo } from 'react';
import { DataTable, type DataTableColumn } from '@/components/ui/DataTable';
import { MetricCard } from '@/components/ui/MetricCard';
import {
  SectionProvenance,
  sectionCoverage,
} from '@/components/provenance/SectionProvenance';
import { analyticsApi, portfolioApi } from '@/lib/api';
import { usePortfolioStore } from '@/lib/store';
import { escapeCsvCell, formatCurrency as formatAmount } from '@/lib/utils';
import type {
  VolatilitySizingResponse,
  VolSizingExecutionBlock,
  VolSizingTrade,
  VolSizingTradeStatus,
} from '@/types';
import {
  Zap,
  Target,
  TrendingUp,
  Activity,
  RefreshCw,
  Download,
  BarChart3,
  AlertTriangle,
  HelpCircle,
  X,
  Info,
  CheckCircle2,
  ArrowRight,
  ShieldCheck,
  Lock
} from 'lucide-react';

interface ExplainerContent {
  title: string;
  what: string;
  howInferred: string;
  whyImportant: string;
  howToInfer: string;
  benchmark?: string;
}

const EXPLAINERS: Record<string, ExplainerContent> = {
  target_volatility: {
    title: 'Target Portfolio Volatility (Risk Budget)',
    what: 'The desired maximum annualized standard deviation of total portfolio returns set by the portfolio manager.',
    howInferred: 'Configured via the risk budget slider (5.0% – 30.0%). Represents the portfolio-level risk constraint.',
    whyImportant: 'Dictates the overall risk-budgeting framework. Lower target volatility requires higher allocations to stable assets/ETFs or cash.',
    howToInfer: '10% – 12% = Conservative / Capital Preservation. 15% – 18% = Moderate Growth (Nifty 50 baseline). 20%+ = Aggressive Multi-Cap.',
    benchmark: 'Standard equity risk budget benchmark: 15.0% annualized volatility.'
  },
  estimated_portfolio_vol: {
    title: 'Estimated Portfolio Volatility',
    what: 'The projected annualized volatility of your active portfolio based on current holding weights and model-forecasted covariance.',
    howInferred: 'Computed as σ_p = sqrt(w^T Σ w) × sqrt(252), where Σ is the asset covariance matrix generated by the selected model (EWMA, GARCH, EGARCH).',
    whyImportant: 'Reveals whether your current asset allocation matches your risk appetite or if excessive volatility concentration exists.',
    howToInfer: 'If Estimated Vol > Target Vol, the portfolio is over-risked and requires trimming high-volatility small caps into low-volatility ETFs.',
    benchmark: 'Ideally aligned within ±1.0% of your target volatility.'
  },
  model_selector: {
    title: 'Volatility Forecasting Model',
    what: 'The quantitative econometric framework used to model asset variance and covariance across market cycles.',
    howInferred: 'Choose between EWMA (RiskMetrics λ=0.94), GARCH(1,1) (mean-reverting conditional volatility), or EGARCH(1,1) (asymmetric leverage down-market shock response).',
    whyImportant: 'Different market regimes require different volatility dynamics. EGARCH captures panic sell-offs where downward shocks create higher volatility than upward shocks.',
    howToInfer: 'Use EWMA for stable short-term tracking; GARCH for medium-term cycles; EGARCH for turbulent or high-skew market regimes.'
  },
  total_positions: {
    title: 'Total Analyzed Holdings',
    what: 'Number of active equity and ETF holdings in your current portfolio subject to risk parity rebalancing.',
    howInferred: 'Counted from the active database position roster.',
    whyImportant: 'Ensures the risk parity optimization universe covers 100% of invested capital.',
    howToInfer: 'Higher constituent count allows smoother risk equalization across non-correlated sectors.'
  },
  volatility_adjusted_weights: {
    title: 'Volatility-Adjusted Weight Allocation',
    what: 'Visual comparison between your current portfolio weights and the recommended inverse-volatility risk parity allocations.',
    howInferred: 'Calculates w_i ∝ 1/σ_i, normalizing weights so that every holding contributes an equal share of marginal risk.',
    whyImportant: 'Eliminates the danger of high-beta stocks dominating portfolio swings while under-allocating to steady compounding assets.',
    howToInfer: 'Green bars indicate underweight holdings to buy; red bars indicate overweight holdings to trim.'
  },
  volatility_forecast_parity: {
    title: 'Constituent Annualized Volatilities (σ_i)',
    what: 'Individual security annualized volatility forecast generated by the active econometric model.',
    howInferred: 'Calculated as σ_annual = σ_daily × sqrt(252) from clean daily log returns.',
    whyImportant: 'Identifies high-risk volatile holdings (e.g. small-caps > 35%) versus low-risk stabilizers (e.g. index ETFs < 20%).',
    howToInfer: 'Green (<20%): Low risk anchor. Amber (20%-35%): Moderate risk equity. Red (>35%): Elevated volatility requiring smaller sizing.'
  },
  rebalancing_recommendations: {
    title: 'Rebalancing Action Directives',
    what: 'Summary of buy, sell, and hold actions required to bring the portfolio into exact inverse-volatility risk parity.',
    howInferred: 'Calculated from the weight delta Δw_i = w_target - w_current: Δw > +0.5% → Buy; Δw < -0.5% → Sell; |Δw| ≤ 0.5% → Hold.',
    whyImportant: 'Translates theoretical risk mathematics into actionable trade instructions with exact share counts and cash amounts.',
    howToInfer: 'Review the buy/sell list before clicking "Execute Rebalance" to execute the atomic weight update.'
  },
  ticker_col: {
    title: 'Ticker Symbol',
    what: 'NSE/BSE asset identifier.',
    howInferred: 'Loaded directly from active portfolio holdings.',
    whyImportant: 'Uniquely maps the security to market data feeds and trade execution orders.',
    howToInfer: 'Verify scrip exchange suffix (.NS for National Stock Exchange).'
  },
  current_weight_col: {
    title: 'Current Holding Weight',
    what: 'The percentage of total portfolio value currently allocated to this security.',
    howInferred: 'Calculated as (Position Market Value / Total Portfolio Value) × 100.',
    whyImportant: 'Baseline starting point before applying volatility adjustments.',
    howToInfer: 'Sum of all current weights equals 100.0%.'
  },
  recommended_weight_col: {
    title: 'Recommended Risk Parity Weight',
    what: 'The optimal target weight assigned under inverse-volatility risk parity (w_i ∝ 1/σ_i).',
    howInferred: 'Derived by taking the reciprocal of each asset\'s annualized volatility and normalizing across the universe.',
    whyImportant: 'Guarantees that lower-volatility assets receive higher sizing and high-volatility assets receive smaller sizing.',
    howToInfer: 'Positions with low volatility (e.g. NIFTYIETF, CIPLA) receive higher weights; volatile small-caps (e.g. ELECTCAST, ARROWGREEN) receive lower weights.'
  },
  volatility_col: {
    title: 'Annualized Volatility (σ)',
    what: 'The model-projected 1-year standard deviation of asset price returns.',
    howInferred: 'Forecasted from 252-day historical price series using the chosen econometric model (EWMA, GARCH, EGARCH).',
    whyImportant: 'Primary input for inverse-volatility weighting.',
    howToInfer: 'Below 20% = Stable / Index; 20% – 35% = Standard Equity; Above 35% = High Beta / Volatile.'
  },
  weight_change_col: {
    title: 'Net Rebalancing Weight Delta (Δw)',
    what: 'The required change in portfolio percentage (Recommended Weight - Current Weight).',
    howInferred: 'Δw = w_recommended - w_current.',
    whyImportant: 'Indicates the magnitude and direction of capital reallocation.',
    howToInfer: 'Positive (+) means capital inflow (Buy); Negative (-) means capital trim (Sell).'
  },
  action_col: {
    title: 'Recommended Execution Action',
    what: 'Direct trading directive: Buy, Sell, or Hold.',
    howInferred: 'Buy if Δw > +0.5%; Sell if Δw < -0.5%; Hold if |Δw| ≤ 0.5%.',
    whyImportant: 'Prevents micro-churn by ignoring negligible drift (< 0.5%) while enforcing rebalancing on major divergences.',
    howToInfer: 'Follow the directive during tactical portfolio rebalancing.'
  },
  notional_col: {
    title: 'Trade Notional',
    what: 'The rupee amount the weight delta implies for this leg: Δw × portfolio value.',
    howInferred: 'Reported by the engine alongside the sizing price it was measured against, so amount and share count reconcile exactly.',
    whyImportant: 'A notional is the money actually at stake; a share count is only a rounding of it.',
    howToInfer: 'N/A means no notional was computable (no portfolio value) — it is never a zero.'
  },
  shares_delta_col: {
    title: 'Whole-Share Delta',
    what: 'The integer share count the notional buys or sells, rounded half away from zero.',
    howInferred: 'shares_delta = half_up(notional ÷ sizing_price), where the sizing price is one aligned snapshot date shared by every leg.',
    whyImportant: 'A material notional that rounds to zero shares is reported as below minimum lot, not silently as zero.',
    howToInfer: 'N/A means no whole-share instruction exists (no sizing price); a below-minimum-lot leg shows its notional instead.'
  },
  trade_status_col: {
    title: 'Instruction Status',
    what: 'Whether the leg has an expressible order: executable, below minimum lot, immaterial, no trade required, or not executable.',
    howInferred: 'Published by the engine per leg with the reason attached (e.g. sizing_price_unavailable).',
    whyImportant: 'It separates "do not trade" from "cannot trade", which a 0-share cell cannot.',
    howToInfer: 'Hover any status for its reason. "No sizing instruction" means the leg left the sizing universe.'
  }
};

function HelpExplainerModal({
  itemKey,
  onClose,
  positionCount,
}: {
  itemKey: string;
  onClose: () => void;
  positionCount?: number;
}) {
  const info = EXPLAINERS[itemKey];

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [onClose]);

  if (!info) return null;

  const howInferred =
    itemKey === 'total_positions'
      ? `Counted from the active database position roster (N = ${positionCount ?? 0}).`
      : info.howInferred;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-fadeIn"
      onClick={onClose}
    >
      <div
        role="dialog"
        aria-modal="true"
        aria-label={info.title}
        className="bg-slate-900 border border-slate-700 rounded-xl max-w-xl w-full p-6 shadow-2xl relative text-slate-100 max-h-[90vh] overflow-y-auto"
        onClick={(e) => e.stopPropagation()}
      >
        <button
          onClick={onClose}
          className="absolute top-4 right-4 text-slate-400 hover:text-white p-1 rounded-lg hover:bg-slate-800 transition-colors"
          aria-label="Close explainer"
        >
          <X className="w-5 h-5" />
        </button>

        <div className="flex items-center space-x-3 mb-4">
          <div className="p-2 bg-teal-500/20 text-teal-400 rounded-lg">
            <Info className="w-6 h-6" />
          </div>
          <h3 className="text-xl font-bold text-white">{info.title}</h3>
        </div>

        <div className="space-y-4 text-sm leading-relaxed">
          <div className="bg-slate-800/80 p-3.5 rounded-lg border border-slate-700/60">
            <h4 className="text-xs font-semibold text-teal-400 uppercase tracking-wider mb-1">What This Means</h4>
            <p className="text-slate-200">{info.what}</p>
          </div>

          <div
            className="bg-slate-800/80 p-3.5 rounded-lg border border-slate-700/60"
          >
            <h4 className="text-xs font-semibold text-teal-400 uppercase tracking-wider mb-1">How It Is Inferred</h4>
            <p className="text-slate-300">{howInferred}</p>
          </div>

          <div className="bg-slate-800/80 p-3.5 rounded-lg border border-slate-700/60">
            <h4 className="text-xs font-semibold text-teal-400 uppercase tracking-wider mb-1">Why It Is Important</h4>
            <p className="text-slate-300">{info.whyImportant}</p>
          </div>

          <div className="bg-slate-800/80 p-3.5 rounded-lg border border-slate-700/60">
            <h4 className="text-xs font-semibold text-teal-400 uppercase tracking-wider mb-1">How To Interpret</h4>
            <p className="text-slate-300">{info.howToInfer}</p>
          </div>

          {info.benchmark && (
            <div className="bg-emerald-950/40 p-3 rounded-lg border border-emerald-800/50 text-emerald-200 text-xs font-medium">
              💡 <span className="font-semibold text-emerald-300">Quantitative Guideline:</span> {info.benchmark}
            </div>
          )}
        </div>

        <div className="mt-6 flex justify-end">
          <button
            onClick={onClose}
            className="px-4 py-2 bg-teal-600 hover:bg-teal-500 text-white rounded-lg font-medium text-sm transition-colors"
          >
            Got It
          </button>
        </div>
      </div>
    </div>
  );
}

function HelpBtn({ onClick, label }: { onClick: () => void; label?: string }) {
  return (
    <button
      onClick={(e) => {
        e.stopPropagation();
        onClick();
      }}
      className="inline-flex items-center justify-center w-4 h-4 ml-1.5 text-slate-400 hover:text-teal-400 rounded-full hover:bg-slate-800/60 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-400"
      title={label || 'Click to understand this metric'}
      aria-label={label || 'Explainer info'}
    >
      <HelpCircle className="w-3.5 h-3.5" />
    </button>
  );
}

/**
 * Freshness fields the route publishes that `@/types` does not model — it is
 * owned by another workstream. `price_freshness` is the one that matters here:
 * the route states plainly that `sizing_price_as_of` (not the section date) is
 * the freshness of the executable trade list, so the provenance line is bound to
 * it rather than to a date that does not describe the share counts.
 */
interface VolSizingPriceFreshness {
  sizing_price_as_of: string | null;
  latest_delivered_observation: string | null;
  sizing_price_calendar_days_behind: number | null;
  sizing_price_as_of_status: 'measured' | 'unavailable';
  rule: string;
}

interface VolatilitySizingData extends VolatilitySizingResponse {
  model_params?: Record<string, any>;
  /** Newest delivered observation the sizing window was measured on. */
  latest_observation_date?: string | null;
  warnings?: string[] | null;
  sizing_basis?: VolatilitySizingResponse['sizing_basis'] & {
    missing_tickers?: string[] | null;
    price_freshness?: VolSizingPriceFreshness | null;
  };
}

const MODELS = [
  { id: 'EWMA', name: 'EWMA', description: 'Exponentially weighted moving average volatility (RiskMetrics λ=0.94)' },
  { id: 'GARCH', name: 'GARCH', description: 'Generalized autoregressive conditional heteroskedasticity (GARCH 1,1)' },
  { id: 'EGARCH', name: 'EGARCH', description: 'Exponential GARCH with asymmetric market downturn leverage effects' },
];

/** One value an absent measurement must never borrow from: `null` is N/A. */
const NOT_AVAILABLE = 'N/A';

/**
 * Mirrors `GROSS_EXPOSURE_TOLERANCE` in `backend/app/utils/allocations.py`.
 * A target is financed only above this distance from 1.0.
 */
const GROSS_EXPOSURE_TOLERANCE = 1e-6;

function finiteOrNull(value: unknown): number | null {
  return typeof value === 'number' && Number.isFinite(value) ? value : null;
}

/** Weight / exposure as a percentage of NAV. `null` renders N/A, never 0%. */
function formatWeight(value: number | null | undefined, decimals = 2): string {
  const numeric = finiteOrNull(value);
  return numeric === null ? NOT_AVAILABLE : `${(numeric * 100).toFixed(decimals)}%`;
}

function formatShares(value: number | null | undefined): string {
  const numeric = finiteOrNull(value);
  return numeric === null ? NOT_AVAILABLE : `${numeric > 0 ? '+' : ''}${numeric}`;
}

// ---------------------------------------------------------------------------
// execution eligibility
// ---------------------------------------------------------------------------
type FinancingView = {
  /** Borrowed fraction of NAV (`gross - 1`). */
  weight: number | null;
  /** Quantified borrowing. `null` when no portfolio value made it computable. */
  amount: number | null;
  currency: string | null;
};

type ExecutionView = {
  /** `reported` = the engine's own block; `derived` = computed from weights. */
  source: 'reported' | 'derived';
  rule: string | null;
  mode: string | null;
  grossExposure: number | null;
  netCashWeight: number | null;
  financing: FinancingView;
  financingRequired: boolean;
  eligible: boolean;
  blockReason: string | null;
};

function financingView(raw: unknown, currency: string | null): FinancingView {
  const numeric = finiteOrNull(raw);
  if (numeric !== null) return { weight: null, amount: numeric, currency };
  if (raw && typeof raw === 'object') {
    const block = raw as { weight?: unknown; amount?: unknown; currency?: unknown };
    return {
      weight: finiteOrNull(block.weight),
      amount: finiteOrNull(block.amount),
      currency: typeof block.currency === 'string' ? block.currency : currency,
    };
  }
  return { weight: null, amount: null, currency };
}

function grossExposureOf(weights: Record<string, number> | undefined): number {
  return Object.values(weights ?? {}).reduce((sum, weight) => {
    const numeric = finiteOrNull(weight);
    return numeric === null ? sum : sum + Math.abs(numeric);
  }, 0);
}

/**
 * Borrowed fraction of NAV. The engine publishes `net_cash_weight` (its
 * negative), so `gross - 1` is a restatement of a reported number, not a new
 * measurement; it is only used when the block omits an explicit weight.
 */
function financingWeightOf(execution: ExecutionView): number | null {
  if (execution.financing.weight !== null) return execution.financing.weight;
  const gross = finiteOrNull(execution.grossExposure);
  return gross === null ? null : gross - 1;
}

/**
 * One gate for both rebalance buttons: may these weights be applied as a plain
 * rebalance? The engine answers it in `execution`; a pre-contract payload is
 * measured with the SAME published rule so a leveraged target can never slip
 * into the rebalance call. Only the borrowed *weight* is derived there — a rupee
 * amount stays N/A because no backend figure exists to quote.
 */
function resolveExecution(data: VolatilitySizingData | null | undefined): ExecutionView | null {
  if (!data) return null;
  const reported = data.execution as VolSizingExecutionBlock | undefined;
  if (reported) {
    return {
      source: 'reported',
      rule: reported.normalization_rule ?? null,
      mode: reported.normalization_mode ?? null,
      grossExposure: finiteOrNull(reported.gross_exposure),
      netCashWeight: finiteOrNull(reported.net_cash_weight),
      financing: financingView(
        reported.financing_requirement,
        reported.financing_requirement_currency ?? data.sizing_price_currency ?? data.currency ?? null
      ),
      financingRequired: reported.financing_required === true,
      eligible: reported.execution_eligible === true,
      blockReason: reported.block_reason ?? null,
    };
  }

  const tickers = Object.keys(data.recommended_weights ?? {});
  if (tickers.length === 0) return null;
  const gross = grossExposureOf(data.recommended_weights);
  const financed = gross > 1 + GROSS_EXPOSURE_TOLERANCE;
  return {
    source: 'derived',
    rule: null,
    mode: null,
    grossExposure: gross,
    netCashWeight: 1 - gross,
    financing: { weight: financed ? gross - 1 : null, amount: null, currency: null },
    financingRequired: financed,
    eligible: !financed,
    blockReason: financed
      ? `Gross exposure ${gross.toFixed(6)} exceeds 1.0; the target borrows ${(gross - 1).toFixed(6)} of the portfolio value and is not a normal rebalance`
      : null,
  };
}

/** Why the target cannot be pushed as a normal rebalance, in plain words. */
function executionBlockText(
  execution: ExecutionView | null,
  hasTarget: boolean,
  unavailableReason: string | null
): string | null {
  if (unavailableReason) {
    return `The sizing result is unavailable, so it is not an executable target: ${unavailableReason}`;
  }
  if (!hasTarget) {
    return 'No rebalance target is available, so there is nothing to execute.';
  }
  if (!execution) return null;
  if (execution.eligible) return null;
  if (!execution.financingRequired) {
    return execution.blockReason || 'This target cannot be applied as a normal rebalance.';
  }
  const currency = execution.financing.currency;
  const borrowing =
    execution.financing.amount !== null
      ? `Target requires ${formatAmount(execution.financing.amount, currency ?? 'INR')} of financing`
      : execution.financing.weight !== null
        ? `Target requires ${formatWeight(execution.financing.weight)} financing (amount not quantified: no portfolio value)`
        : 'Target requires financing';
  const rule = execution.rule
    ? ` Normalization rule '${execution.rule}' does not create financing.`
    : '';
  const reason = execution.blockReason ? ` ${execution.blockReason}.` : '';
  return `${borrowing}; a normal rebalance cannot express gross > 100%.${rule}${reason}`;
}

// ---------------------------------------------------------------------------
// per-leg rows
// ---------------------------------------------------------------------------
type TradeView = {
  status: VolSizingTradeStatus | 'no_instruction';
  label: string;
  detail: string;
  tone: 'ok' | 'warn' | 'muted' | 'bad';
};

type PositionSizing = {
  ticker: string;
  current_weight: number | null;
  recommended_weight: number | null;
  volatility: number | null;
  weight_change: number | null;
  shares_delta: number | null;
  amount_delta: number | null;
  sizing_price: number | null;
  rounding_residual: number | null;
  trade: TradeView;
}

const TRADE_TONES: Record<TradeView['tone'], string> = {
  ok: 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/40',
  warn: 'bg-amber-500/20 text-amber-300 border border-amber-500/40',
  bad: 'bg-rose-500/20 text-rose-300 border border-rose-500/40',
  muted: 'bg-slate-700/40 text-slate-300 border border-slate-600/40',
};

const TRADE_REASON_TEXT: Record<string, string> = {
  sizing_price_unavailable: 'No aligned sizing price: the notional is known, the share count is N/A.',
  portfolio_value_unavailable: 'No portfolio value: the notional and the share count are N/A.',
  no_aligned_price_snapshot: 'No aligned sizing price: the notional is known, the share count is N/A.',
};

function tradeView(
  trade: VolSizingTrade | undefined,
  currency: string,
  notionalFloor: number | null
): TradeView {
  if (!trade) {
    return {
      status: 'no_instruction',
      label: 'No sizing instruction',
      detail:
        'No usable return history for this leg: it was dropped from the sizing universe, so it has no target weight, notional, or share count.',
      tone: 'muted',
    };
  }
  const money = (value: number | null) => formatAmount(value, currency);
  const amount = finiteOrNull(trade.amount);
  const price = finiteOrNull(trade.sizing_price);
  const shares = finiteOrNull(trade.shares_delta);
  const residual = finiteOrNull(trade.rounding_residual);
  // A pre-contract entry carries no `status`; treat it as unproven rather than
  // trusting a bare 0 shares / 0 amount.
  const status: VolSizingTradeStatus = trade.status ?? 'unavailable';
  switch (status) {
    case 'executable':
      return {
        status,
        label: 'Executable',
        detail: `${formatShares(shares)} sh @ ${money(price)}`,
        tone: 'ok',
      };
    case 'below_minimum_notional':
      return {
        status,
        label: 'Below minimum lot',
        detail: `${money(amount)} notional cannot buy a whole share at ${money(price)}; ${money(residual)} left untraded. No order is expressible.`,
        tone: 'warn',
      };
    case 'immaterial_no_op':
      return {
        status,
        label: 'Immaterial — no order',
        detail: `${money(amount)} is below the ${money(notionalFloor)} minimum notional floor.`,
        tone: 'muted',
      };
    case 'no_trade_required':
      return { status, label: 'No trade required', detail: money(amount), tone: 'muted' };
    default:
      return {
        status: 'unavailable',
        label: 'Not executable',
        detail:
          TRADE_REASON_TEXT[trade.reason ?? ''] ??
          (trade.reason
            ? `Not executable (${trade.reason}).`
            : 'Not executable: the notional and the share count are N/A.'),
        tone: 'bad',
      };
  }
}

/**
 * Rows follow the universe the request actually covered, not the local roster:
 * a leg that lost its history stays visible as an explicit row with no target
 * weight and `shares_delta: null` instead of silently disappearing.
 */
function requestedUniverse(data: VolatilitySizingData): string[] {
  const coverage = data.universe_coverage;
  // A declared coverage report is authoritative even when it is empty: an empty
  // requested universe is a measured "no positions", not a reason to fall back
  // to whatever weights the response happens to carry.
  if (coverage) {
    return Array.isArray(coverage.requested_tickers) ? coverage.requested_tickers : [];
  }
  return Array.from(
    new Set([
      ...Object.keys(data.current_weights ?? {}),
      ...Object.keys(data.recommended_weights ?? {}),
      ...Object.keys(data.trades ?? {}),
    ])
  );
}

function buildRows(data: VolatilitySizingData): PositionSizing[] {
  const universe = requestedUniverse(data);
  const tickers = [
    ...universe,
    // A priced leg the universe report omitted must not vanish either.
    ...Object.keys(data.trades ?? {}).filter((ticker) => !universe.includes(ticker)),
  ];
  const defaultCurrency = data.sizing_price_currency ?? data.portfolio_value_currency ?? data.currency ?? 'INR';
  const notionalFloor = finiteOrNull(data.trade_reconciliation?.notional_floor);

  return tickers.map((ticker) => {
    const current = finiteOrNull(data.current_weights?.[ticker]);
    const recommended = finiteOrNull(data.recommended_weights?.[ticker]);
    const trade = data.trades?.[ticker];
    return {
      ticker,
      current_weight: current,
      recommended_weight: recommended,
      volatility: finiteOrNull(data.volatilities?.[ticker]),
      weight_change: current !== null && recommended !== null ? recommended - current : null,
      // A material notional that rounds to zero shares has no expressible
      // order: its notional is the fact worth showing, so the share cell is
      // N/A rather than a bare "0" that reads as "do nothing".
      shares_delta:
        trade && trade.status !== 'below_minimum_notional' ? finiteOrNull(trade.shares_delta) : null,
      amount_delta: trade ? finiteOrNull(trade.amount) : null,
      sizing_price: trade ? finiteOrNull(trade.sizing_price) : null,
      rounding_residual: trade ? finiteOrNull(trade.rounding_residual) : null,
      trade: tradeView(trade, trade?.amount_currency ?? defaultCurrency, notionalFloor),
    };
  });
}

/** Measured current weight first (descending); unmeasured legs last. */
function sortRows(rows: PositionSizing[]): PositionSizing[] {
  return [...rows].sort((a, b) => {
    if (a.current_weight === null && b.current_weight === null) return a.ticker.localeCompare(b.ticker);
    if (a.current_weight === null) return 1;
    if (b.current_weight === null) return -1;
    if (b.current_weight !== a.current_weight) return b.current_weight - a.current_weight;
    return a.ticker.localeCompare(b.ticker);
  });
}

type ActionView = { label: string; colorClass: string };

function actionOf(change: number | null): ActionView {
  if (change === null) {
    return {
      label: 'No target',
      colorClass: 'bg-slate-700/40 text-slate-400 border border-slate-600/40',
    };
  }
  if (change > 0.005) {
    return { label: 'Buy', colorClass: 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/40' };
  }
  if (change < -0.005) {
    return { label: 'Sell', colorClass: 'bg-rose-500/20 text-rose-300 border border-rose-500/40' };
  }
  return { label: 'Hold', colorClass: 'bg-slate-700/40 text-slate-300 border border-slate-600/40' };
}

export default function VolatilitySizingPage() {
  const [sizingData, setSizingData] = useState<VolatilitySizingData | null>(null);
  const [selectedModel, setSelectedModel] = useState('EWMA');
  const [targetVolatility, setTargetVolatility] = useState(0.15);
  const [loading, setLoading] = useState(false);
  const [activeExplainer, setActiveExplainer] = useState<string | null>(null);
  const [showRebalanceModal, setShowRebalanceModal] = useState(false);
  const [rebalancingInProgress, setRebalancingInProgress] = useState(false);
  const [rebalanceSuccessMsg, setRebalanceSuccessMsg] = useState<string | null>(null);
  const [rebalanceErrorMsg, setRebalanceErrorMsg] = useState<string | null>(null);
  const fetchSeq = useRef(0);
  const inited = useRef(false);
  const rebalanceCloseTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  const { fetchPortfolio } = usePortfolioStore();

  useEffect(() => {
    return () => {
      if (rebalanceCloseTimer.current) clearTimeout(rebalanceCloseTimer.current);
    };
  }, []);

  const fetchSizingData = async () => {
    const seq = ++fetchSeq.current;
    setLoading(true);
    try {
      const data = await analyticsApi.getVolatilitySizing({
        model: selectedModel,
        target_volatility: targetVolatility
      });
      if (seq !== fetchSeq.current) return;
      setSizingData(data);
    } catch (error) {
      if (seq !== fetchSeq.current) return;
      console.error('Failed to fetch volatility sizing data:', error);
      setSizingData(null);
    } finally {
      if (seq === fetchSeq.current) setLoading(false);
    }
  };

  // Always call the latest fetchSizingData (avoids stale model/target closures)
  const fetchRef = useRef(fetchSizingData);
  fetchRef.current = fetchSizingData;

  useEffect(() => {
    let alive = true;
    (async () => {
      try {
        await fetchPortfolio();
      } finally {
        if (alive) {
          inited.current = true;
          fetchRef.current();
        }
      }
    })();
    return () => {
      alive = false;
      fetchSeq.current++;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    if (!inited.current) return;
    fetchSizingData();
    return () => {
      fetchSeq.current++;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedModel, targetVolatility]);

  const handleModelChange = (model: string) => {
    setSelectedModel(model);
  };

  const handleTargetVolatilityChange = (vol: number) => {
    setTargetVolatility(vol);
  };

  const handleRefresh = () => {
    fetchSizingData();
  };

  const [rebalanceMode, setRebalanceMode] = useState<'simulate' | 'live'>('simulate');
  const [simulationData, setSimulationData] = useState<any | null>(null);

  // Rows are derived from the response, never from a separate state copy, so a
  // refetch can never leave a stale leg on screen.
  const positionData = useMemo(
    () => (sizingData ? sortRows(buildRows(sizingData)) : []),
    [sizingData]
  );
  const execution = useMemo(() => resolveExecution(sizingData), [sizingData]);
  const hasTarget = Object.keys(sizingData?.recommended_weights ?? {}).length > 0;
  // A response the engine could not measure is not an execution-grade target,
  // whatever weights it echoes back: no instruction exists to execute.
  const unavailableReason =
    sizingData?.data_status === 'unavailable'
      ? sizingData.error || 'the engine reported no measured sizing result'
      : sizingData?.error
        ? sizingData.error
        : null;
  const executionEligible =
    execution?.eligible === true && hasTarget && unavailableReason === null;
  const executionBlockReason = useMemo(
    () => executionBlockText(execution, hasTarget, unavailableReason),
    [execution, hasTarget, unavailableReason]
  );
  const universeCount = sizingData
    ? sizingData.universe_coverage?.requested_count ?? requestedUniverse(sizingData).length
    : 0;
  // One aligned price date backs every share count; it is never per-ticker.
  const sizingPriceAsOf =
    sizingData?.sizing_basis?.sizing_price_as_of ?? sizingData?.sizing_price_as_of ?? null;
  const sizingCurrency =
    sizingData?.sizing_basis?.price_currency ?? sizingData?.sizing_price_currency ?? null;

  const closeRebalanceModal = () => {
    setShowRebalanceModal(false);
    setSimulationData(null);
    setRebalanceErrorMsg(null);
  };

  useEffect(() => {
    if (!showRebalanceModal) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') closeRebalanceModal();
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [showRebalanceModal]);

  const handleRunSimulation = async () => {
    if (!sizingData?.recommended_weights) return;
    // Fail closed: a leveraged target is not a rebalance, so it is never sent.
    if (!executionEligible) {
      setRebalanceErrorMsg(executionBlockReason || 'This target is not eligible for a normal rebalance.');
      return;
    }
    setRebalancingInProgress(true);
    setRebalanceErrorMsg(null);
    try {
      const result = await portfolioApi.rebalancePortfolio(sizingData.recommended_weights, true);
      setSimulationData(result);
    } catch (err: any) {
      console.error('Failed to run simulation:', err);
      setRebalanceErrorMsg(`Simulation failed: ${err.message || 'Unknown error'}`);
    } finally {
      setRebalancingInProgress(false);
    }
  };

  const handleConfirmRebalance = async () => {
    if (!sizingData?.recommended_weights) return;
    if (!executionEligible) {
      setRebalanceErrorMsg(executionBlockReason || 'This target is not eligible for a normal rebalance.');
      return;
    }
    setRebalancingInProgress(true);
    setRebalanceErrorMsg(null);
    try {
      const result = await portfolioApi.rebalancePortfolio(sizingData.recommended_weights, false);
      setRebalanceSuccessMsg(result.message || 'Portfolio rebalancing executed successfully!');
      await fetchPortfolio();
      await fetchSizingData();
      if (rebalanceCloseTimer.current) clearTimeout(rebalanceCloseTimer.current);
      rebalanceCloseTimer.current = setTimeout(() => {
        setShowRebalanceModal(false);
        setRebalanceSuccessMsg(null);
        setSimulationData(null);
      }, 2000);
    } catch (err: any) {
      console.error('Failed to execute rebalance:', err);
      setRebalanceErrorMsg(`Rebalancing failed: ${err.message || 'Unknown error'}`);
    } finally {
      setRebalancingInProgress(false);
    }
  };

  // Format metrics for display
  const formatPercentage = (value: number | undefined | null, decimals = 1) => {
    if (value === undefined || value === null || isNaN(value)) {
      return 'N/A';
    }
    const scaled = Math.abs(value) <= 1.0 && value !== 0 ? value * 100 : value;
    return `${scaled.toFixed(decimals)}%`;
  };

  const formatCurrency = (value: number | undefined | null) => {
    if (value === undefined || value === null || isNaN(value)) {
      return 'N/A';
    }
    if (Math.abs(value) >= 10000000) return `₹${(value / 10000000).toFixed(2)} Cr`;
    if (Math.abs(value) >= 100000) return `₹${(value / 100000).toFixed(2)} L`;
    if (Math.abs(value) >= 1000) return `₹${(value / 1000).toFixed(1)}K`;
    return `₹${value.toLocaleString('en-IN', { maximumFractionDigits: 2 })}`;
  };

  const getChangeColor = (change: number | null): string => {
    if (change === null) return 'text-slate-400 font-medium';
    if (change > 0.005) return 'text-emerald-400 font-bold';
    if (change < -0.005) return 'text-rose-400 font-bold';
    return 'text-slate-400 font-medium';
  };

  const getVolRiskLabel = (vol: number | null) => {
    if (vol == null) return { label: 'N/A', color: 'text-slate-400 bg-slate-700/40 border-slate-600/40' };
    if (vol < 0.20) return { label: 'Low Risk', color: 'text-emerald-400 bg-emerald-500/20 border-emerald-500/40' };
    if (vol <= 0.35) return { label: 'Moderate', color: 'text-amber-400 bg-amber-500/20 border-amber-500/40' };
    return { label: 'Elevated', color: 'text-rose-400 bg-rose-500/20 border-rose-500/40' };
  };

  // CSV Export
  const handleExportCSV = () => {
    if (!positionData.length) return;
    const currency = sizingData?.sizing_price_currency ?? sizingData?.portfolio_value_currency ?? 'INR';
    const headers = [
      'Ticker',
      'Current Weight (%)',
      'Recommended Weight (%)',
      'Annualized Volatility (%)',
      'Weight Delta (%)',
      'Shares Delta',
      `Notional (${currency})`,
      'Sizing Price',
      'Trade Status',
      'Action',
    ];
    const pct = (value: number | null) => (value === null ? NOT_AVAILABLE : `${(value * 100).toFixed(2)}%`);
    const rows = positionData.map((p) => [
      escapeCsvCell(p.ticker),
      escapeCsvCell(pct(p.current_weight)),
      escapeCsvCell(pct(p.recommended_weight)),
      escapeCsvCell(pct(p.volatility)),
      escapeCsvCell(pct(p.weight_change)),
      // N/A, never 0: a leg with no whole-share instruction has no share count.
      escapeCsvCell(p.shares_delta === null ? NOT_AVAILABLE : String(p.shares_delta)),
      escapeCsvCell(p.amount_delta === null ? NOT_AVAILABLE : p.amount_delta.toFixed(2)),
      escapeCsvCell(p.sizing_price === null ? NOT_AVAILABLE : p.sizing_price.toFixed(4)),
      escapeCsvCell(p.trade.label),
      escapeCsvCell(actionOf(p.weight_change).label),
    ]);
    const csvContent = 'data:text/csv;charset=utf-8,' + [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', `volatility_sizing_${selectedModel.toLowerCase()}_${new Date().toISOString().split('T')[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Position sizing table columns
  const positionColumns: DataTableColumn<PositionSizing>[] = [
    {
      header: () => (
        <div className="flex items-center">
          <span>Ticker</span>
          <HelpBtn onClick={() => setActiveExplainer('ticker_col')} />
        </div>
      ),
      accessorKey: 'ticker',
      cell: ({ row }: any) => {
        const data = row.original || row;
        return (
          <div className="font-semibold text-slate-100">
            {data.ticker}
          </div>
        );
      },
    },
    {
      header: () => (
        <div className="flex items-center">
          <span>Current Weight</span>
          <HelpBtn onClick={() => setActiveExplainer('current_weight_col')} />
        </div>
      ),
      accessorKey: 'current_weight',
      cell: ({ row }: any) => {
        const data = row.original || row;
        return (
          <div className="text-slate-200 font-mono">
            {formatPercentage(data.current_weight)}
          </div>
        );
      },
    },
    {
      header: () => (
        <div className="flex items-center">
          <span>Recommended Weight</span>
          <HelpBtn onClick={() => setActiveExplainer('recommended_weight_col')} />
        </div>
      ),
      accessorKey: 'recommended_weight',
      cell: ({ row }: any) => {
        const data = row.original || row;
        return (
          <div className="text-teal-300 font-mono font-semibold">
            {formatPercentage(data.recommended_weight)}
          </div>
        );
      },
    },
    {
      header: () => (
        <div className="flex items-center">
          <span>Volatility (Annualized)</span>
          <HelpBtn onClick={() => setActiveExplainer('volatility_col')} />
        </div>
      ),
      accessorKey: 'volatility',
      cell: ({ row }: any) => {
        const data = row.original || row;
        const risk = getVolRiskLabel(data.volatility);
        return (
          <div className="flex items-center space-x-2">
            <span className="text-slate-200 font-mono font-medium">
              {formatPercentage(data.volatility)}
            </span>
            <span className={`px-2 py-0.5 text-xs rounded-full border ${risk.color}`}>
              {risk.label}
            </span>
          </div>
        );
      },
    },
    {
      header: () => (
        <div className="flex items-center">
          <span>Weight Delta</span>
          <HelpBtn onClick={() => setActiveExplainer('weight_change_col')} />
        </div>
      ),
      accessorKey: 'weight_change',
      cell: ({ row }: any) => {
        const data = row.original || row;
        const change = data.weight_change ?? null;
        return (
          <div className={`font-mono ${getChangeColor(change)}`}>
            {change !== null && change > 0 ? '+' : ''}{formatPercentage(change)}
          </div>
        );
      },
    },
    {
      header: () => (
        <div className="flex items-center">
          <span>Notional</span>
          <HelpBtn onClick={() => setActiveExplainer('notional_col')} />
        </div>
      ),
      accessorKey: 'amount_delta',
      cell: ({ row }: any) => {
        const data = row.original || row;
        return (
          <div className="text-slate-200 font-mono">
            {formatAmount(data.amount_delta, sizingCurrency ?? 'INR')}
          </div>
        );
      },
    },
    {
      header: () => (
        <div className="flex items-center">
          <span>Shares Δ</span>
          <HelpBtn onClick={() => setActiveExplainer('shares_delta_col')} />
        </div>
      ),
      accessorKey: 'shares_delta',
      cell: ({ row }: any) => {
        const data = row.original || row;
        // N/A, never 0: a leg without a whole-share instruction has no count.
        return (
          <div className="text-slate-200 font-mono">
            {data.shares_delta === null ? NOT_AVAILABLE : formatShares(data.shares_delta)}
          </div>
        );
      },
    },
    {
      header: () => (
        <div className="flex items-center">
          <span>Trade Status</span>
          <HelpBtn onClick={() => setActiveExplainer('trade_status_col')} />
        </div>
      ),
      accessorKey: 'trade',
      cell: ({ row }: any) => {
        const data = row.original || row;
        const trade: TradeView = data.trade;
        return (
          <span
            className={`px-2.5 py-0.5 text-xs rounded-full font-semibold ${TRADE_TONES[trade.tone]}`}
            title={trade.detail}
          >
            {trade.label}
          </span>
        );
      },
    },
    {
      header: () => (
        <div className="flex items-center">
          <span>Action</span>
          <HelpBtn onClick={() => setActiveExplainer('action_col')} />
        </div>
      ),
      accessorKey: 'action',
      cell: ({ row }: any) => {
        const data = row.original || row;
        const action = actionOf(data.weight_change ?? null);
        return (
          <span className={`px-2.5 py-0.5 text-xs rounded-full font-semibold ${action.colorClass}`}>
            {action.label}
          </span>
        );
      },
    },
  ];

  // Calculate summary metrics
  const totalWeightChange = positionData.reduce(
    (sum, pos) => sum + Math.abs(pos.weight_change ?? 0),
    0
  );
  const buyCount = positionData.filter(pos => (pos.weight_change ?? 0) > 0.005).length;
  const sellCount = positionData.filter(pos => (pos.weight_change ?? 0) < -0.005).length;
  const holdCount = positionData.filter(
    pos => pos.weight_change !== null && Math.abs(pos.weight_change) <= 0.005
  ).length;
  // A dropped leg has no target weight; it is neither a buy, a sell, nor a hold.
  const noTargetCount = positionData.filter(pos => pos.weight_change === null).length;
  const belowLotCount = positionData.filter(
    pos => pos.trade.status === 'below_minimum_notional'
  ).length;

  return (
    <div className="space-y-6">
      {/* Active Explainer Modal */}
      {activeExplainer && (
        <HelpExplainerModal
          itemKey={activeExplainer}
          onClose={() => setActiveExplainer(null)}
          positionCount={universeCount}
        />
      )}

      {/* Sizing response unavailable / errored: never render a zero-filled book */}
      {sizingData && (sizingData.error || sizingData.data_status === 'unavailable') && (
        <div
          data-testid="sizing-error-banner"
          className="bg-amber-950/30 border border-amber-800/50 rounded-xl p-4 text-xs text-amber-200 flex items-start space-x-2"
        >
          <AlertTriangle className="w-4 h-4 mt-0.5 shrink-0 text-amber-400" />
          <div>
            <span className="font-bold">Volatility sizing unavailable: </span>
            {sizingData.error || 'The engine reported no measured sizing result.'}
            <span className="block mt-1 text-amber-300/80">
              Weights, notionals, and share counts below are N/A — no value was inferred.
            </span>
          </div>
        </div>
      )}

      {/* Execution basis: gross exposure, cash residue, and any financing */}
      {execution && (
        <div
          data-testid="exposure-banner"
          className={`rounded-xl p-4 text-xs border ${
            execution.financingRequired
              ? 'bg-rose-950/30 border-rose-800/50 text-rose-200'
              : 'bg-slate-900 border-slate-800 text-slate-300'
          }`}
        >
          <div className="flex flex-wrap items-center gap-x-5 gap-y-1.5">
            <span>
              <span className="text-slate-400">Gross exposure: </span>
              <span className="font-mono font-bold text-white">{formatWeight(execution.grossExposure)}</span>
            </span>
            <span>
              <span className="text-slate-400">Net cash: </span>
              <span className={`font-mono font-bold ${(execution.netCashWeight ?? 0) < 0 ? 'text-rose-300' : 'text-emerald-300'}`}>
                {formatWeight(execution.netCashWeight)}
              </span>
            </span>
            <span>
              <span className="text-slate-400">Financing: </span>
              <span className="font-mono font-bold text-white">
                {execution.financingRequired
                  ? `${formatAmount(execution.financing.amount, execution.financing.currency ?? 'INR')} (${formatWeight(financingWeightOf(execution))})`
                  : 'none'}
              </span>
            </span>
            <span>
              <span className="text-slate-400">Portfolio value: </span>
              <span className="font-mono font-bold text-white">
                {formatAmount(finiteOrNull(sizingData?.exposure?.portfolio_value ?? sizingData?.portfolio_value), sizingData?.exposure?.currency ?? sizingData?.portfolio_value_currency ?? 'INR')}
              </span>
            </span>
            {execution.mode && (
              <span>
                <span className="text-slate-400">Mode: </span>
                <span className="font-mono text-white">{execution.mode}</span>
              </span>
            )}
            {execution.source === 'derived' && (
              <span className="text-slate-400">
                Gross exposure derived from the delivered weights (no execution block reported).
              </span>
            )}
          </div>
        </div>
      )}

      {/* Sizing basis: model, measured window, sample size, price date, currency */}
      {sizingData && (
        <div
          data-testid="sizing-basis"
          className="rounded-xl border border-slate-800 bg-slate-900 p-3.5 text-[11px] text-slate-300 flex flex-wrap items-center gap-x-4 gap-y-1.5"
        >
          <span>
            <span className="text-slate-500">Model: </span>
            <span className="font-mono text-teal-300">{sizingData.sizing_history?.model ?? selectedModel}</span>
          </span>
          <span>
            <span className="text-slate-500">Window: </span>
            <span className="font-mono">
              {sizingData.sizing_history?.window_start && sizingData.sizing_history?.window_end
                ? `${sizingData.sizing_history.window_start} → ${sizingData.sizing_history.window_end}`
                : 'not reported'}
            </span>
          </span>
          <span>
            <span className="text-slate-500">Return observations: </span>
            <span className="font-mono">
              {sizingData.sizing_history
                ? `${sizingData.sizing_history.return_observations} (min ${sizingData.sizing_history.min_return_observations} · ${sizingData.sizing_history.minimum_observations_required} required)`
                : 'not reported'}
            </span>
          </span>
          <span>
            <span className="text-slate-500">Latest observation: </span>
            <span className="font-mono">{sizingData.sizing_history?.latest_observation ?? 'not reported'}</span>
          </span>
          <span>
            <span className="text-slate-500">Sizing price as of: </span>
            <span className="font-mono">{sizingPriceAsOf ?? 'unavailable'}</span>
          </span>
          <span>
            <span className="text-slate-500">Currency: </span>
            <span className="font-mono">{sizingCurrency ?? 'not reported'}</span>
          </span>
          {sizingData.sizing_history ? (
            <span
              data-testid="sizing-sample-status"
              className={`px-2 py-0.5 rounded-full font-semibold border ${
                sizingData.sizing_history.meets_minimum_sample
                  ? 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40'
                  : 'bg-amber-500/20 text-amber-300 border-amber-500/40'
              }`}
            >
              {sizingData.sizing_history.meets_minimum_sample
                ? 'Sufficient sample'
                : `Insufficient sample: ${sizingData.sizing_history.return_observations} of ${sizingData.sizing_history.minimum_observations_required} observations`}
              {sizingData.sizing_history.tickers_below_minimum_sample.length > 0
                ? ` — below minimum: ${sizingData.sizing_history.tickers_below_minimum_sample.join(', ')}`
                : ''}
            </span>
          ) : (
            <span className="text-slate-500">Minimum-sample status: not reported</span>
          )}
        </div>
      )}

      {/* Rebalance Confirmation & Simulation Modal */}
      {showRebalanceModal && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-sm animate-fadeIn"
          onClick={closeRebalanceModal}
        >
          <div
            role="dialog"
            aria-modal="true"
            aria-label={rebalanceMode === 'simulate' ? 'Simulate Rebalance' : 'Execute Live Rebalance'}
            className="bg-slate-900 border border-slate-700 rounded-xl max-w-2xl w-full p-6 shadow-2xl relative text-slate-100 max-h-[90vh] overflow-y-auto"
            onClick={(e) => e.stopPropagation()}
          >
            <button
              onClick={closeRebalanceModal}
              className="absolute top-4 right-4 text-slate-400 hover:text-white p-1 rounded-lg hover:bg-slate-800 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-400"
              aria-label="Close"
            >
              <X className="w-5 h-5" />
            </button>

            <div className="flex items-center space-x-3 mb-4">
              <div className={`p-2 rounded-lg ${rebalanceMode === 'simulate' ? 'bg-teal-500/20 text-teal-400' : 'bg-amber-500/20 text-amber-400'}`}>
                <ShieldCheck className="w-6 h-6" />
              </div>
              <div>
                <h3 className="text-xl font-bold text-white">
                  {rebalanceMode === 'simulate' ? 'Simulate Rebalance (Dry-Run)' : 'Execute Live Rebalance'}
                </h3>
                <p className="text-xs text-slate-400">
                  {rebalanceMode === 'simulate'
                    ? 'Test risk parity allocations and review exact cash / share deltas with zero database mutations.'
                    : 'Apply updated target weights atomically to your active portfolio database.'}
                </p>
              </div>
            </div>

            {/* Mode Selector Tabs */}
            <div className="flex rounded-lg bg-slate-800/80 p-1 mb-4 border border-slate-700">
              <button
                onClick={() => setRebalanceMode('simulate')}
                className={`flex-1 py-1.5 text-xs font-bold rounded-md transition-all ${
                  rebalanceMode === 'simulate'
                    ? 'bg-teal-600 text-white shadow-sm'
                    : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                🧪 Dry-Run Simulation (Safe Sandbox)
              </button>
              <button
                onClick={() => setRebalanceMode('live')}
                className={`flex-1 py-1.5 text-xs font-bold rounded-md transition-all ${
                  rebalanceMode === 'live'
                    ? 'bg-amber-500 text-slate-950 shadow-sm'
                    : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                ⚡ Live Database Commit
              </button>
            </div>

            {/* In-page rebalance error (replaces native alert) */}
            {rebalanceErrorMsg && (
              <div
                data-testid="rebalance-error"
                className="bg-red-950/40 border border-red-800/60 p-3 rounded-lg text-xs text-red-300 mb-4 flex items-start space-x-2"
              >
                <AlertTriangle className="w-4 h-4 mt-0.5 shrink-0 text-red-400" />
                <span>{rebalanceErrorMsg}</span>
              </div>
            )}

            {/* Fail-closed gate: an ineligible target never reaches the API */}
            {!executionEligible && (
              <div
                data-testid="execution-blocked"
                className="bg-rose-950/30 border border-rose-800/50 p-3 rounded-lg text-xs text-rose-200 mb-4 flex items-start space-x-2"
              >
                <Lock className="w-4 h-4 mt-0.5 shrink-0 text-rose-400" />
                <div>
                  <span className="font-bold">Rebalance blocked: </span>
                  {executionBlockReason || 'This target cannot be applied as a normal rebalance.'}
                </div>
              </div>
            )}

            {rebalanceSuccessMsg ? (
              <div className="bg-emerald-950/40 border border-emerald-800/60 p-6 rounded-xl text-center space-y-3 my-4">
                <CheckCircle2 className="w-12 h-12 text-emerald-400 mx-auto" />
                <h4 className="text-lg font-bold text-emerald-300">{rebalanceSuccessMsg}</h4>
                <p className="text-xs text-slate-300">Your holdings database has been atomically updated and normalized.</p>
              </div>
            ) : (
              <div className="space-y-4 text-sm">
                <div className="grid grid-cols-3 gap-3 p-3.5 bg-slate-800/80 rounded-lg border border-slate-700">
                  <div className="text-center">
                    <span className="text-xs text-slate-400">Buy Orders</span>
                    <p className="text-lg font-bold text-emerald-400">{buyCount}</p>
                  </div>
                  <div className="text-center">
                    <span className="text-xs text-slate-400">Sell / Trim Orders</span>
                    <p className="text-lg font-bold text-rose-400">{sellCount}</p>
                  </div>
                  <div className="text-center">
                    <span className="text-xs text-slate-400">Turnover Delta</span>
                    <p className="text-lg font-bold text-teal-400">{(totalWeightChange * 100).toFixed(1)}%</p>
                  </div>
                </div>

                {rebalanceMode === 'simulate' && simulationData && (
                  <div className="p-3.5 bg-teal-950/30 border border-teal-800/50 rounded-xl space-y-2">
                    <div className="flex items-center justify-between text-xs">
                      <span className="font-bold text-teal-300">🧪 Simulation Analysis Results:</span>
                      <span className="text-[11px] px-2 py-0.5 rounded bg-teal-900/60 text-teal-200 border border-teal-700/50">
                        0 Database Changes
                      </span>
                    </div>
                    <div className="grid grid-cols-2 gap-2 text-xs pt-1">
                      <div className="p-2 rounded bg-slate-800/80 border border-slate-700">
                        <span className="text-slate-400">Total Buy Capital:</span>
                        <p className="font-mono font-bold text-emerald-400">{formatCurrency(simulationData.total_buy_inr)}</p>
                      </div>
                      <div className="p-2 rounded bg-slate-800/80 border border-slate-700">
                        <span className="text-slate-400">Total Sell Capital:</span>
                        <p className="font-mono font-bold text-rose-400">{formatCurrency(simulationData.total_sell_inr)}</p>
                      </div>
                    </div>
                    {simulationData.weight_normalization && (
                      <p
                        data-testid="simulation-normalization"
                        className="pt-1 text-[11px] text-teal-200/80 font-mono"
                      >
                        Normalization rule: {simulationData.weight_normalization.normalization_rule} · mode{' '}
                        {simulationData.weight_normalization.normalization_mode} · submitted gross exposure{' '}
                        {formatWeight(simulationData.weight_normalization.submitted_gross_exposure)}
                        {simulationData.weight_normalization.weights_normalized
                          ? ' (legs divided by gross exposure)'
                          : ' (legs already sum to 100%)'}
                      </p>
                    )}
                  </div>
                )}

                <div className="space-y-2 max-h-56 overflow-y-auto pr-1">
                  <h4 className="text-xs font-semibold text-slate-300 uppercase tracking-wider">
                    {rebalanceMode === 'simulate' ? 'Simulated Order Ticket:' : 'Proposed Live Allocation Changes:'}
                  </h4>
                  {positionData.map((p) => {
                    const action = actionOf(p.weight_change);
                    return (
                      <div key={p.ticker} className="flex items-center justify-between p-2.5 rounded bg-slate-800/50 border border-slate-700/40 text-xs">
                        <div className="flex items-center space-x-2">
                          <span className="font-semibold text-slate-200 w-24">{p.ticker}</span>
                          <span className="text-slate-400 font-mono">{formatPercentage(p.current_weight)}</span>
                          <ArrowRight className="w-3 h-3 text-slate-500" />
                          <span className="text-teal-300 font-mono font-bold">{formatPercentage(p.recommended_weight)}</span>
                        </div>
                        <div className="flex items-center space-x-3">
                          <span
                            className="text-slate-400 font-mono text-[11px]"
                            title={p.trade.detail}
                          >
                            {p.shares_delta === null
                              ? NOT_AVAILABLE
                              : `${formatShares(p.shares_delta)} shs`}
                            {p.amount_delta !== null &&
                              ` · ${formatAmount(p.amount_delta, sizingCurrency ?? 'INR')}`}
                          </span>
                          <span className={`font-mono ${getChangeColor(p.weight_change)}`}>
                            {p.weight_change !== null && p.weight_change > 0 ? '+' : ''}{formatPercentage(p.weight_change)}
                          </span>
                          <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                            action.label === 'Buy' ? 'bg-emerald-500/20 text-emerald-300' :
                            action.label === 'Sell' ? 'bg-rose-500/20 text-rose-300' : 'bg-slate-700 text-slate-400'
                          }`}>
                            {action.label}
                          </span>
                        </div>
                      </div>
                    );
                  })}
                </div>

                {rebalanceMode === 'simulate' ? (
                  <div className="p-3 bg-teal-950/20 border border-teal-800/30 rounded-lg text-teal-200 text-xs leading-relaxed">
                    💡 <span className="font-semibold">Safe Sandbox Mode:</span> Running simulation calculates execution deltas without modifying the database. You can review all orders safely.
                  </div>
                ) : (
                  <div className="p-3 bg-amber-950/30 border border-amber-800/40 rounded-lg text-amber-200 text-xs leading-relaxed">
                    ⚠️ <span className="font-semibold">Live Database Execution:</span> Confirming will update position weights and quantities in your SQLite database.
                  </div>
                )}

                <div className="flex items-center justify-end space-x-3 pt-4 border-t border-slate-800">
                  <button
                    onClick={closeRebalanceModal}
                    className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg text-sm transition-colors"
                  >
                    Close
                  </button>

                  {rebalanceMode === 'simulate' ? (
                    <button
                      onClick={handleRunSimulation}
                      disabled={rebalancingInProgress || !executionEligible}
                      className="px-5 py-2 bg-teal-600 hover:bg-teal-500 text-white font-bold rounded-lg text-sm transition-colors shadow-lg flex items-center disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:bg-teal-600"
                    >
                      {rebalancingInProgress ? (
                        <>
                          <RefreshCw className="w-4 h-4 mr-2 animate-spin" />
                          Simulating...
                        </>
                      ) : (
                        '🧪 Run Simulation Test'
                      )}
                    </button>
                  ) : (
                    <button
                      onClick={handleConfirmRebalance}
                      disabled={rebalancingInProgress || !executionEligible}
                      className="px-5 py-2 bg-amber-500 hover:bg-amber-400 text-slate-950 font-bold rounded-lg text-sm transition-colors shadow-lg flex items-center disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:bg-amber-500"
                    >
                      {rebalancingInProgress ? (
                        <>
                          <RefreshCw className="w-4 h-4 mr-2 animate-spin" />
                          Executing Live...
                        </>
                      ) : (
                        '⚡ Confirm Live Rebalance'
                      )}
                    </button>
                  )}
                </div>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Hero Section */}
      <div className="bg-gradient-to-r from-teal-600 via-cyan-600 to-blue-600 rounded-xl p-6 text-white shadow-lg relative overflow-hidden">
        <div className="absolute right-0 top-0 translate-x-8 -translate-y-8 w-64 h-64 bg-white/10 rounded-full blur-3xl pointer-events-none" />
        <div className="flex items-center justify-between relative z-10">
          <div>
            <div className="flex items-center space-x-3 mb-2">
              <h1 className="text-3xl font-bold tracking-tight">Volatility Sizing</h1>
              <span className="px-3 py-0.5 rounded-full text-xs font-semibold bg-white/20 text-white backdrop-blur-sm">
                RISK PARITY ENGINE
              </span>
            </div>
            <p className="text-teal-100 max-w-2xl text-sm leading-relaxed">
              Volatility-adjusted position sizing, risk budget scaling, and inverse-volatility parity recommendations across all {universeCount || 'N/A'} positions in the requested universe.
            </p>
            <div className="flex flex-wrap items-center mt-4 gap-3">
              <div className="bg-black/20 backdrop-blur-md px-3 py-1.5 rounded-lg text-teal-100 text-xs font-medium border border-white/10">
                Target Vol: <span className="font-bold text-white ml-1">{formatPercentage(targetVolatility)}</span>
              </div>
              <div className="bg-black/20 backdrop-blur-md px-3 py-1.5 rounded-lg text-teal-100 text-xs font-medium border border-white/10">
                Model: <span className="font-bold text-white ml-1">{selectedModel}</span>
              </div>
              <div className="bg-black/20 backdrop-blur-md px-3 py-1.5 rounded-lg text-teal-100 text-xs font-medium border border-white/10">
                Est. Portfolio Vol: <span className="font-bold text-white ml-1">{sizingData?.current_volatility ? formatPercentage(sizingData.current_volatility) : 'N/A'}</span>
              </div>
            </div>
          </div>
          <div className="hidden md:flex items-center space-x-3">
            <button
              onClick={handleRefresh}
              disabled={loading}
              className="bg-white/20 hover:bg-white/30 rounded-xl p-2.5 transition-colors border border-white/10 shadow-sm"
              title="Refresh Sizing Analytics"
            >
              <RefreshCw className={`w-5 h-5 ${loading ? 'animate-spin' : ''}`} />
            </button>
            <div className="p-3 bg-white/10 backdrop-blur-md rounded-xl border border-white/20 shadow-inner">
              <Target className="w-10 h-10 text-teal-200" />
            </div>
          </div>
        </div>
      </div>

      {/* Provenance bound to `sizing_price_as_of`, NOT the section date. The
          route's own rule is explicit that the price date is what the share
          counts were struck from, so dating the trade list by the section
          `as_of` would misdescribe every executable number on this page. */}
      <SectionProvenance
        section="Volatility sizing"
        asOf={
          sizingData?.sizing_basis?.price_freshness?.sizing_price_as_of
          ?? sizingPriceAsOf
        }
        asOfSemantics={
          sizingData?.sizing_basis?.price_freshness
            ? 'sizing_price_as_of: the last close delivered inside the sizing window, and the only price every share_delta was divided by'
            : null
        }
        coverage={sectionCoverage(sizingData?.universe_coverage)}
        warnings={[
          ...(sizingData?.warnings ?? []),
          ...(sizingData?.sizing_basis?.price_freshness?.sizing_price_calendar_days_behind != null
            ? [
                `Sizing prices are ${sizingData.sizing_basis.price_freshness.sizing_price_calendar_days_behind} calendar day(s) behind the newest delivered observation (${sizingData.sizing_basis.price_freshness.latest_delivered_observation}).`,
              ]
            : []),
        ]}
      />

      {/* Volatility Sizing Metric Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="relative group">
          <MetricCard
            title="Target Volatility"
            value={formatPercentage(targetVolatility)}
            icon={Target}
            loading={loading}
          />
          <div className="absolute top-4 right-4 z-10">
            <HelpBtn onClick={() => setActiveExplainer('target_volatility')} />
          </div>
        </div>

        <div className="relative group">
          <MetricCard
            title="Est. Portfolio Vol"
            value={sizingData?.current_volatility ? formatPercentage(sizingData.current_volatility) : 'N/A'}
            icon={Activity}
            loading={loading}
          />
          <p className="mt-2 text-xs text-gray-500 dark:text-gray-400">
            {selectedModel === 'EWMA'
              ? 'EWMA conditional estimate (RiskMetrics λ=0.94) · 252d window — current vol for sizing; differs from Forecast Risk (forward projection) & Realized Risk (trailing realized)'
              : `${selectedModel} conditional estimate · 252d window — current vol for sizing; differs from Forecast Risk (forward projection) & Realized Risk (trailing realized)`}
          </p>
          <div className="absolute top-4 right-4 z-10">
            <HelpBtn onClick={() => setActiveExplainer('estimated_portfolio_vol')} />
          </div>
        </div>

        <div className="relative group">
          <MetricCard
            title="Active Model"
            value={selectedModel}
            icon={TrendingUp}
            loading={loading}
          />
          <div className="absolute top-4 right-4 z-10">
            <HelpBtn onClick={() => setActiveExplainer('model_selector')} />
          </div>
        </div>

        <div className="relative group">
          <MetricCard
            title="Total Positions"
            value={sizingData ? String(universeCount) : 'N/A'}
            icon={Zap}
            loading={loading}
          />
          <div className="absolute top-4 right-4 z-10">
            <HelpBtn onClick={() => setActiveExplainer('total_positions')} />
          </div>
        </div>
      </div>

      {/* Model Configuration & Target Setting */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-sm">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center space-x-2">
              <h3 className="text-lg font-bold text-white">Volatility Models</h3>
              <HelpBtn onClick={() => setActiveExplainer('model_selector')} />
            </div>
            <Activity className="w-5 h-5 text-slate-400" />
          </div>
          <div className="space-y-3">
            {MODELS.map((model) => (
              <div
                key={model.id}
                role="button"
                tabIndex={0}
                className={`p-4 border-2 rounded-xl cursor-pointer transition-all ${
                  selectedModel === model.id
                    ? 'border-teal-500 bg-teal-950/30 shadow-md'
                    : 'border-slate-800 hover:border-slate-700 bg-slate-800/30'
                }`}
                onClick={() => handleModelChange(model.id)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' || e.key === ' ') {
                    e.preventDefault();
                    handleModelChange(model.id);
                  }
                }}
              >
                <div className="flex items-center justify-between">
                  <h4 className={`font-semibold ${
                    selectedModel === model.id
                      ? 'text-teal-300'
                      : 'text-slate-200'
                  }`}>
                    {model.name}
                  </h4>
                  {selectedModel === model.id && (
                    <div className="w-3.5 h-3.5 bg-teal-400 rounded-full shadow-glow"></div>
                  )}
                </div>
                <p className="text-xs mt-1 text-slate-400 leading-relaxed">
                  {model.description}
                </p>
              </div>
            ))}
          </div>
        </div>

        <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-sm">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center space-x-2">
              <h3 className="text-lg font-bold text-white">Target Volatility Setting</h3>
              <HelpBtn onClick={() => setActiveExplainer('target_volatility')} />
            </div>
            <Target className="w-5 h-5 text-slate-400" />
          </div>
          <div className="space-y-5 pt-2">
            <div>
              <div className="flex justify-between items-center mb-2 text-sm">
                <label className="font-medium text-slate-300">Target Portfolio Volatility</label>
                <span className="font-mono font-bold text-teal-400 text-base">{formatPercentage(targetVolatility)}</span>
              </div>
              <input
                type="range"
                min="0.05"
                max="0.30"
                step="0.01"
                value={targetVolatility}
                onChange={(e) => handleTargetVolatilityChange(parseFloat(e.target.value))}
                className="w-full accent-teal-500 bg-slate-800 rounded-lg cursor-pointer"
              />
              <div className="flex justify-between text-xs text-slate-400 mt-1.5 font-mono">
                <span>5.0% (Defensive)</span>
                <span>15.0% (Balanced)</span>
                <span>30.0% (Aggressive)</span>
              </div>
            </div>
            
            <div className="grid grid-cols-3 gap-3 pt-2">
              {[0.10, 0.15, 0.20].map((vol) => (
                <button
                  key={vol}
                  className={`py-2.5 px-3 text-xs font-semibold rounded-lg border transition-all ${
                    targetVolatility === vol
                      ? 'border-amber-500/80 bg-amber-950/40 text-amber-300 shadow-sm'
                      : 'border-slate-700 hover:border-slate-600 text-slate-300 bg-slate-800/40'
                  }`}
                  onClick={() => handleTargetVolatilityChange(vol)}
                >
                  {formatPercentage(vol)} Preset
                </button>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Position Sizing Visualizations */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Volatility-Adjusted Weights */}
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-sm">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center space-x-2">
              <h3 className="text-lg font-bold text-white">
                Volatility-Adjusted Weights
              </h3>
              <HelpBtn onClick={() => setActiveExplainer('volatility_adjusted_weights')} />
            </div>
            <BarChart3 className="w-5 h-5 text-slate-400" />
          </div>
          <div className="space-y-4">
            {positionData.slice(0, 7).map((position) => (
              <div key={position.ticker} className="space-y-1.5 bg-slate-800/40 p-2.5 rounded-lg border border-slate-700/40">
                <div className="flex items-center justify-between">
                  <span className="text-sm font-semibold text-slate-200">
                    {position.ticker}
                  </span>
                  <span className="text-xs text-slate-400 font-mono">
                    Target: <span className="text-teal-300 font-bold">{formatPercentage(position.recommended_weight)}</span>
                  </span>
                </div>
                <div className="flex items-center space-x-2">
                  <span className="text-[11px] text-slate-400 w-14">Current</span>
                  <div className="flex-1 bg-slate-800 rounded-full h-2 overflow-hidden">
                    {/* An unknown weight draws no bar; the label beside it says N/A. */}
                    <div
                      className="h-full rounded-full bg-blue-500 transition-all duration-500"
                      style={{ width: `${Math.min(100, (position.current_weight ?? 0) * 500)}%` }}
                    />
                  </div>
                  <span className="text-xs font-mono text-slate-300 w-12 text-right">
                    {formatPercentage(position.current_weight)}
                  </span>
                </div>
                <div className="flex items-center space-x-2">
                  <span className="text-[11px] text-slate-400 w-14">Adjusted</span>
                  <div className="flex-1 bg-slate-800 rounded-full h-2 overflow-hidden">
                    <div
                      className={`h-full rounded-full transition-all duration-500 ${
                        (position.weight_change ?? 0) > 0.005 ? 'bg-emerald-500' :
                        (position.weight_change ?? 0) < -0.005 ? 'bg-rose-500' : 'bg-slate-500'
                      }`}
                      style={{ width: `${Math.min(100, (position.recommended_weight ?? 0) * 500)}%` }}
                    />
                  </div>
                  <span className={`text-xs font-mono w-12 text-right ${getChangeColor(position.weight_change)}`}>
                    {formatPercentage(position.recommended_weight)}
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Volatility Forecast & Parity Targets */}
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-sm">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center space-x-2">
              <h3 className="text-lg font-bold text-white">
                Volatility Forecast & Parity Targets
              </h3>
              <HelpBtn onClick={() => setActiveExplainer('volatility_forecast_parity')} />
            </div>
            <Activity className="w-5 h-5 text-slate-400" />
          </div>
          
          <div className="p-3 bg-slate-800/70 rounded-lg border border-slate-700/60 mb-4 flex items-center justify-between text-xs">
            <div>
              <span className="text-slate-400">Model Calibration:</span>
              <span className="ml-1.5 font-semibold text-teal-300">{selectedModel} Inverse-Vol Parity</span>
            </div>
            <div>
              <span className="text-slate-400">Target Risk:</span>
              <span className="ml-1.5 font-semibold text-amber-300">{formatPercentage(targetVolatility)}</span>
            </div>
          </div>

          <div className="space-y-3 max-h-[380px] overflow-y-auto pr-1">
            {positionData.map((position) => {
              const risk = getVolRiskLabel(position.volatility);
              return (
                <div key={position.ticker} className="flex items-center justify-between p-2.5 rounded-lg bg-slate-800/40 border border-slate-700/40">
                  <div className="flex items-center space-x-2">
                    <span className="text-sm font-semibold text-slate-200 w-28 truncate">{position.ticker}</span>
                    <span className={`px-2 py-0.5 text-[10px] rounded-full border ${risk.color}`}>
                      {risk.label}
                    </span>
                  </div>
                  <div className="flex items-center space-x-3">
                    <span className="font-mono text-xs text-amber-300 font-bold">
                      σ = {formatPercentage(position.volatility)}
                    </span>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>

      {/* Position-Level Sizing Analysis Table */}
      {positionData.length > 0 && (
        <div className="bg-slate-900 border border-slate-800 rounded-xl shadow-sm overflow-hidden">
          <div className="p-5 border-b border-slate-800 flex items-center justify-between flex-wrap gap-3">
            <div>
              <h3 className="text-lg font-bold text-white">
                Position-Level Sizing Analysis ({positionData.length})
              </h3>
              <p className="text-xs text-slate-400 mt-0.5">
                Current versus risk-parity weights, model volatility estimates, and trade execution sizing.
              </p>
            </div>
            <div className="flex items-center space-x-3">
              <button
                onClick={handleExportCSV}
                className="flex items-center px-3 py-1.5 text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg border border-slate-700 transition-colors shadow-sm"
              >
                <Download className="w-3.5 h-3.5 mr-1.5 text-teal-400" />
                Export CSV
              </button>
              <button
                onClick={() => {
                  setRebalanceErrorMsg(null);
                  setRebalanceSuccessMsg(null);
                  setShowRebalanceModal(true);
                }}
                disabled={!executionEligible}
                title={executionEligible ? 'Open the rebalance ticket' : executionBlockReason || undefined}
                className="flex items-center px-4 py-1.5 text-xs font-bold bg-amber-500 hover:bg-amber-400 text-slate-950 rounded-lg transition-colors shadow-md disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:bg-amber-500"
              >
                {executionEligible ? (
                  <ShieldCheck className="w-3.5 h-3.5 mr-1.5" />
                ) : (
                  <Lock className="w-3.5 h-3.5 mr-1.5" />
                )}
                Execute Rebalance
              </button>
            </div>
          </div>

          {/* Ineligible target: say so here, not only inside the ticket */}
          {executionBlockReason && (
            <div
              data-testid="execution-blocked"
              className="px-5 py-3 bg-rose-950/20 border-b border-rose-900/40 text-xs text-rose-200 flex items-start space-x-2"
            >
              <Lock className="w-4 h-4 mt-0.5 shrink-0 text-rose-400" />
              <div>
                <span className="font-bold">Rebalance blocked: </span>
                {executionBlockReason}
                {belowLotCount > 0 && (
                  <span className="block mt-1 text-rose-300/80">
                    {belowLotCount} leg{belowLotCount === 1 ? '' : 's'} carry a notional below the minimum
                    lot and cannot be expressed as an order.
                  </span>
                )}
              </div>
            </div>
          )}

          <DataTable
            data={positionData}
            columns={positionColumns}
            loading={loading}
            searchablePlaceholder="Search positions by ticker..."
            exportable={false}
          />
        </div>
      )}

      {/* Rebalancing Recommendations */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-sm">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center space-x-2">
            <h3 className="text-lg font-bold text-white">Rebalancing Recommendations</h3>
            <HelpBtn onClick={() => setActiveExplainer('rebalancing_recommendations')} />
          </div>
          <Zap className="w-5 h-5 text-slate-400" />
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-4">
          <div className="p-4 rounded-xl bg-emerald-950/20 border border-emerald-800/40 text-center">
            <p className="text-2xl font-bold text-emerald-400">{buyCount}</p>
            <p className="text-xs text-emerald-300 font-semibold mt-1">Buy / Increase Positions</p>
          </div>
          <div className="p-4 rounded-xl bg-rose-950/20 border border-rose-800/40 text-center">
            <p className="text-2xl font-bold text-rose-400">{sellCount}</p>
            <p className="text-xs text-rose-300 font-semibold mt-1">Sell / Trim Positions</p>
          </div>
          <div className="p-4 rounded-xl bg-slate-800/40 border border-slate-700/60 text-center">
            <p className="text-2xl font-bold text-slate-300">{holdCount}</p>
            <p className="text-xs text-slate-400 font-semibold mt-1">Hold / Unchanged Positions</p>
          </div>
          <div className="p-4 rounded-xl bg-slate-800/40 border border-slate-700/60 text-center">
            <p className="text-2xl font-bold text-slate-400">{noTargetCount}</p>
            <p className="text-xs text-slate-400 font-semibold mt-1">Dropped From Sizing (No Target)</p>
          </div>
        </div>

        <div className="space-y-2">
          {positionData.filter(p => Math.abs(p.weight_change ?? 0) > 0.005).slice(0, 6).map((p) => {
            const isBuy = (p.weight_change ?? 0) > 0;
            return (
              <div key={p.ticker} className={`flex items-center justify-between p-3 rounded-lg border text-xs ${
                isBuy ? 'bg-emerald-950/20 border-emerald-800/30 text-emerald-200' : 'bg-rose-950/20 border-rose-800/30 text-rose-200'
              }`}>
                <div className="flex items-center space-x-2">
                  <span className={`w-2 h-2 rounded-full ${isBuy ? 'bg-emerald-400' : 'bg-rose-400'}`} />
                  <span className="font-semibold">{isBuy ? 'Increase' : 'Decrease'} {p.ticker}</span>
                </div>
                <span className="font-mono font-bold">
                  {(p.weight_change ?? 0) > 0 ? '+' : ''}{formatPercentage(p.weight_change)}
                </span>
              </div>
            );
          })}
        </div>

        {/* Dropped legs stay visible instead of vanishing from the roster */}
        {noTargetCount > 0 && (
          <div
            data-testid="dropped-legs"
            className="mt-3 space-y-2"
          >
            {positionData.filter(p => p.weight_change === null).map((p) => (
              <div
                key={p.ticker}
                className="flex items-center justify-between p-3 rounded-lg border border-slate-700/60 bg-slate-800/40 text-xs text-slate-300"
              >
                <div className="flex items-center space-x-2">
                  <span className="w-2 h-2 rounded-full bg-slate-500" />
                  <span className="font-semibold">{p.ticker} — no sizing instruction</span>
                </div>
                <span className="font-mono">{p.trade.label}</span>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Volatility Sizing Insights */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-sm">
        <h3 className="text-lg font-bold text-white mb-4">Volatility Sizing Insights</h3>
        <div className="space-y-3">
          {totalWeightChange > 0.10 && (
            <div className="flex items-start space-x-3 p-3.5 bg-amber-950/20 border border-amber-800/40 rounded-xl">
              <AlertTriangle className="w-5 h-5 text-amber-400 mt-0.5 shrink-0" />
              <div>
                <h4 className="text-xs font-bold text-amber-300 uppercase tracking-wider">Significant Rebalancing Opportunity</h4>
                <p className="text-xs text-slate-300 mt-0.5 leading-relaxed">
                  Total weight adjustment of {(totalWeightChange * 100).toFixed(1)}% will balance marginal risk contribution across all {universeCount || 'N/A'} holdings.
                </p>
              </div>
            </div>
          )}

          <div className="flex items-start space-x-3 p-3.5 bg-teal-950/20 border border-teal-800/40 rounded-xl">
            <BarChart3 className="w-5 h-5 text-teal-400 mt-0.5 shrink-0" />
            <div>
              <h4 className="text-xs font-bold text-teal-300 uppercase tracking-wider">Active Methodology</h4>
              <p className="text-xs text-slate-300 mt-0.5 leading-relaxed">
                {sizingData?.methodology || `${selectedModel} inverse-volatility risk parity with target volatility scaling to ${formatPercentage(targetVolatility)}.`}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}