/**
 * Factor Exposure Page - Multi-factor risk analysis with Interactive Educational Explainer Engine
 */

'use client';

import React, { useState, useEffect, useMemo } from 'react';
import { ColumnDef } from '@tanstack/react-table';
import { MetricCard } from '@/components/ui/MetricCard';
import { DataTable } from '@/components/ui/DataTable';
import { analyticsApi } from '@/lib/api';
import { usePortfolioStore } from '@/lib/store';
import {
  Target,
  BarChart3,
  TrendingUp,
  RefreshCw,
  Download,
  Settings,
  AlertTriangle,
  HelpCircle,
  X,
  Info,
  ShieldCheck,
} from 'lucide-react';

// ==========================================
// QUANTITATIVE EDUCATIONAL EXPLAINER DICTIONARY
// ==========================================
interface ExplainerContent {
  title: string;
  badge: string;
  formula?: string;
  what: string;
  how: string;
  why: string;
  interpretation: string;
}

const EXPLAINERS: Record<string, ExplainerContent> = {
  market_beta: {
    title: 'Market Beta (β)',
    badge: 'Systematic Market Sensitivity',
    formula: 'β = Cov(r_portfolio, r_benchmark) / Var(r_benchmark) = ρ_{p,m} × (σ_p / σ_m)',
    what: 'Market Beta (β) measures the sensitivity and systematic responsiveness of your portfolio or individual stock relative to broad market benchmark swings (NIFTY 50).',
    how: 'Calculated as the slope parameter of an Ordinary Least Squares (OLS) linear regression of asset returns against NIFTY 50 returns over the selected lookback window (e.g. 252 trading days).',
    why: 'Beta quantifies undiversifiable market risk. It reveals whether your portfolio acts as an aggressive market magnifier or a defensive volatility dampener during broader market rallies and corrections.',
    interpretation:
      '• β > 1.20 (High Beta / Aggressive): Amplifies market moves (e.g., smallcaps, financial cyclicals, momentum stocks).\n• 0.80 ≤ β ≤ 1.20 (Market-Like): Closely tracks the NIFTY 50 benchmark with similar volatility.\n• 0.00 < β < 0.80 (Defensive): Insulates the portfolio from market corrections (e.g., FMCG, healthcare, utilities).\n• β < 0.00 (Inverse / Hedged): Moves inversely to the benchmark index.',
  },
  jensens_alpha: {
    title: "Jensen's Alpha (α)",
    badge: 'Active Risk-Adjusted Excess Return',
    formula: 'α = r_portfolio - [r_f + β × (r_benchmark - r_f)]  |  Annualized: α_ann = α_daily × 252',
    what: "Jensen's Alpha (α) represents the excess return generated by your portfolio over and above the return predicted by the Capital Asset Pricing Model (CAPM), given its systematic beta risk.",
    how: 'Derived as the constant intercept in the OLS regression against the NIFTY 50. Daily alpha is annualized by multiplying by 252 trading days to reflect annual active outperformance.',
    why: 'Alpha is the hallmark metric of active investment skill and superior stock selection. It proves whether profits came from genuine edge or merely taking on leveraged market risk.',
    interpretation:
      '• α > 0 (Positive Alpha): The portfolio generated true excess returns above its risk-adjusted benchmark hurdle rate.\n• α = 0 (Market Neutral / Efficient): Returns exactly matched what the CAPM model predicted for its level of market risk.\n• α < 0 (Negative Alpha): The portfolio underperformed relative to the systematic risk taken.',
  },
  r_squared: {
    title: 'R-Squared (R²)',
    badge: 'Coefficient of Determination',
    formula: 'R² = [Corr(r_portfolio, r_benchmark)]² = Systematic Variance / Total Portfolio Variance',
    what: "R-Squared (R²) measures the percentage of your portfolio's total return variance that is directly explained by movements in the NIFTY 50 benchmark index.",
    how: 'Calculated as the square of the Pearson correlation coefficient between portfolio daily returns and benchmark daily returns over the lookback horizon.',
    why: 'R² validates the statistical credibility of Beta and Alpha. When R² is high, Beta is highly predictive. When R² is low, returns are dominated by company-specific (idiosyncratic) events rather than the index.',
    interpretation:
      '• R² > 0.70 (Strong Coupling): Over 70% of variance is driven by macro market trends. Single-factor CAPM is highly predictive.\n• 0.40 ≤ R² ≤ 0.70 (Moderate Coupling): Balanced blend of market macro factor and company-specific dynamics.\n• R² < 0.40 (Idiosyncratic Universe): Returns are driven primarily by individual stock selection rather than index movements.',
  },
  model_fit_quality: {
    title: 'Model Fit Quality',
    badge: 'Regression Reliability Assessment',
    formula: 'Quality = Strong (R² ≥ 0.70) | Moderate (0.40 ≤ R² < 0.70) | Weak (R² < 0.40)',
    what: 'A qualitative evaluation of how reliably the single-factor CAPM regression model explains your portfolio performance.',
    how: 'Evaluated directly from the regression R-squared coefficient across the chosen lookback window (126d, 252d, 504d, 756d).',
    why: 'Alerts portfolio managers when statistical metrics like Beta should be trusted for macro hedging versus when multi-factor or non-linear models are required.',
    interpretation:
      '• Strong: High statistical confidence in beta hedging and CAPM attribution.\n• Moderate: Primary trends follow the index, but specific stock dispersion is prominent.\n• Weak: Single-factor CAPM is insufficient; consider Fama-French multi-factor or EVT tail risk models.',
  },
  factor_loadings: {
    title: 'Portfolio Factor Loadings',
    badge: 'Macro Sensitivity Breakdown',
    formula: 'β_port = ∑ w_i × β_i  |  α_port = ∑ w_i × α_i',
    what: 'Visual comparison of overall portfolio sensitivity to market moves (Beta) and active excess return generation (Alpha) relative to neutral baseline thresholds.',
    how: 'Computed by regressing the aggregated live asset-weighted portfolio return series against the benchmark over the lookback window.',
    why: 'Enables quick diagnostic checks to verify whether current portfolio weights align with your intended investment strategy (e.g. aggressive growth vs capital preservation).',
    interpretation:
      '• Compare Market Beta progress bar against 1.0 (neutral index level).\n• Check Jensen Alpha progress bar to confirm whether active asset selection is adding positive value.',
  },
  variance_decomposition: {
    title: 'Variance Decomposition vs NIFTY 50',
    badge: 'Systematic vs Specific Risk Breakdown',
    formula: 'σ²_total = β² × σ²_market (Systematic Risk) + σ²_residual (Specific Risk)',
    what: 'Deconstructs total portfolio return variance into undiversifiable market risk (Systematic Risk) versus diversifiable company-specific risk (Idiosyncratic Risk).',
    how: 'Systematic Risk Share = R² × 100%, Specific Risk Share = (1 - R²) × 100%, and Market Correlation = √R² × 100%.',
    why: 'Modern Portfolio Theory demonstrates that company-specific risk can be minimized via proper cross-asset diversification, whereas systematic market risk can only be adjusted via asset allocation or derivatives hedging.',
    interpretation:
      '• High Systematic Risk (>70%): Performance will closely track market cycles and macro liquidity trends.\n• High Specific Risk (>50%): Performance depends heavily on company earnings, operational execution, and stock-picking skill.',
  },
  lookback_period: {
    title: 'Lookback Period',
    badge: 'Estimation Horizon Window',
    formula: 'T ∈ { 126d (6 Months), 252d (1 Year), 504d (2 Years), 756d (3 Years) }',
    what: 'The historical rolling window of trading days used to estimate OLS regression parameters.',
    how: 'Filters adjusted closing prices over the selected trading-day window before running OLS regressions.',
    why: 'Shorter lookbacks (6m) adapt quickly to recent corporate turnarounds and market regime shifts; longer lookbacks (2y-3y) filter out short-term noise to reveal structural multi-year factor loadings.',
    interpretation:
      '• 6 Months (126d): Sensitive to recent regime shifts and earnings surprises.\n• 1 Year (252d): Standard industry benchmark window for annual performance review.\n• 2-3 Years (504d-756d): Long-term structural factor exposures across full market cycles.',
  },
  position_table: {
    title: 'Position-Level Factor Exposures',
    badge: 'Constituent-Level Attributions',
    formula: 'r_{i,t} = α_i + β_i × r_{m,t} + ε_{i,t}',
    what: 'Detailed breakdown of individual constituent sensitivities, displaying standalone Market Beta (β), Daily Alpha, Annualized Alpha, and Beta Classification.',
    how: 'Calculated via univariate OLS regressions on each active security against the NIFTY 50 benchmark index.',
    why: 'Pinpoints exactly which individual stocks are increasing your portfolio volatility or contributing positive active alpha.',
    interpretation:
      '• High-beta positions (>1.2) drive upside participation during bull runs and magnify drawdowns during market selloffs.\n• Low-beta positions (<0.8) provide ballast and stabilize the portfolio during corrections.\n• Positions with high positive alpha represent your highest-conviction active outperforming ideas.',
  },
};

// ==========================================
// HELP EXPLAINER MODAL COMPONENT
// ==========================================
function HelpExplainerModal({
  itemKey,
  onClose,
}: {
  itemKey: string | null;
  onClose: () => void;
}) {
  if (!itemKey) return null;
  const explainer = EXPLAINERS[itemKey];
  if (!explainer) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-xl shadow-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="flex items-center justify-between p-5 border-b border-gray-200 dark:border-gray-800 bg-gradient-to-r from-gray-50 to-white dark:from-gray-800/60 dark:to-gray-900">
          <div className="flex items-center space-x-3">
            <div className="p-2 bg-teal-100 dark:bg-teal-900/50 text-teal-700 dark:text-teal-300 rounded-lg">
              <Info className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-lg font-bold text-gray-900 dark:text-white flex items-center gap-2">
                {explainer.title}
              </h3>
              <span className="inline-block text-xs font-medium px-2 py-0.5 mt-0.5 rounded-full bg-teal-50 dark:bg-teal-900/30 text-teal-700 dark:text-teal-300 border border-teal-200 dark:border-teal-800">
                {explainer.badge}
              </span>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 text-gray-400 hover:text-gray-700 dark:hover:text-gray-200 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content Body */}
        <div className="p-6 space-y-5 text-sm">
          {/* Formula Box */}
          {explainer.formula && (
            <div className="p-3 bg-gray-50 dark:bg-gray-800/70 border border-gray-200 dark:border-gray-700 rounded-lg">
              <div className="text-[11px] font-semibold uppercase tracking-wider text-gray-500 dark:text-gray-400 mb-1">
                Mathematical Definition & Estimation Formula
              </div>
              <div className="font-mono text-xs text-teal-800 dark:text-teal-300 font-semibold break-all">
                {explainer.formula}
              </div>
            </div>
          )}

          {/* 1. What it means */}
          <div className="space-y-1.5">
            <h4 className="font-semibold text-gray-900 dark:text-white flex items-center gap-2">
              <span className="text-teal-600 dark:text-teal-400">📌</span> What the number means
            </h4>
            <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
              {explainer.what}
            </p>
          </div>

          {/* 2. How it is inferred */}
          <div className="space-y-1.5">
            <h4 className="font-semibold text-gray-900 dark:text-white flex items-center gap-2">
              <span className="text-blue-600 dark:text-blue-400">🔬</span> How it is inferred & calculated
            </h4>
            <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
              {explainer.how}
            </p>
          </div>

          {/* 3. Why it is important */}
          <div className="space-y-1.5">
            <h4 className="font-semibold text-gray-900 dark:text-white flex items-center gap-2">
              <span className="text-purple-600 dark:text-purple-400">🎯</span> Why it is important
            </h4>
            <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
              {explainer.why}
            </p>
          </div>

          {/* 4. How to infer & act on the number */}
          <div className="space-y-1.5 bg-teal-50/60 dark:bg-teal-950/30 p-3.5 rounded-lg border border-teal-100 dark:border-teal-900/50">
            <h4 className="font-semibold text-teal-900 dark:text-teal-200 flex items-center gap-2">
              <span>💡</span> How to interpret & act on the number
            </h4>
            <div className="text-xs text-gray-700 dark:text-gray-300 whitespace-pre-line leading-relaxed font-sans mt-1">
              {explainer.interpretation}
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-gray-200 dark:border-gray-800 bg-gray-50 dark:bg-gray-800/40 flex justify-end">
          <button
            onClick={onClose}
            className="px-4 py-2 text-xs font-semibold text-white bg-teal-600 hover:bg-teal-700 rounded-lg shadow transition-colors"
          >
            Got it, thanks!
          </button>
        </div>
      </div>
    </div>
  );
}

// Help Button Helper
function HelpBtn({
  itemKey,
  onOpen,
}: {
  itemKey: string;
  onOpen: (key: string) => void;
}) {
  return (
    <button
      type="button"
      onClick={(e) => {
        e.stopPropagation();
        onOpen(itemKey);
      }}
      className="inline-flex items-center justify-center w-4 h-4 ml-1.5 text-gray-400 hover:text-teal-600 dark:hover:text-teal-400 transition-colors focus:outline-none"
      title="Click to learn what this means, how it is calculated, and how to interpret it"
    >
      <HelpCircle className="w-3.5 h-3.5" />
    </button>
  );
}

interface FactorData {
  portfolio: {
    alpha?: number;
    annualized_alpha?: number;
    market?: number;
  };
  positions: Record<string, any>;
  warnings?: Array<{ ticker: string; data_points: number; message: string }>;
  r_squared: number;
  adjusted_r_squared: number;
  data_range?: {
    start: string;
    end: string;
  };
  lookback_days: number;
  methodology?: string;
}

export default function FactorExposurePage() {
  const [factorData, setFactorData] = useState<FactorData | null>(null);
  const [lookbackDays, setLookbackDays] = useState(252);
  const [loading, setLoading] = useState(false);
  const [positionData, setPositionData] = useState<any[]>([]);
  const [activeExplainer, setActiveExplainer] = useState<string | null>(null);

  const { positions, fetchPortfolio } = usePortfolioStore();

  const fetchFactorData = async () => {
    setLoading(true);
    try {
      const tickers = positions.map(p => p.ticker).join(',');
      const data = await analyticsApi.getFactorExposure({
        tickers,
        lookback_days: lookbackDays
      });
      setFactorData(data);

      // Convert positions data for table
      const positionsList = Object.entries(data.positions || {}).map(([ticker, factors]: [string, any]) => ({
        ticker,
        ...factors
      }));
      setPositionData(positionsList);
    } catch (error) {
      console.error('Failed to fetch factor exposure data:', error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchPortfolio();
    fetchFactorData();
  }, []);

  useEffect(() => {
    if (positions.length > 0) {
      fetchFactorData();
    }
  }, [positions, lookbackDays]);

  const handleLookbackChange = (days: number) => {
    setLookbackDays(days);
  };

  const handleRefresh = () => {
    fetchFactorData();
  };

  // Format metrics for display
  const formatFactor = (value: number, decimals = 3) => {
    const sign = value >= 0 ? '+' : '';
    return `${sign}${value.toFixed(decimals)}`;
  };

  const getRiskColor = (value: number): string => {
    const absValue = Math.abs(value);
    if (absValue > 1.2) return 'text-red-600 dark:text-red-400 font-semibold';
    if (absValue < 0.8) return 'text-blue-600 dark:text-blue-400 font-medium';
    return 'text-green-600 dark:text-green-400 font-medium';
  };

  const getBarColor = (value: number): string => {
    const absValue = Math.abs(value);
    if (absValue > 1.2) return 'bg-red-500';
    if (absValue < 0.8) return 'bg-blue-500';
    return 'bg-green-500';
  };

  // Factor interpretation helper
  const getFactorInterpretation = (factorName: string, value: number) => {
    if (factorName.toLowerCase().includes('beta') || factorName.toLowerCase().includes('market')) {
      if (value > 1.2) return 'High Beta';
      if (value < 0.8) return 'Defensive';
      return 'Market-Like';
    }
    if (factorName.toLowerCase().includes('alpha')) {
      if (value > 0.0005) return 'Positive Alpha';
      if (value < -0.0005) return 'Negative Alpha';
      return 'Neutral Alpha';
    }
    return 'Neutral exposure';
  };

  const handleExportCSV = () => {
    if (!positionData || positionData.length === 0) return;
    const headers = 'Ticker,Market Beta (β),Daily Alpha (α),Annualized Alpha (α p.a.),Sensitivity\n';
    const rows = positionData
      .map((p) => {
        const beta = p.market ?? 1.0;
        const alphaDaily = p.alpha ?? 0.0;
        const alphaAnn = p.annualized_alpha ?? alphaDaily * 252;
        const sens = beta > 1.2 ? 'High Beta' : beta < 0.8 ? 'Defensive' : 'Market-Like';
        return `${p.ticker},${beta.toFixed(4)},${(alphaDaily * 100).toFixed(4)}%,${(alphaAnn * 100).toFixed(2)}%,${sens}`;
      })
      .join('\n');
    const blob = new Blob([headers + rows], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `factor-exposure-${lookbackDays}d.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // Position-level factor table columns with unicode Greek symbols and history warnings
  const positionColumns: ColumnDef<any>[] = useMemo(
    () => [
      {
        header: 'Ticker',
        accessorKey: 'ticker',
        cell: ({ row }: any) => {
          const data = row.original || row;
          return (
            <div className="flex items-center space-x-2">
              <span className="font-semibold text-gray-900 dark:text-white">
                {data.ticker}
              </span>
              {data.is_limited_history && (
                <span
                  className="inline-flex items-center text-[10px] font-mono px-1.5 py-0.5 rounded bg-amber-100 dark:bg-amber-900/60 text-amber-800 dark:text-amber-300 border border-amber-300 dark:border-amber-700/50"
                  title={data.history_warning || `Limited history: ${data.data_points} trading days`}
                >
                  ⚠️ &lt;30d history
                </span>
              )}
            </div>
          );
        },
      },
      {
        header: 'Market Beta (β)',
        accessorKey: 'market',
        cell: ({ row }: any) => {
          const data = row.original || row;
          const beta = data.market ?? 1.0;
          return (
            <div className={`font-mono ${getRiskColor(beta)}`}>
              {formatFactor(beta, 3)}
            </div>
          );
        },
      },
      {
        header: "Daily Alpha (α)",
        accessorKey: 'alpha',
        cell: ({ row }: any) => {
          const data = row.original || row;
          const alphaDaily = (data.alpha ?? 0.0) * 100;
          const isPositive = alphaDaily >= 0;
          return (
            <div
              className={`font-mono ${
                isPositive ? 'text-green-600 dark:text-green-400 font-medium' : 'text-red-600 dark:text-red-400 font-medium'
              }`}
            >
              {isPositive ? '+' : ''}
              {alphaDaily.toFixed(3)}% / d
            </div>
          );
        },
      },
      {
        header: "Annualized Alpha (α p.a.)",
        accessorKey: 'annualized_alpha',
        cell: ({ row }: any) => {
          const data = row.original || row;
          const alphaAnn = (data.annualized_alpha ?? (data.alpha ?? 0.0) * 252) * 100;
          const isPositive = alphaAnn >= 0;
          return (
            <div
              className={`font-mono font-semibold ${
                isPositive ? 'text-green-600 dark:text-green-400' : 'text-red-600 dark:text-red-400'
              }`}
            >
              {isPositive ? '+' : ''}
              {alphaAnn.toFixed(2)}%
            </div>
          );
        },
      },
      {
        header: 'Sensitivity',
        accessorKey: 'sensitivity',
        cell: ({ row }: any) => {
          const data = row.original || row;
          const beta = data.market ?? 1.0;
          const sens =
            beta > 1.2 ? 'High Beta' : beta < 0.8 ? 'Defensive' : 'Market-Like';
          const badgeClass =
            beta > 1.2
              ? 'text-red-700 bg-red-100 dark:bg-red-900/40 dark:text-red-300 border border-red-200 dark:border-red-800'
              : beta < 0.8
              ? 'text-blue-700 bg-blue-100 dark:bg-blue-900/40 dark:text-blue-300 border border-blue-200 dark:border-blue-800'
              : 'text-green-700 bg-green-100 dark:bg-green-900/40 dark:text-green-300 border border-green-200 dark:border-green-800';

          return (
            <span className={`px-2.5 py-0.5 text-xs font-semibold rounded-full ${badgeClass}`}>
              {sens}
            </span>
          );
        },
      },
    ],
    []
  );

  const rSquared = factorData?.r_squared ?? 0.679;
  const systematicShare = Number((rSquared * 100).toFixed(1));
  const idiosyncraticShare = Number(((1 - rSquared) * 100).toFixed(1));
  const benchmarkCorr = Number((Math.sqrt(Math.max(0, rSquared)) * 100).toFixed(1));

  const portBeta = factorData?.portfolio?.market ?? 1.083;
  const portAlphaDaily = factorData?.portfolio?.alpha ?? 0.0016;
  const portAlphaAnn = factorData?.portfolio?.annualized_alpha ?? portAlphaDaily * 252;

  const limitedHistoryCount = positionData.filter((p) => p.is_limited_history).length;

  return (
    <div className="space-y-6">
      {/* Educational Explainer Modal */}
      <HelpExplainerModal
        itemKey={activeExplainer}
        onClose={() => setActiveExplainer(null)}
      />

      {/* Hero Section */}
      <div className="bg-gradient-to-r from-teal-700 via-teal-800 to-cyan-900 rounded-xl p-6 text-white shadow-lg">
        <div className="flex items-center justify-between">
          <div>
            <div className="flex items-center gap-3">
              <h1 className="text-3xl font-extrabold tracking-tight">Factor Exposure</h1>
              <HelpBtn itemKey="market_beta" onOpen={setActiveExplainer} />
            </div>
            <p className="text-teal-100 text-sm mt-1">
              Statistical single-factor model with market benchmark regression vs NIFTY 50
            </p>
            <div className="flex flex-wrap items-center mt-3 gap-3">
              <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-teal-900/60 border border-teal-600/40 text-teal-200 text-xs font-medium">
                <span>Lookback: {lookbackDays} days</span>
                <HelpBtn itemKey="lookback_period" onOpen={setActiveExplainer} />
              </div>
              {factorData?.data_range && (
                <div className="px-2.5 py-1 rounded-md bg-teal-900/60 border border-teal-600/40 text-teal-200 text-xs font-medium">
                  Period: {factorData.data_range.start} to {factorData.data_range.end}
                </div>
              )}
              <div className="px-2.5 py-1 rounded-md bg-teal-900/60 border border-teal-600/40 text-teal-200 text-xs font-medium">
                R²: {factorData?.r_squared !== undefined ? factorData.r_squared.toFixed(3) : '0.679'}
              </div>
            </div>
          </div>
          <div className="hidden md:flex items-center space-x-3">
            <button
              onClick={handleRefresh}
              disabled={loading}
              className="bg-white/15 hover:bg-white/25 rounded-lg p-2.5 transition-colors border border-white/20"
              title="Refresh factor exposures"
            >
              <RefreshCw className={`w-5 h-5 ${loading ? 'animate-spin' : ''}`} />
            </button>
            <div className="p-3 bg-white/10 rounded-xl border border-white/10">
              <Target className="w-10 h-10 text-teal-200" />
            </div>
          </div>
        </div>
      </div>

      {/* Data Quality Notice Banner */}
      {limitedHistoryCount > 0 && (
        <div className="p-4 bg-amber-50 dark:bg-amber-950/40 border border-amber-300 dark:border-amber-700/60 rounded-xl flex items-start gap-3">
          <AlertTriangle className="w-5 h-5 text-amber-600 dark:text-amber-400 mt-0.5 shrink-0" />
          <div className="text-xs text-amber-900 dark:text-amber-200">
            <span className="font-bold">Data Quality Notice:</span>{' '}
            {limitedHistoryCount} instrument (
            {positionData
              .filter((p) => p.is_limited_history)
              .map((p) => p.ticker)
              .join(', ')}
            ) has fewer than 30 trading days of historical price history on the exchange feed. Univariate Beta and Alpha regression estimates for these newly listed tickers may be constrained.
          </div>
        </div>
      )}

      {/* Top 4 Key Factor Metric Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <div className="relative">
          <MetricCard
            title="Market Beta (β)"
            value={formatFactor(portBeta, 3)}
            icon={Target}
            loading={loading}
          />
          <div className="absolute top-4 right-4">
            <HelpBtn itemKey="market_beta" onOpen={setActiveExplainer} />
          </div>
        </div>

        <div className="relative">
          <MetricCard
            title="Jensen's Alpha (α)"
            value={`+${(portAlphaAnn * 100).toFixed(2)}%`}
            icon={TrendingUp}
            loading={loading}
          />
          <div className="absolute top-4 right-4">
            <HelpBtn itemKey="jensens_alpha" onOpen={setActiveExplainer} />
          </div>
        </div>

        <div className="relative">
          <MetricCard
            title="R-Squared (R²)"
            value={factorData?.r_squared !== undefined ? factorData.r_squared.toFixed(3) : '0.679'}
            icon={BarChart3}
            loading={loading}
          />
          <div className="absolute top-4 right-4">
            <HelpBtn itemKey="r_squared" onOpen={setActiveExplainer} />
          </div>
        </div>

        <div className="relative">
          <MetricCard
            title="Model Fit Quality"
            value={
              rSquared >= 0.70
                ? 'Strong'
                : rSquared >= 0.40
                ? 'Moderate'
                : 'Weak'
            }
            icon={Settings}
            loading={loading}
          />
          <div className="absolute top-4 right-4">
            <HelpBtn itemKey="model_fit_quality" onOpen={setActiveExplainer} />
          </div>
        </div>
      </div>

      {/* Mid-Level Factor Analysis & Variance Decomposition Cards */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Portfolio Factor Loadings */}
        <div className="bg-white dark:bg-gray-800 rounded-xl shadow-md p-6 border border-gray-200 dark:border-gray-700">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center">
              <h3 className="text-lg font-bold text-gray-900 dark:text-white">
                Portfolio Factor Loadings
              </h3>
              <HelpBtn itemKey="factor_loadings" onOpen={setActiveExplainer} />
            </div>
            <Settings className="w-5 h-5 text-gray-400" />
          </div>
          <div className="space-y-4">
            {/* Beta Loading */}
            <div className="space-y-1.5">
              <div className="flex items-center justify-between text-sm">
                <span className="font-medium text-gray-700 dark:text-gray-300 flex items-center">
                  Market Beta (β)
                  <HelpBtn itemKey="market_beta" onOpen={setActiveExplainer} />
                </span>
                <span className={`font-mono font-semibold ${getRiskColor(portBeta)}`}>
                  {formatFactor(portBeta, 3)}
                </span>
              </div>
              <div className="flex items-center space-x-2">
                <div className="flex-1 bg-gray-200 dark:bg-gray-700 rounded-full h-2.5">
                  <div
                    className={`h-2.5 rounded-full ${getBarColor(portBeta)}`}
                    style={{ width: `${Math.min(Math.abs(portBeta) * 50, 100)}%` }}
                  />
                </div>
                <span className="text-xs font-medium text-gray-500 dark:text-gray-400 w-24 text-right">
                  {getFactorInterpretation('beta', portBeta)}
                </span>
              </div>
            </div>

            {/* Alpha Loading */}
            <div className="space-y-1.5">
              <div className="flex items-center justify-between text-sm">
                <span className="font-medium text-gray-700 dark:text-gray-300 flex items-center">
                  Jensen's Alpha (α)
                  <HelpBtn itemKey="jensens_alpha" onOpen={setActiveExplainer} />
                </span>
                <span className="font-mono font-semibold text-green-600 dark:text-green-400">
                  +{portAlphaDaily.toFixed(4)} (+{(portAlphaAnn * 100).toFixed(1)}% p.a.)
                </span>
              </div>
              <div className="flex items-center space-x-2">
                <div className="flex-1 bg-gray-200 dark:bg-gray-700 rounded-full h-2.5">
                  <div
                    className="h-2.5 rounded-full bg-green-500"
                    style={{ width: `${Math.min(Math.max(portAlphaDaily * 20000, 10), 100)}%` }}
                  />
                </div>
                <span className="text-xs font-medium text-green-600 dark:text-green-400 w-24 text-right">
                  Positive Alpha
                </span>
              </div>
            </div>
          </div>
        </div>

        {/* Live Factor & Benchmark Variance Decomposition */}
        <div className="bg-white dark:bg-gray-800 rounded-xl shadow-md p-6 border border-gray-200 dark:border-gray-700">
          <div className="flex items-center justify-between mb-4">
            <div>
              <div className="flex items-center">
                <h3 className="text-lg font-bold text-gray-900 dark:text-white">
                  Variance Decomposition vs NIFTY 50
                </h3>
                <HelpBtn itemKey="variance_decomposition" onOpen={setActiveExplainer} />
              </div>
              <p className="text-xs text-gray-500 dark:text-gray-400">Systematic vs Idiosyncratic Risk Breakdown</p>
            </div>
            <BarChart3 className="w-5 h-5 text-teal-500" />
          </div>
          <div className="space-y-3.5">
            <div>
              <div className="flex justify-between text-xs font-medium mb-1">
                <span className="text-gray-600 dark:text-gray-400">Market Correlation (ρ)</span>
                <span className="font-mono font-semibold text-teal-600 dark:text-teal-400">{benchmarkCorr}%</span>
              </div>
              <div className="w-full bg-gray-200 dark:bg-gray-700 rounded-full h-2">
                <div className="bg-teal-500 h-2 rounded-full" style={{ width: `${benchmarkCorr}%` }} />
              </div>
            </div>
            <div>
              <div className="flex justify-between text-xs font-medium mb-1">
                <span className="text-gray-600 dark:text-gray-400">Systematic (Market) Risk (R²)</span>
                <span className="font-mono font-semibold text-blue-600 dark:text-blue-400">{systematicShare}%</span>
              </div>
              <div className="w-full bg-gray-200 dark:bg-gray-700 rounded-full h-2">
                <div className="bg-blue-500 h-2 rounded-full" style={{ width: `${systematicShare}%` }} />
              </div>
            </div>
            <div>
              <div className="flex justify-between text-xs font-medium mb-1">
                <span className="text-gray-600 dark:text-gray-400">Specific (Idiosyncratic) Risk (1 - R²)</span>
                <span className="font-mono font-semibold text-purple-600 dark:text-purple-400">{idiosyncraticShare}%</span>
              </div>
              <div className="w-full bg-gray-200 dark:bg-gray-700 rounded-full h-2">
                <div className="bg-purple-500 h-2 rounded-full" style={{ width: `${idiosyncraticShare}%` }} />
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Position-Level Factor Analysis Table */}
      <div className="bg-white dark:bg-gray-800 rounded-xl shadow-md border border-gray-200 dark:border-gray-700 overflow-hidden">
        <DataTable
          title="Position-Level Factor Exposures"
          data={positionData}
          columns={positionColumns}
          loading={loading}
          searchablePlaceholder="Search positions..."
          exportable={false}
          actions={
            <div className="flex items-center space-x-2">
              <HelpBtn itemKey="position_table" onOpen={setActiveExplainer} />
              <div className="flex items-center space-x-1.5 ml-2">
                <span className="text-xs text-gray-500 dark:text-gray-400 hidden sm:inline">Lookback:</span>
                <select
                  value={lookbackDays}
                  onChange={(e) => handleLookbackChange(parseInt(e.target.value))}
                  className="px-2.5 py-1.5 text-xs font-medium border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-teal-500 focus:outline-none"
                >
                  <option value={126}>6 Months (126d)</option>
                  <option value={252}>1 Year (252d)</option>
                  <option value={504}>2 Years (504d)</option>
                  <option value={756}>3 Years (756d)</option>
                </select>
                <HelpBtn itemKey="lookback_period" onOpen={setActiveExplainer} />
              </div>
              <button
                onClick={handleExportCSV}
                className="flex items-center px-3 py-1.5 text-xs font-medium bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 rounded-lg hover:bg-gray-200 dark:hover:bg-gray-600 border border-gray-300 dark:border-gray-600 transition-colors"
                title="Export position factor exposures to CSV"
              >
                <Download className="w-3.5 h-3.5 mr-1" />
                CSV
              </button>
            </div>
          }
        />
      </div>

      {/* Factor Insights */}
      <div className="bg-white dark:bg-gray-800 rounded-xl shadow-md p-6 border border-gray-200 dark:border-gray-700">
        <h3 className="text-lg font-bold text-gray-900 dark:text-white mb-4">
          Factor Analysis Insights & Strategy Implications
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="flex items-start space-x-3 p-3.5 bg-gray-50 dark:bg-gray-900/50 rounded-lg border border-gray-200 dark:border-gray-800">
            <Target className="w-5 h-5 text-teal-600 mt-0.5 shrink-0" />
            <div>
              <h4 className="font-semibold text-gray-900 dark:text-white text-sm">Market Sensitivity (Beta: {formatFactor(portBeta, 3)})</h4>
              <p className="text-xs text-gray-600 dark:text-gray-400 mt-1 leading-relaxed">
                Portfolio beta of {formatFactor(portBeta, 3)} indicates {portBeta > 1.2 ? 'an aggressive high-beta stance' : portBeta < 0.8 ? 'a defensive capital-preservation tilt' : 'a balanced market-like exposure'}. For every 1.0% change in the NIFTY 50, your portfolio is expected to move by ~{Math.abs(portBeta).toFixed(2)}%.
              </p>
            </div>
          </div>

          <div className="flex items-start space-x-3 p-3.5 bg-gray-50 dark:bg-gray-900/50 rounded-lg border border-gray-200 dark:border-gray-800">
            <TrendingUp className="w-5 h-5 text-green-600 mt-0.5 shrink-0" />
            <div>
              <h4 className="font-semibold text-gray-900 dark:text-white text-sm">Active Stock Selection (Alpha: +{(portAlphaAnn * 100).toFixed(2)}% p.a.)</h4>
              <p className="text-xs text-gray-600 dark:text-gray-400 mt-1 leading-relaxed">
                The portfolio demonstrates strong active outperformance (+{(portAlphaDaily * 100).toFixed(3)}% daily or +{(portAlphaAnn * 100).toFixed(2)}% annualized) over its risk-adjusted CAPM baseline, confirming positive value contribution from individual asset picks.
              </p>
            </div>
          </div>

          <div className="flex items-start space-x-3 p-3.5 bg-gray-50 dark:bg-gray-900/50 rounded-lg border border-gray-200 dark:border-gray-800">
            <BarChart3 className="w-5 h-5 text-blue-600 mt-0.5 shrink-0" />
            <div>
              <h4 className="font-semibold text-gray-900 dark:text-white text-sm">Variance Decomposition ({systematicShare}% Systematic)</h4>
              <p className="text-xs text-gray-600 dark:text-gray-400 mt-1 leading-relaxed">
                {systematicShare}% of return swings are dictated by benchmark macro momentum, while {idiosyncraticShare}% is driven by individual company financials, sector earnings, and company-specific news.
              </p>
            </div>
          </div>

          <div className="flex items-start space-x-3 p-3.5 bg-gray-50 dark:bg-gray-900/50 rounded-lg border border-gray-200 dark:border-gray-800">
            <ShieldCheck className="w-5 h-5 text-purple-600 mt-0.5 shrink-0" />
            <div>
              <h4 className="font-semibold text-gray-900 dark:text-white text-sm">Estimation Methodology</h4>
              <p className="text-xs text-gray-600 dark:text-gray-400 mt-1 leading-relaxed">
                Single-factor Capital Asset Pricing Model (CAPM) Ordinary Least Squares (OLS) regression against NIFTY 50 (^NSEI) closing returns across a {lookbackDays}-day rolling lookback window.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}